const HOST="ai.cervel.capture";
const api=globalThis.browser??globalThis.chrome;
const id=()=>crypto.randomUUID();
async function settings(){return api.storage.local.get({vault:"default",project_ref:"",tags:"",capture_intent:"research"});}
async function extract(tabId){return api.tabs.sendMessage(tabId,{type:"CERVEL_EXTRACT"});}
async function enqueue(evidence){const {queue=[]}=await api.storage.local.get({queue:[]});queue.push({id:evidence.request_id,evidence,attempts:0,status:"queued",next_attempt_at:Date.now()});await api.storage.local.set({queue:queue.slice(-500)});await flush();return evidence.request_id;}
async function native(message){const response=await api.runtime.sendNativeMessage(HOST,message);if(!response?.ok)throw new Error(response?.error||"CAPTURE_NATIVE_HOST_FAILED");return response.result;}
async function flush(){const stored=await api.storage.local.get({queue:[]}),queue=stored.queue,remaining=[];for(const item of queue){if(item.next_attempt_at>Date.now()){remaining.push(item);continue;}try{const result=await native({command:"capture",vault:item.evidence.vault,evidence:item.evidence});await api.storage.local.set({last_result:{at:new Date().toISOString(),request_id:item.id,result}});}catch(error){item.attempts++;item.error=String(error?.message??error);const permanent=/CAPTURE_(PROTOCOL|URL|CANONICAL|REQUEST|CONTENT_TOO_LARGE|CONTENT_REQUIRED|WORKSPACE_SCOPE|HOST_COMMAND)/.test(item.error);item.status=permanent?"failed":"retry";item.next_attempt_at=permanent?Number.MAX_SAFE_INTEGER:Date.now()+Math.min(300000,1000*2**item.attempts);remaining.push(item);await api.storage.local.set({last_result:{at:new Date().toISOString(),request_id:item.id,error:item.error}});}}await api.storage.local.set({queue:remaining});return {queued:remaining.length};}
async function build(tab,kind,extra={}){const config=await settings();let data;if(kind==="image"&&extra.srcUrl)data={metadata:{source_url:tab.url,canonical_url:tab.url,title:tab.title,mime_type:"text/uri-list"},content_text:extra.srcUrl};else if(kind==="image"){const screenshot=await api.tabs.captureVisibleTab(tab.windowId,{format:"png"});data={metadata:{source_url:tab.url,canonical_url:tab.url,title:tab.title,mime_type:"image/png"},content_base64:screenshot.split(",")[1]};}else if(kind==="pdf")data={metadata:{source_url:tab.url,canonical_url:tab.url,title:tab.title,mime_type:"application/pdf"},content_text:tab.url};else data=await extract(tab.id);const meta=data.metadata,chosen=kind==="selection"?data.selection?.selected:data.content_text;if(kind==="selection"&&!data.selection)throw new Error("Select text before capturing");return {protocol:"cervel-capture/v0.1",request_id:id(),capture_type:kind,source_url:meta.source_url,canonical_url:meta.canonical_url,title:meta.title||tab.title||"Captured evidence",author:meta.author,published_at:meta.published_at,captured_at:new Date().toISOString(),content_text:chosen,content_base64:data.content_base64,mime_type:meta.mime_type||"text/plain",selection_context:kind==="selection"?data.selection:undefined,image:kind==="image"?{source_url:extra.srcUrl||tab.url}:undefined,user:{note:extra.note,tags:String(extra.tags??config.tags).split(",").map(x=>x.trim()).filter(Boolean),capture_intent:extra.capture_intent??config.capture_intent,project_ref:extra.project_ref??config.project_ref},provenance:{acquisition:"browser_extension",browser:navigator.userAgent,page_language:meta.page_language,referrer:meta.referrer,trust:"untrusted_web_content",instruction_policy:"never_execute"},vault:config.vault};}
api.runtime.onInstalled.addListener(()=>{api.contextMenus.create({id:"cervel-page",title:"Capture page to CERVEL",contexts:["page"]});api.contextMenus.create({id:"cervel-selection",title:"Capture selection to CERVEL",contexts:["selection"]});api.contextMenus.create({id:"cervel-image",title:"Capture image evidence to CERVEL",contexts:["image"]});api.contextMenus.create({id:"cervel-link",title:"Capture link to CERVEL",contexts:["link"]});});
api.contextMenus.onClicked.addListener(async(info,tab)=>{const map={"cervel-page":"page","cervel-selection":"selection","cervel-image":"image","cervel-link":"link"},kind=map[info.menuItemId];if(!kind)return;try{const evidence=await build(tab,kind,{srcUrl:info.srcUrl,note:kind==="link"?info.linkUrl:undefined});if(kind==="link"){evidence.source_url=info.linkUrl;evidence.canonical_url=info.linkUrl;evidence.content_text=info.linkUrl;evidence.mime_type="text/uri-list";}await enqueue(evidence);}catch(error){await api.storage.local.set({last_result:{at:new Date().toISOString(),error:String(error)}});}});
api.runtime.onMessage.addListener((message,_sender,respond)=>{if(message.type==="CERVEL_CAPTURE")api.tabs.query({active:true,currentWindow:true}).then(async([tab])=>respond({ok:true,request_id:await enqueue(await build(tab,message.kind,message.input))})).catch(error=>respond({ok:false,error:String(error)}));else if(message.type==="CERVEL_RETRY")api.storage.local.get({queue:[]}).then(async value=>{for(const item of value.queue){item.next_attempt_at=0;if(item.status==="failed")item.status="queued";}await api.storage.local.set({queue:value.queue});return flush();}).then(result=>respond({ok:true,...result})).catch(error=>respond({ok:false,error:String(error)}));else if(message.type==="CERVEL_STATUS")api.storage.local.get({queue:[],last_result:null}).then(value=>respond({ok:true,queued:value.queue.length,failed:value.queue.filter(item=>item.status==="failed").length,last_result:value.last_result}));else return false;return true;});
api.alarms?.create?.("cervel-retry",{periodInMinutes:1});api.alarms?.onAlarm?.addListener?.(alarm=>{if(alarm.name==="cervel-retry")void flush();});
