const HOST="ai.cervel.capture";
const api=globalThis.browser??globalThis.chrome;
const uuid=()=>crypto.randomUUID().replaceAll("-","");
const prefixed=prefix=>`${prefix}_${uuid()}`;
async function settings(){return api.storage.local.get({vault:"default",project_ref:"",tags:"",capture_intent:"research",pairing:null,embodiment_id:null,device_id:null,queue:[]});}
async function ensureIdentity(){const stored=await settings();const updates={};if(!stored.embodiment_id)updates.embodiment_id=prefixed("emb");if(!stored.device_id)updates.device_id=prefixed("dev");if(Object.keys(updates).length)await api.storage.local.set(updates);return {...stored,...updates};}
async function extract(tabId){return api.tabs.sendMessage(tabId,{type:"CERVEL_EXTRACT"});}
async function native(message){const response=await api.runtime.sendNativeMessage(HOST,message);if(!response?.ok)throw new Error(response?.error||"CAPTURE_NATIVE_HOST_FAILED");return response.result;}
async function pair(){const config=await ensureIdentity();const result=await native({command:"pair",vault:config.vault,embodiment:{protocol:"cervel-embodiment/v0.1",embodiment_id:config.embodiment_id,device_id:config.device_id,kind:"browser_extension",display_name:`CERVEL Capture · ${navigator.platform||"browser"}`,capabilities:["capture.page","capture.selection","capture.link","capture.pdf","capture.note","vault.read","vault.write","vault.search","device.pair"]}});const pairing={...result,paired_at:new Date().toISOString(),embodiment_id:config.embodiment_id,device_id:config.device_id};await api.storage.local.set({pairing,last_pair_error:null});await flush();return pairing;}
async function enqueue(evidence){const stored=await api.storage.local.get({queue:[]});const queue=stored.queue??[];queue.push({id:evidence.request_id,evidence,attempts:0,status:"queued",queued_at:new Date().toISOString(),next_attempt_at:Date.now()});await api.storage.local.set({queue:queue.slice(-500)});await flush();return evidence.request_id;}
async function flush(){const stored=await api.storage.local.get({queue:[],pairing:null}),queue=stored.queue??[],remaining=[];if(!stored.pairing)return {queued:queue.length,paired:false};for(const item of queue){if(item.next_attempt_at>Date.now()){remaining.push(item);continue;}try{const result=await native({command:"capture",vault:item.evidence.vault,evidence:item.evidence});await api.storage.local.set({last_result:{at:new Date().toISOString(),request_id:item.id,result}});}catch(error){item.attempts++;item.error=String(error?.message??error);const permanent=/CAPTURE_(PROTOCOL|URL|CANONICAL|REQUEST|CONTENT_TOO_LARGE|CONTENT_REQUIRED|WORKSPACE_SCOPE|HOST_COMMAND)/.test(item.error);item.status=permanent?"failed":"retry";item.next_attempt_at=permanent?Number.MAX_SAFE_INTEGER:Date.now()+Math.min(300000,1000*2**item.attempts);remaining.push(item);await api.storage.local.set({last_result:{at:new Date().toISOString(),request_id:item.id,error:item.error}});}}await api.storage.local.set({queue:remaining});return {queued:remaining.length,paired:true};}
async function build(tab,kind,extra={}){const config=await ensureIdentity();let data;if(kind==="pdf")data={metadata:{source_url:tab.url,canonical_url:tab.url,title:tab.title||"PDF",mime_type:"application/pdf",page_language:undefined},content_text:tab.url};else if(kind==="link")data={metadata:{source_url:extra.linkUrl||tab.url,canonical_url:extra.linkUrl||tab.url,title:extra.linkText||tab.title||"Link",mime_type:"text/uri-list",page_language:undefined},content_text:extra.linkUrl||tab.url};else data=await extract(tab.id);const meta=data.metadata,chosen=kind==="selection"?data.selection?.selected:data.content_text;if(kind==="selection"&&!data.selection)throw new Error("Select text before capturing");return {protocol:"cervel-capture/v0.1",request_id:`browser_${uuid()}`,capture_type:kind,source_url:meta.source_url,canonical_url:meta.canonical_url,title:meta.title||tab.title||"Captured evidence",author:meta.author,published_at:meta.published_at,captured_at:new Date().toISOString(),content_text:chosen,mime_type:meta.mime_type||"text/plain",selection_context:kind==="selection"?data.selection:undefined,user:{note:extra.note,tags:String(extra.tags??config.tags).split(",").map(x=>x.trim()).filter(Boolean),capture_intent:extra.capture_intent??config.capture_intent,project_ref:extra.project_ref??config.project_ref},provenance:{acquisition:"browser_extension",browser:navigator.userAgent,page_language:meta.page_language,referrer:meta.referrer,trust:"untrusted_web_content",instruction_policy:"never_execute"},client:{embodiment_id:config.embodiment_id,device_id:config.device_id,kind:"browser_extension",app_version:"0.2.0"},vault:config.vault};}
async function status(){const value=await api.storage.local.get({queue:[],last_result:null,pairing:null,last_pair_error:null});let node=null;if(value.pairing){try{node=await native({command:"status",vault:value.pairing.vault??"default"});}catch(error){node={ok:false,error:String(error?.message??error)};}}return {ok:true,paired:Boolean(value.pairing),pairing:value.pairing,node,queued:value.queue.length,failed:value.queue.filter(item=>item.status==="failed").length,last_result:value.last_result,last_pair_error:value.last_pair_error};}
api.runtime.onInstalled.addListener(async()=>{await ensureIdentity();await api.contextMenus.removeAll();api.contextMenus.create({id:"cervel-page",title:"Add page to CERVEL",contexts:["page"]});api.contextMenus.create({id:"cervel-selection",title:"Add selection to CERVEL",contexts:["selection"]});api.contextMenus.create({id:"cervel-link",title:"Add link to CERVEL",contexts:["link"]});});
api.contextMenus.onClicked.addListener(async(info,tab)=>{const map={"cervel-page":"page","cervel-selection":"selection","cervel-link":"link"},kind=map[info.menuItemId];if(!kind)return;try{const evidence=await build(tab,kind,{linkUrl:info.linkUrl,linkText:info.selectionText});await enqueue(evidence);}catch(error){await api.storage.local.set({last_result:{at:new Date().toISOString(),error:String(error)}});}});
api.runtime.onMessage.addListener((message,_sender,respond)=>{if(message.type==="CERVEL_PAIR")pair().then(pairing=>respond({ok:true,pairing})).catch(async error=>{await api.storage.local.set({last_pair_error:String(error?.message??error)});respond({ok:false,error:String(error?.message??error)});});else if(message.type==="CERVEL_CAPTURE")api.tabs.query({active:true,currentWindow:true}).then(async([tab])=>respond({ok:true,request_id:await enqueue(await build(tab,message.kind,message.input))})).catch(error=>respond({ok:false,error:String(error?.message??error)}));else if(message.type==="CERVEL_RETRY")api.storage.local.get({queue:[]}).then(async value=>{for(const item of value.queue){item.next_attempt_at=0;if(item.status==="failed")item.status="queued";}await api.storage.local.set({queue:value.queue});return flush();}).then(result=>respond({ok:true,...result})).catch(error=>respond({ok:false,error:String(error?.message??error)}));else if(message.type==="CERVEL_STATUS")status().then(respond).catch(error=>respond({ok:false,error:String(error?.message??error)}));else return false;return true;});
api.alarms?.create?.("cervel-retry",{periodInMinutes:1});api.alarms?.onAlarm?.addListener?.(alarm=>{if(alarm.name==="cervel-retry")void flush();});
