import{impactedDeliverables,renderDeliverable,validateDeliverable,type BrandProfile,type DeliverableObject,type SemanticTemplate}from"../../packages/deliverables/src";
const template:SemanticTemplate={id:"template",name:"Brief",format:"markdown",sections:[{id:"summary",title:"Executive Summary",required:true,accepted_kinds:["summary"]},{id:"evidence",title:"Evidence",required:true,accepted_kinds:["evidence"]}]};
const profile:BrandProfile={name:"CERVEL",primary_color:"#121826",secondary_color:"#64748b",font_family:"Inter",terminology:{vault:"Vault",cervel:"CERVEL"},prohibited_terms:["black box"],footer:"Sovereign Knowledge Infrastructure"};
const base:DeliverableObject={schema_version:"1.0",id:"d1",title:"CERVEL Brief",format:"markdown",template_id:"template",approval:"draft",version:1,blocks:[{id:"b1",kind:"summary",title:"Summary",content:"The cervel vault preserves knowledge.",version:1,cko_ids:["cko1"],claim_ids:["claim1"],approved:true},{id:"b2",kind:"evidence",content:"Every assertion retains provenance.",version:1,cko_ids:["cko2"],claim_ids:[],approved:true}],dependencies:[{resource_type:"cko",resource_id:"cko1",version:2}],created_at:"2026-08-21T00:00:00Z"};
describe("CERVEL Deliverables Engine",()=>{
 test.each([["markdown","md","text/markdown"],["html","html","text/html"],["docx","docx","application/vnd.openxmlformats-officedocument.wordprocessingml.document"],["pdf","pdf","application/pdf"],["presentation","pptx","application/vnd.openxmlformats-officedocument.presentationml.presentation"]]as const)("renders %s",(format,extension,mime)=>{const r=renderDeliverable({...base,format},profile);expect(r.extension).toBe(extension);expect(r.mime_type).toBe(mime);expect(r.bytes.length).toBeGreaterThan(100);expect(r.sha256).toHaveLength(64);});
 test("applies canonical terminology and brand profile",()=>{const md=renderDeliverable(base,profile).bytes.toString();expect(md).toContain("CERVEL Vault");expect(md).toContain(profile.footer!);});
 test("checks required sections, approval, prohibited terms, and version conflicts",()=>{const broken={...base,blocks:[{...base.blocks[0],approved:false,content:"A black box"},{...base.blocks[0],version:2}]};expect(validateDeliverable(broken,template,profile).map(x=>x.code)).toEqual(expect.arrayContaining(["REQUIRED_SECTION_MISSING","UNAPPROVED_BLOCK","PROHIBITED_TERM","BLOCK_VERSION_CONFLICT"]));});
 test("computes deterministic update propagation",()=>expect(impactedDeliverables("b1",[{deliverable_id:"d2",resource_id:"b1"},{deliverable_id:"d1",resource_id:"b1"},{deliverable_id:"d1",resource_id:"b1"}])).toEqual(["d1","d2"]));
});
