import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { BUILTIN_CORPORA, BUILTIN_CORPUS_KEYS, CORPUS_ENGINE_VERSION, classifyForCorpora, corpusRegistryDigest, validateCorpusDefinition } from "../../packages/corpus-engine/src";

describe("CERVEL Corpus Engine v1",()=>{
 test("registers the nine CCA corpora with three-level semantic taxonomies",()=>{expect(CORPUS_ENGINE_VERSION).toBe("1.0");expect(BUILTIN_CORPUS_KEYS).toEqual(["life","enterprise","knowledge","world","civilization","machine","ai","experience","resource"]);for(const corpus of BUILTIN_CORPORA){expect(validateCorpusDefinition(corpus)).toBe(corpus);expect(corpus.taxonomy[0].tabs.length).toBeGreaterThan(0);expect(corpus.taxonomy[0].tabs[0]).toHaveProperty("subtabs");}});
 test("classifies one canonical object into multiple corpora",()=>{const result=classifyForCorpora({type:"note",title:"CERVEL business plan",summary:"AI model strategy, customer revenue, research evidence",topics:["business","ai"],verticals:["software"],intents:["research"]});expect(result.map(x=>x.corpus_key)).toEqual(expect.arrayContaining(["enterprise","knowledge","ai"]));expect(new Set(result.map(x=>x.corpus_key)).size).toBe(result.length);});
 test("derives semantic channels from canonical title and summary when labels are absent",()=>{const result=classifyForCorpora({type:"note",title:"CERVEL AI business plan",summary:"Research evidence for AI model strategy, customer operations, and revenue."});expect(result.map(x=>x.corpus_key)).toEqual(expect.arrayContaining(["enterprise","knowledge","ai"]));});
 test("supports deterministic registries and custom extensions",()=>{expect(corpusRegistryDigest()).toMatch(/^[0-9a-f]{64}$/);expect(corpusRegistryDigest()).toBe(corpusRegistryDigest(BUILTIN_CORPORA));expect(validateCorpusDefinition({key:"melanin-mind",title:"Melanin Mind",description:"A custom cultural knowledge view.",visibility:"restricted",extension_of:"knowledge",taxonomy:[{key:"culture",title:"Culture",tabs:[{key:"history",title:"History",subtabs:["people"]}]}],rules:[]})).toMatchObject({key:"melanin-mind",extension_of:"knowledge"});});
 test("migration stores semantic references rather than duplicated files or content",()=>{const sql=readFileSync(resolve("db/migrations/032_corpus_engine.sql"),"utf8"),membership=sql.slice(sql.indexOf("CREATE TABLE corpus_memberships"),sql.indexOf("CREATE TABLE corpus_classification_hooks"));expect(membership).toContain("cko_id uuid");expect(membership).not.toMatch(/artifact_id|content\s+text|payload\s+jsonb/);expect(sql).toContain("CREATE VIEW corpus_cko_semantic_view");expect(sql).toContain("JOIN knowledge_objects ko");expect(sql).toContain("Semantic coordinates only");});
 test("ships a strict corpus contract",()=>{const schema=JSON.parse(readFileSync(resolve("packages/contracts/v1.0/corpus-definition.schema.json"),"utf8"));expect(schema.additionalProperties).toBe(false);expect(schema.properties.visibility.enum).toEqual(["public","node","restricted","private"]);});
});
