export type TaskClass="retrieval"|"summarization"|"analysis"|"coding"|"multimodal"|"long_context";
export type Sensitivity="public"|"internal"|"confidential"|"restricted";
export type Capability=TaskClass|"tools"|"json";
export type ProviderKind="local"|"cloud"|"enterprise";
export type ProviderProfile={id:string;kind:ProviderKind;capabilities:Capability[];quality:number;latency_ms:number;input_cost_per_million:number;output_cost_per_million:number;context_window:number;healthy:boolean;enabled:boolean;locality?:"device"|"private_network"|"public_cloud"};
export type GatewayPolicy={offline_only:boolean;network_allowed:boolean;monthly_budget_usd:number;spent_usd:number;max_request_usd:number;allow_confidential_external:boolean;allow_restricted_external:boolean;quality_floor:number};
export type RouteRequest={query:string;evidence_count:number;estimated_input_tokens:number;estimated_output_tokens?:number;has_images?:boolean;force_generation?:boolean;sensitivity_hint?:Sensitivity;policy:GatewayPolicy};
export type RouteCandidate={provider:ProviderProfile;estimated_cost_usd:number;score:number;reasons:string[]};
export type RoutePlan={task:TaskClass;sensitivity:Sensitivity;mode:"retrieval_without_generation"|"generation";selected:RouteCandidate;fallbacks:RouteCandidate[];disclosure:{external:boolean;classification:Sensitivity;fragment_count:number;estimated_tokens:number};reasons:string[]};

const sensitive={restricted:[/password/i,/secret key/i,/private key/i,/social security/i,/medical record/i,/attorney.client/i,/do not disclose/i],confidential:[/confidential/i,/payroll/i,/financial statement/i,/personnel/i,/customer data/i,/unpublished/i],internal:[/internal/i,/vault/i,/workspace/i,/project/i]};
export function classifySensitivity(query:string):Sensitivity{if(sensitive.restricted.some(x=>x.test(query)))return"restricted";if(sensitive.confidential.some(x=>x.test(query)))return"confidential";if(sensitive.internal.some(x=>x.test(query)))return"internal";return"public";}
export function classifyTask(input:Pick<RouteRequest,"query"|"has_images"|"evidence_count"|"force_generation">):TaskClass{const q=input.query.toLowerCase();if(input.has_images||/image|photo|scan|diagram/.test(q))return"multimodal";if(/code|debug|typescript|python|sql|api|function/.test(q))return"coding";if(/summari[sz]e|brief|condense|key points/.test(q))return"summarization";if(/compare|analy[sz]e|strategy|evaluate|reason|recommend/.test(q))return"analysis";if(input.evidence_count>24||/entire|all (the )?(files|documents)|long context/.test(q))return"long_context";return"retrieval";}
export function estimateCost(p:ProviderProfile,input:number,output=600){return Number(((input*p.input_cost_per_million+output*p.output_cost_per_million)/1_000_000).toFixed(6));}
function eligible(p:ProviderProfile,task:TaskClass,s:Sensitivity,policy:GatewayPolicy,cost:number,input:number){if(!p.enabled||!p.healthy||!p.capabilities.includes(task)||p.context_window<input)return false;if(p.quality<policy.quality_floor||cost>policy.max_request_usd||policy.spent_usd+cost>policy.monthly_budget_usd)return false;if(p.kind!=="local"&&(policy.offline_only||!policy.network_allowed))return false;if(p.kind!=="local"&&s==="restricted"&&!policy.allow_restricted_external)return false;if(p.kind!=="local"&&s==="confidential"&&!policy.allow_confidential_external)return false;return true;}
export function planRoute(req:RouteRequest,providers:ProviderProfile[]):RoutePlan{const task=classifyTask(req),rank:Record<Sensitivity,number>={public:0,internal:1,confidential:2,restricted:3},detected=classifySensitivity(req.query),sensitivity=req.sensitivity_hint&&rank[req.sensitivity_hint]>rank[detected]?req.sensitivity_hint:detected,mode=task==="retrieval"&&req.evidence_count>0&&!req.force_generation?"retrieval_without_generation":"generation",output=req.estimated_output_tokens??600,taskFloor=req.policy.offline_only||mode==="retrieval_without_generation"?.55:["analysis","coding","multimodal","long_context"].includes(task)?.80:.68,policy={...req.policy,quality_floor:Math.max(req.policy.quality_floor,taskFloor)},candidates=providers.map(provider=>{const cost=estimateCost(provider,req.estimated_input_tokens,output),local=provider.kind==="local",score=provider.quality*60-Math.log10(Math.max(10,provider.latency_ms))*6-cost*25+(local?10:0);return{provider,estimated_cost_usd:cost,score,reasons:[local?"device-local":"external",`quality:${provider.quality}`,`latency:${provider.latency_ms}ms`,`cost:$${cost}`]};}).filter(x=>eligible(x.provider,task,sensitivity,policy,x.estimated_cost_usd,req.estimated_input_tokens)).sort((a,b)=>b.score-a.score||a.provider.id.localeCompare(b.provider.id));if(!candidates.length)throw new Error("INTELLIGENCE_ROUTE_UNAVAILABLE");const selected=mode==="retrieval_without_generation"?(candidates.find(x=>x.provider.kind==="local")??candidates[0]):candidates[0];return{task,sensitivity,mode,selected,fallbacks:candidates.filter(x=>x!==selected),disclosure:{external:selected.provider.kind!=="local",classification:sensitivity,fragment_count:req.evidence_count,estimated_tokens:req.estimated_input_tokens},reasons:[`classified:${task}`,`sensitivity:${sensitivity}`,`quality_floor:${policy.quality_floor}`,mode,`selected:${selected.provider.id}`]};}

export const DEFAULT_CAPABILITY_REGISTRY:ProviderProfile[]=[
 {id:"local:deterministic",kind:"local",capabilities:["retrieval","summarization","analysis","long_context","json"],quality:.62,latency_ms:10,input_cost_per_million:0,output_cost_per_million:0,context_window:1_000_000,healthy:true,enabled:true,locality:"device"},
 {id:"local:ollama",kind:"local",capabilities:["retrieval","summarization","analysis","coding","multimodal","long_context","json"],quality:.74,latency_ms:900,input_cost_per_million:0,output_cost_per_million:0,context_window:128_000,healthy:true,enabled:false,locality:"device"},
 {id:"openai",kind:"cloud",capabilities:["summarization","analysis","coding","multimodal","long_context","tools","json"],quality:.92,latency_ms:1500,input_cost_per_million:1.25,output_cost_per_million:10,context_window:400_000,healthy:true,enabled:false,locality:"public_cloud"},
 {id:"anthropic",kind:"cloud",capabilities:["summarization","analysis","coding","multimodal","long_context","tools","json"],quality:.93,latency_ms:1700,input_cost_per_million:3,output_cost_per_million:15,context_window:200_000,healthy:true,enabled:false,locality:"public_cloud"},
 {id:"google",kind:"cloud",capabilities:["summarization","analysis","coding","multimodal","long_context","tools","json"],quality:.90,latency_ms:1200,input_cost_per_million:.30,output_cost_per_million:2.50,context_window:1_000_000,healthy:true,enabled:false,locality:"public_cloud"},
 {id:"openrouter",kind:"cloud",capabilities:["summarization","analysis","coding","multimodal","long_context","tools","json"],quality:.88,latency_ms:1800,input_cost_per_million:1,output_cost_per_million:4,context_window:200_000,healthy:true,enabled:false,locality:"public_cloud"},
 {id:"enterprise",kind:"enterprise",capabilities:["retrieval","summarization","analysis","coding","multimodal","long_context","tools","json"],quality:.87,latency_ms:700,input_cost_per_million:0,output_cost_per_million:0,context_window:200_000,healthy:true,enabled:false,locality:"private_network"}
];
