import{createHash}from"node:crypto";
import{renderPresentation}from"./presentation";
export type DeliverableFormat="markdown"|"html"|"docx"|"pdf"|"presentation";
export type ApprovalState="draft"|"in_review"|"approved"|"rejected"|"superseded";
export type CanonicalBlock={id:string;kind:string;title?:string;content:string;version:number;cko_ids:string[];claim_ids:string[];approved:boolean};
export type SemanticTemplate={id:string;name:string;format:DeliverableFormat;sections:{id:string;title:string;required:boolean;accepted_kinds:string[]}[]};
export type BrandProfile={name:string;organization?:string;primary_color:string;secondary_color:string;font_family:string;terminology:Record<string,string>;prohibited_terms:string[];footer?:string};
export type DeliverableObject={schema_version:"1.0";id:string;title:string;format:DeliverableFormat;template_id:string;brand_profile_id?:string|null;approval:ApprovalState;version:number;blocks:CanonicalBlock[];dependencies:{resource_type:string;resource_id:string;version?:number}[];created_at:string};
export type ConsistencyIssue={code:string;severity:"error"|"warning";message:string;block_id?:string};
const esc=(s:string)=>s.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");
export const digest=(x:unknown)=>createHash("sha256").update(JSON.stringify(x)).digest("hex");
export function applyTerminology(text:string,profile:BrandProfile){let out=text;for(const[from,to]of Object.entries(profile.terminology))out=out.replace(new RegExp(`\\b${from.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")}\\b`,"gi"),to);return out;}
export function validateDeliverable(d:DeliverableObject,t:SemanticTemplate,p?:BrandProfile):ConsistencyIssue[]{const issues:ConsistencyIssue[]=[];for(const s of t.sections)if(s.required&&!d.blocks.some(b=>s.accepted_kinds.includes(b.kind)))issues.push({code:"REQUIRED_SECTION_MISSING",severity:"error",message:`Required section ${s.title} is missing`});const seen=new Map<string,CanonicalBlock>();for(const b of d.blocks){if(!b.approved)issues.push({code:"UNAPPROVED_BLOCK",severity:"warning",message:"Block is not approved",block_id:b.id});const prior=seen.get(b.id);if(prior&&prior.version!==b.version)issues.push({code:"BLOCK_VERSION_CONFLICT",severity:"error",message:"Two versions of one canonical block are present",block_id:b.id});seen.set(b.id,b);if(p)for(const term of p.prohibited_terms)if(new RegExp(`\\b${term}\\b`,"i").test(b.content))issues.push({code:"PROHIBITED_TERM",severity:"error",message:`Prohibited term: ${term}`,block_id:b.id});}return issues;}
function markdown(d:DeliverableObject,p?:BrandProfile){return[`# ${d.title}`,...d.blocks.flatMap(b=>[`## ${b.title??b.kind}`,p?applyTerminology(b.content,p):b.content]),p?.footer?`---\n${p.footer}`:""].filter(Boolean).join("\n\n");}
function html(d:DeliverableObject,p?:BrandProfile){const color=p?.primary_color??"#111827",font=p?.font_family??"system-ui";return`<!doctype html><html><head><meta charset="utf-8"><title>${esc(d.title)}</title><style>body{font-family:${esc(font)};max-width:800px;margin:48px auto;color:#111}h1,h2{color:${esc(color)}}footer{margin-top:48px}</style></head><body><h1>${esc(d.title)}</h1>${d.blocks.map(b=>`<section data-block-id="${esc(b.id)}" data-version="${b.version}"><h2>${esc(b.title??b.kind)}</h2><p>${esc(p?applyTerminology(b.content,p):b.content).replace(/\n/g,"<br>")}</p></section>`).join("")}${p?.footer?`<footer>${esc(p.footer)}</footer>`:""}</body></html>`;}
const crcTable=(()=>Array.from({length:256},(_,n)=>{let c=n;for(let k=0;k<8;k++)c=(c&1)?0xedb88320^(c>>>1):c>>>1;return c>>>0;}))();
const crc32=(b:Buffer)=>{let c=0xffffffff;for(const x of b)c=crcTable[(c^x)&255]^(c>>>8);return(c^0xffffffff)>>>0;};
function zip(files:Record<string,string>):Buffer{const local:Buffer[]=[],central:Buffer[]=[];let offset=0;for(const[name,value]of Object.entries(files)){const n=Buffer.from(name),b=Buffer.from(value),crc=crc32(b),h=Buffer.alloc(30);h.writeUInt32LE(0x04034b50);h.writeUInt16LE(20,4);h.writeUInt32LE(crc,14);h.writeUInt32LE(b.length,18);h.writeUInt32LE(b.length,22);h.writeUInt16LE(n.length,26);local.push(h,n,b);const c=Buffer.alloc(46);c.writeUInt32LE(0x02014b50);c.writeUInt16LE(20,4);c.writeUInt16LE(20,6);c.writeUInt32LE(crc,16);c.writeUInt32LE(b.length,20);c.writeUInt32LE(b.length,24);c.writeUInt16LE(n.length,28);c.writeUInt32LE(offset,42);central.push(c,n);offset+=h.length+n.length+b.length;}const cs=Buffer.concat(central),end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50);end.writeUInt16LE(Object.keys(files).length,8);end.writeUInt16LE(Object.keys(files).length,10);end.writeUInt32LE(cs.length,12);end.writeUInt32LE(offset,16);return Buffer.concat([...local,cs,end]);}
function docx(d:DeliverableObject,p?:BrandProfile){const paragraphs=[d.title,...d.blocks.flatMap(b=>[b.title??b.kind,p?applyTerminology(b.content,p):b.content])].map(x=>`<w:p><w:r><w:t xml:space="preserve">${esc(x)}</w:t></w:r></w:p>`).join("");return zip({"[Content_Types].xml":`<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/></Types>`,"_rels/.rels":`<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>`,"word/document.xml":`<?xml version="1.0"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>${paragraphs}</w:body></w:document>`});}
function pdf(d:DeliverableObject,p?:BrandProfile){const lines=[d.title,...d.blocks.flatMap(b=>[b.title??b.kind,p?applyTerminology(b.content,p):b.content])].flatMap(x=>x.split("\n")).map(x=>x.replace(/[()\\]/g,"\\$&").slice(0,110));const stream=`BT /F1 12 Tf 50 790 Td ${lines.map((x,i)=>`${i?"0 -18 Td ":""}(${x}) Tj`).join(" ")} ET`,objs=["<< /Type /Catalog /Pages 2 0 R >>","<< /Type /Pages /Kids [3 0 R] /Count 1 >>","<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 842] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>",`<< /Length ${Buffer.byteLength(stream)} >>\nstream\n${stream}\nendstream`,"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>"];let out="%PDF-1.4\n",offsets=[0];objs.forEach((o,i)=>{offsets.push(Buffer.byteLength(out));out+=`${i+1} 0 obj\n${o}\nendobj\n`;});const start=Buffer.byteLength(out);out+=`xref\n0 ${objs.length+1}\n0000000000 65535 f \n${offsets.slice(1).map(x=>String(x).padStart(10,"0")+" 00000 n ").join("\n")}\ntrailer << /Size ${objs.length+1} /Root 1 0 R >>\nstartxref\n${start}\n%%EOF`;return Buffer.from(out);}
function presentation(d:DeliverableObject,p?:BrandProfile){const slides=d.blocks.map((b,i)=>[`ppt/slides/slide${i+1}.xml`,`<?xml version="1.0"?><p:sld xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main"><p:cSld><p:spTree><p:nvGrpSpPr/><p:grpSpPr/><p:sp><p:nvSpPr/><p:spPr/><p:txBody><a:bodyPr/><a:lstStyle/><a:p><a:r><a:t>${esc(b.title??b.kind)}</a:t></a:r></a:p><a:p><a:r><a:t>${esc(p?applyTerminology(b.content,p):b.content)}</a:t></a:r></a:p></p:txBody></p:sp></p:spTree></p:cSld></p:sld>`]as const);return zip(Object.fromEntries([["[Content_Types].xml",`<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>${slides.map((_,i)=>`<Override PartName="/ppt/slides/slide${i+1}.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slide+xml"/>`).join("")}<Override PartName="/ppt/presentation.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.presentation.main+xml"/></Types>`],["_rels/.rels",`<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="ppt/presentation.xml"/></Relationships>`],["ppt/presentation.xml",`<?xml version="1.0"?><p:presentation xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main"/>`],...slides]));}
export function renderDeliverable(d:DeliverableObject,p?:BrandProfile):{bytes:Buffer;mime_type:string;extension:string;sha256:string}{let bytes:Buffer,mime_type:string,extension:string;if(d.format==="markdown"){bytes=Buffer.from(markdown(d,p));mime_type="text/markdown";extension="md";}else if(d.format==="html"){bytes=Buffer.from(html(d,p));mime_type="text/html";extension="html";}else if(d.format==="docx"){bytes=docx(d,p);mime_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document";extension="docx";}else if(d.format==="pdf"){bytes=pdf(d,p);mime_type="application/pdf";extension="pdf";}else{bytes=renderPresentation(d.blocks.map(b=>({title:b.title??b.kind,content:p?applyTerminology(b.content,p):b.content})));mime_type="application/vnd.openxmlformats-officedocument.presentationml.presentation";extension="pptx";}return{bytes,mime_type,extension,sha256:createHash("sha256").update(bytes).digest("hex")};}
export function impactedDeliverables(changed:string,deps:{deliverable_id:string;resource_id:string}[]){return[...new Set(deps.filter(x=>x.resource_id===changed).map(x=>x.deliverable_id))].sort();}
