import { createCipheriv,createDecipheriv,createHash,createHmac,diffieHellman,generateKeyPairSync,hkdfSync,randomBytes,sign,verify,createPrivateKey,createPublicKey } from "node:crypto";
import { SYNC_PROTOCOL,type DeviceRegistration,type EncryptedChunk,type EncryptedEnvelope,type EnrollmentBundle,type SignedRequest,type VersionVector } from "./protocol";

const b64=(value:Buffer)=>value.toString("base64url"),unb64=(value:string)=>Buffer.from(value,"base64url");
export const sha256=(value:Buffer|string)=>createHash("sha256").update(value).digest("hex");
export const randomId=(bytes=24)=>b64(randomBytes(bytes));
export function opaqueId(rootKey:Buffer,scope:string,value:string):string{return createHmac("sha256",rootKey).update(scope).update("\0").update(value).digest("base64url");}
function aesEncrypt(key:Buffer,plain:Buffer,aad:Buffer){const nonce=randomBytes(12),cipher=createCipheriv("aes-256-gcm",key,nonce);cipher.setAAD(aad);const ciphertext=Buffer.concat([cipher.update(plain),cipher.final()]);return {nonce:b64(nonce),ciphertext:b64(ciphertext),tag:b64(cipher.getAuthTag())};}
function aesDecrypt(key:Buffer,input:{nonce:string;ciphertext:string;tag:string},aad:Buffer){const decipher=createDecipheriv("aes-256-gcm",key,unb64(input.nonce));decipher.setAAD(aad);decipher.setAuthTag(unb64(input.tag));return Buffer.concat([decipher.update(unb64(input.ciphertext)),decipher.final()]);}
const recordAad=(input:{vault_id:string;device_id:string;entity_id:string;counter:number;vector:VersionVector})=>Buffer.from(JSON.stringify([SYNC_PROTOCOL,input.vault_id,input.device_id,input.entity_id,input.counter,Object.entries(input.vector).sort()]));

export function encryptRecord(rootKey:Buffer,input:{vault_id:string;device_id:string;entity_id:string;counter:number;vector:VersionVector;payload:unknown}):EncryptedEnvelope{const header={vault_id:input.vault_id,device_id:input.device_id,entity_id:input.entity_id,counter:input.counter,vector:input.vector},record_id=createHmac("sha256",rootKey).update(`${input.device_id}:${input.counter}:${input.entity_id}`).digest("base64url"),encrypted=aesEncrypt(rootKey,Buffer.from(JSON.stringify(input.payload)),recordAad(header));return {protocol:SYNC_PROTOCOL,record_id,...header,...encrypted,created_at:new Date().toISOString()};}
export function decryptRecord<T>(rootKey:Buffer,envelope:EncryptedEnvelope):T{return JSON.parse(aesDecrypt(rootKey,envelope,recordAad(envelope)).toString("utf8"));}
export function chunkId(rootKey:Buffer,plain:Buffer):string{return createHmac("sha256",rootKey).update("chunk\0").update(plain).digest("base64url");}
export function encryptChunk(rootKey:Buffer,plain:Buffer):EncryptedChunk{const id=chunkId(rootKey,plain),key=Buffer.from(hkdfSync("sha256",rootKey,Buffer.from(id),Buffer.from("cervel-sync-chunk"),32)),encrypted=aesEncrypt(key,plain,Buffer.from(`${SYNC_PROTOCOL}:${id}`));return {chunk_id:id,...encrypted,size:plain.length};}
export function decryptChunk(rootKey:Buffer,chunk:EncryptedChunk):Buffer{const key=Buffer.from(hkdfSync("sha256",rootKey,Buffer.from(chunk.chunk_id),Buffer.from("cervel-sync-chunk"),32)),plain=aesDecrypt(key,chunk,Buffer.from(`${SYNC_PROTOCOL}:${chunk.chunk_id}`));if(chunkId(rootKey,plain)!==chunk.chunk_id)throw new Error("SYNC_CHUNK_INTEGRITY_FAILURE");return plain;}
export function splitEncryptedChunks(rootKey:Buffer,bytes:Buffer,chunkSize=4*1024*1024):EncryptedChunk[]{if(chunkSize<64*1024||chunkSize>16*1024*1024)throw new Error("SYNC_CHUNK_SIZE_INVALID");const chunks=[];for(let offset=0;offset<bytes.length;offset+=chunkSize)chunks.push(encryptChunk(rootKey,bytes.subarray(offset,Math.min(offset+chunkSize,bytes.length))));return chunks;}

export function generateDeviceIdentity(label="CERVEL Device"):{registration:DeviceRegistration;signing_private_key:string;encryption_private_key:string}{const signing=generateKeyPairSync("ed25519"),encryption=generateKeyPairSync("x25519"),device_id=randomId(18);return {registration:{device_id,signing_public_key:signing.publicKey.export({type:"spki",format:"pem"}).toString(),encryption_public_key:encryption.publicKey.export({type:"spki",format:"pem"}).toString(),enrolled_at:new Date().toISOString()},signing_private_key:signing.privateKey.export({type:"pkcs8",format:"pem"}).toString(),encryption_private_key:encryption.privateKey.export({type:"pkcs8",format:"pem"}).toString()};}
export function requestDigest(method:string,path:string,timestamp:string,nonce:string,body:unknown):Buffer{return Buffer.from([method.toUpperCase(),path,timestamp,nonce,sha256(Buffer.from(JSON.stringify(body??null)))].join("\n"));}
export function signRequest(deviceId:string,privateKey:string,method:string,path:string,body:unknown,timestamp=new Date().toISOString(),nonce=randomId(16)):SignedRequest{const digest=requestDigest(method,path,timestamp,nonce,body);return {device_id:deviceId,timestamp,nonce,body_sha256:sha256(Buffer.from(JSON.stringify(body??null))),signature:b64(sign(null,digest,createPrivateKey(privateKey)))};}
export function verifyRequest(publicKey:string,proof:SignedRequest,method:string,path:string,body:unknown,now=Date.now()):boolean{if(Math.abs(now-Date.parse(proof.timestamp))>5*60_000)return false;const expected=sha256(Buffer.from(JSON.stringify(body??null)));if(expected!==proof.body_sha256)return false;return verify(null,requestDigest(method,path,proof.timestamp,proof.nonce,body),createPublicKey(publicKey),unb64(proof.signature));}
export function createEnrollmentBundle(rootKey:Buffer,vaultId:string,recipient:DeviceRegistration,ttlMs=10*60_000):EnrollmentBundle{const ephemeral=generateKeyPairSync("x25519"),shared=diffieHellman({privateKey:ephemeral.privateKey,publicKey:createPublicKey(recipient.encryption_public_key)}),key=Buffer.from(hkdfSync("sha256",shared,Buffer.from(vaultId),Buffer.from("cervel-device-enrollment"),32)),issued=new Date(),expires=new Date(issued.getTime()+ttlMs),aad=Buffer.from(`${SYNC_PROTOCOL}:${vaultId}:${recipient.device_id}:${expires.toISOString()}`),encrypted=aesEncrypt(key,rootKey,aad);return {protocol:SYNC_PROTOCOL,vault_id:vaultId,device_id:recipient.device_id,ephemeral_public_key:ephemeral.publicKey.export({type:"spki",format:"pem"}).toString(),...encrypted,issued_at:issued.toISOString(),expires_at:expires.toISOString()};}
export function openEnrollmentBundle(bundle:EnrollmentBundle,recipientPrivateKey:string,now=Date.now()):Buffer{if(Date.parse(bundle.expires_at)<now)throw new Error("ENROLLMENT_EXPIRED");const shared=diffieHellman({privateKey:createPrivateKey(recipientPrivateKey),publicKey:createPublicKey(bundle.ephemeral_public_key)}),key=Buffer.from(hkdfSync("sha256",shared,Buffer.from(bundle.vault_id),Buffer.from("cervel-device-enrollment"),32)),aad=Buffer.from(`${SYNC_PROTOCOL}:${bundle.vault_id}:${bundle.device_id}:${bundle.expires_at}`);return aesDecrypt(key,bundle,aad);}
