import {createCipheriv,createDecipheriv,createHash,diffieHellman,generateKeyPairSync,hkdfSync,randomBytes,createPrivateKey,createPublicKey} from "node:crypto";
import {createDeviceId,createEmbodimentId,type CervelEmbodimentKind,type EmbodimentCapability,type EmbodimentPermission} from "../../embodiment/src/index";
import {DEVICE_ENROLLMENT_PROTOCOL,canonicalGrant,type DeviceIdentityV2,type EncryptedEnrollmentBundleV2,type EnrollmentChallengeV2,type EnrollmentGrantV2,validateDeviceIdentityV2} from "./device-enrollment";
const b64=(v:Buffer)=>v.toString("base64url"),unb64=(v:string)=>Buffer.from(v,"base64url");
const fingerprint=(...keys:string[])=>createHash("sha256").update(keys.join("\n")).digest("hex");
const enrollmentId=()=>`enr_${b64(randomBytes(24))}`;
export const enrollmentGrantDigest=(grant:EnrollmentGrantV2)=>createHash("sha256").update(canonicalGrant(grant)).digest("hex");
export type DeviceKeyMaterialV2={identity:DeviceIdentityV2;signing_private_key:string;encryption_private_key:string};
export function generateEmbodimentDeviceV2(input:{kind:CervelEmbodimentKind;display_name:string;platform?:string;app_version?:string;capabilities:EmbodimentCapability[];requested_permissions:EmbodimentPermission[];seed?:string}):DeviceKeyMaterialV2{const signing=generateKeyPairSync("ed25519"),encryption=generateKeyPairSync("x25519"),signingPublic=signing.publicKey.export({type:"spki",format:"pem"}).toString(),encryptionPublic=encryption.publicKey.export({type:"spki",format:"pem"}).toString();const identity:DeviceIdentityV2={protocol:DEVICE_ENROLLMENT_PROTOCOL,device_id:createDeviceId(input.seed?`${input.seed}:device`:undefined),embodiment_id:createEmbodimentId(input.seed?`${input.seed}:embodiment`:undefined),kind:input.kind,display_name:input.display_name,platform:input.platform,app_version:input.app_version,signing_public_key:signingPublic,encryption_public_key:encryptionPublic,key_fingerprint:fingerprint(signingPublic,encryptionPublic),capabilities:[...new Set(input.capabilities)],requested_permissions:input.requested_permissions,created_at:new Date().toISOString()};validateDeviceIdentityV2(identity);return {identity,signing_private_key:signing.privateKey.export({type:"pkcs8",format:"pem"}).toString(),encryption_private_key:encryption.privateKey.export({type:"pkcs8",format:"pem"}).toString()};}
export function createEnrollmentChallengeV2(vaultId:string,nodeId:string,device:DeviceIdentityV2,ttlMs=5*60_000):EnrollmentChallengeV2{if(ttlMs<30_000||ttlMs>15*60_000)throw new Error("ENROLLMENT_TTL_INVALID");const issued=new Date();return {protocol:DEVICE_ENROLLMENT_PROTOCOL,request_id:enrollmentId(),vault_id:vaultId,node_id:nodeId,device:validateDeviceIdentityV2(device),pairing_nonce:b64(randomBytes(32)),issued_at:issued.toISOString(),expires_at:new Date(issued.getTime()+ttlMs).toISOString()};}
function encrypt(key:Buffer,plain:Buffer,aad:Buffer){const nonce=randomBytes(12),cipher=createCipheriv("aes-256-gcm",key,nonce);cipher.setAAD(aad);const ciphertext=Buffer.concat([cipher.update(plain),cipher.final()]);return {nonce:b64(nonce),ciphertext:b64(ciphertext),tag:b64(cipher.getAuthTag())};}
function decrypt(key:Buffer,input:{nonce:string;ciphertext:string;tag:string},aad:Buffer){const decipher=createDecipheriv("aes-256-gcm",key,unb64(input.nonce));decipher.setAAD(aad);decipher.setAuthTag(unb64(input.tag));return Buffer.concat([decipher.update(unb64(input.ciphertext)),decipher.final()]);}
export function sealSyncRootForDeviceV2(rootKey:Buffer,input:{vault_id:string;device:DeviceIdentityV2;sync_epoch:number;grant:EnrollmentGrantV2;ttlMs?:number}):EncryptedEnrollmentBundleV2{if(rootKey.length!==32)throw new Error("SYNC_ROOT_KEY_INVALID");const ttl=input.ttlMs??10*60_000;if(ttl<30_000||ttl>15*60_000)throw new Error("ENROLLMENT_BUNDLE_TTL_INVALID");const grant_sha256=enrollmentGrantDigest(input.grant),ephemeral=generateKeyPairSync("x25519"),shared=diffieHellman({privateKey:ephemeral.privateKey,publicKey:createPublicKey(input.device.encryption_public_key)}),key=Buffer.from(hkdfSync("sha256",shared,Buffer.from(input.vault_id),Buffer.from(`${DEVICE_ENROLLMENT_PROTOCOL}:${input.device.device_id}:${input.sync_epoch}`),32)),issued=new Date(),expires=new Date(issued.getTime()+ttl),aad=Buffer.from([DEVICE_ENROLLMENT_PROTOCOL,input.vault_id,input.device.device_id,input.device.embodiment_id,input.sync_epoch,grant_sha256,expires.toISOString()].join(":")),sealed=encrypt(key,rootKey,aad);return {protocol:DEVICE_ENROLLMENT_PROTOCOL,vault_id:input.vault_id,device_id:input.device.device_id,embodiment_id:input.device.embodiment_id,sync_epoch:input.sync_epoch,grant_sha256,ephemeral_public_key:ephemeral.publicKey.export({type:"spki",format:"pem"}).toString(),...sealed,issued_at:issued.toISOString(),expires_at:expires.toISOString()};}
export function openSyncRootForDeviceV2(bundle:EncryptedEnrollmentBundleV2,device:DeviceKeyMaterialV2,grant?:EnrollmentGrantV2,now=Date.now()){if(bundle.protocol!==DEVICE_ENROLLMENT_PROTOCOL||bundle.device_id!==device.identity.device_id||bundle.embodiment_id!==device.identity.embodiment_id)throw new Error("ENROLLMENT_BUNDLE_BINDING_FAILURE");if(grant&&enrollmentGrantDigest(grant)!==bundle.grant_sha256)throw new Error("ENROLLMENT_GRANT_DIGEST_MISMATCH");if(Date.parse(bundle.expires_at)<=now)throw new Error("ENROLLMENT_BUNDLE_EXPIRED");const shared=diffieHellman({privateKey:createPrivateKey(device.encryption_private_key),publicKey:createPublicKey(bundle.ephemeral_public_key)}),key=Buffer.from(hkdfSync("sha256",shared,Buffer.from(bundle.vault_id),Buffer.from(`${DEVICE_ENROLLMENT_PROTOCOL}:${bundle.device_id}:${bundle.sync_epoch}`),32)),aad=Buffer.from([DEVICE_ENROLLMENT_PROTOCOL,bundle.vault_id,bundle.device_id,bundle.embodiment_id,bundle.sync_epoch,bundle.grant_sha256,bundle.expires_at].join(":"));return decrypt(key,bundle,aad);}
