import { createHash,randomBytes } from "node:crypto";
import { decryptChunk,decryptRecord,encryptRecord,generateDeviceIdentity,opaqueId,randomId,signRequest,splitEncryptedChunks } from "./crypto";
import { compareVectors,deterministicWinner,mergeVectors,type DeviceRegistration,type EncryptedChunk,type EncryptedEnvelope,type SyncRelayTransport,type VersionVector } from "./protocol";

export type SyncMutation={kind:"put"|"delete"|"backup";entity_type:string;value?:unknown;chunk_ids?:string[];content_sha256?:string};
type Materialized={envelope:EncryptedEnvelope;payload:SyncMutation;conflicts:Array<{envelope:EncryptedEnvelope;payload:SyncMutation}>};
type EncryptedMutation={logical_id:string;mutation:SyncMutation};
export type SyncDevice={registration:DeviceRegistration;signing_private_key:string;encryption_private_key:string};
export type SyncPersistence={counter:number;cursor:number;paused:boolean;journal:EncryptedEnvelope[];sent:string[];records:EncryptedEnvelope[];chunks:EncryptedChunk[]};

export class CloudSyncEngine{
  private counter=0;private cursor=0;private paused=false;private journal:EncryptedEnvelope[]=[];private sent=new Set<string>();private applied=new Set<string>();private recordLog:EncryptedEnvelope[]=[];private materialized=new Map<string,Materialized>();private chunks=new Map<string,EncryptedChunk>();
  constructor(readonly vaultId:string,readonly rootKey:Buffer,readonly device:SyncDevice,private readonly relay:SyncRelayTransport,persisted?:SyncPersistence){if(persisted){this.counter=persisted.counter;this.cursor=persisted.cursor;this.paused=persisted.paused;this.journal=[...persisted.journal];this.sent=new Set(persisted.sent);for(const chunk of persisted.chunks)this.chunks.set(chunk.chunk_id,chunk);for(const envelope of persisted.records)this.apply(envelope);for(const envelope of persisted.journal)this.apply(envelope);}}
  static newVault(relay:SyncRelayTransport){return {vaultId:randomId(24),rootKey:randomBytes(32),device:generateDeviceIdentity(),relay};}
  private proof(method:string,path:string,body:unknown){return signRequest(this.device.registration.device_id,this.device.signing_private_key,method,path,body);}
  async register(){const path=`/v1/sync/vaults/${this.vaultId}`,body=this.device.registration;await this.relay.registerVault(this.vaultId,body,this.proof("POST",path,body));}
  async enrollDevice(registration:DeviceRegistration){const path=`/v1/sync/vaults/${this.vaultId}/devices`;await this.relay.enrollDevice(this.vaultId,registration,this.proof("POST",path,registration));}
  async revokeDevice(deviceId:string){const path=`/v1/sync/vaults/${this.vaultId}/devices/${deviceId}`,body={device_id:deviceId};await this.relay.revokeDevice(this.vaultId,deviceId,this.proof("DELETE",path,body));}
  mutate(entityId:string,payload:SyncMutation):EncryptedEnvelope{const current=this.materialized.get(entityId),vector={...(current?.envelope.vector??{})};this.counter=Math.max(this.counter,vector[this.device.registration.device_id]??0)+1;vector[this.device.registration.device_id]=this.counter;const envelope=encryptRecord(this.rootKey,{vault_id:this.vaultId,device_id:this.device.registration.device_id,entity_id:opaqueId(this.rootKey,"entity",entityId),counter:this.counter,vector,payload:{logical_id:entityId,mutation:payload}});this.journal.push(envelope);this.apply(envelope);return envelope;}
  put(entityId:string,entityType:string,value:unknown){return this.mutate(entityId,{kind:"put",entity_type:entityType,value});}
  delete(entityId:string,entityType:string){return this.mutate(entityId,{kind:"delete",entity_type:entityType});}
  attachArtifact(entityId:string,bytes:Buffer,entityType="artifact"){const chunks=splitEncryptedChunks(this.rootKey,bytes);for(const chunk of chunks)this.chunks.set(chunk.chunk_id,chunk);return this.mutate(entityId,{kind:"put",entity_type:entityType,chunk_ids:chunks.map(c=>c.chunk_id),content_sha256:createHash("sha256").update(bytes).digest("hex")});}
  private apply(envelope:EncryptedEnvelope){if(this.applied.has(envelope.record_id))return;const decrypted=decryptRecord<EncryptedMutation>(this.rootKey,envelope),entityId=decrypted.logical_id,payload=decrypted.mutation;if(opaqueId(this.rootKey,"entity",entityId)!==envelope.entity_id)throw new Error("SYNC_ENTITY_BINDING_FAILURE");this.applied.add(envelope.record_id);this.recordLog.push(envelope);const current=this.materialized.get(entityId);this.counter=Math.max(this.counter,envelope.vector[this.device.registration.device_id]??0);if(!current){this.materialized.set(entityId,{envelope,payload,conflicts:[]});return;}const order=compareVectors(envelope.vector,current.envelope.vector);if(order==="before"||order==="equal")return;if(order==="after"){this.materialized.set(entityId,{envelope,payload,conflicts:current.conflicts});return;}const winner=deterministicWinner(envelope,current.envelope);if(winner===envelope)this.materialized.set(entityId,{envelope,payload,conflicts:[...current.conflicts,{envelope:current.envelope,payload:current.payload}]});else current.conflicts.push({envelope,payload});}
  private async uploadChunks(){const ids=[...this.chunks.keys()],path=`/v1/sync/vaults/${this.vaultId}/chunks/missing`,body={ids},missing=await this.relay.missingChunks(this.vaultId,ids,this.proof("POST",path,body));for(const id of missing){const chunk=this.chunks.get(id)!,cipher=Buffer.from(chunk.ciphertext,"base64url"),meta={chunk_id:chunk.chunk_id,nonce:chunk.nonce,tag:chunk.tag,size:chunk.size};for(let offset=0;offset<cipher.length;offset+=512*1024){const part=cipher.subarray(offset,Math.min(offset+512*1024,cipher.length)),final=offset+part.length===cipher.length,partBody={meta,offset,ciphertext_part:part.toString("base64url"),final},partPath=`/v1/sync/vaults/${this.vaultId}/chunks/${id}`;await this.relay.putChunkPart(this.vaultId,meta,offset,partBody.ciphertext_part,final,this.proof("PUT",partPath,partBody));}}}
  async sync(){if(this.paused)return {paused:true,pushed:0,pulled:0,cursor:this.cursor};await this.uploadChunks();const pending=this.journal.filter(row=>!this.sent.has(row.record_id));if(pending.length){const path=`/v1/sync/vaults/${this.vaultId}/records`,body={envelopes:pending},result=await this.relay.push(this.vaultId,pending,this.proof("POST",path,body));for(const id of result.accepted)this.sent.add(id);}let pulled=0;for(;;){const path=`/v1/sync/vaults/${this.vaultId}/records`,body={after:this.cursor,limit:200},page=await this.relay.pull(this.vaultId,this.cursor,200,this.proof("GET",path,body));for(const row of page.records){this.apply(row.envelope);pulled++;}this.cursor=page.cursor;if(page.records.length<200)break;}return {paused:false,pushed:pending.length,pulled,cursor:this.cursor};}
  pause(value=true){this.paused=value;}isPaused(){return this.paused;}
  async reset(){const path=`/v1/sync/vaults/${this.vaultId}/reset`;await this.relay.resetDevice(this.vaultId,this.proof("POST",path,{}));this.cursor=0;this.sent.clear();this.applied.clear();this.recordLog=[];this.materialized.clear();}
  async deleteRemote(){const path=`/v1/sync/vaults/${this.vaultId}`;await this.relay.deleteVault(this.vaultId,this.proof("DELETE",path,{}));this.pause(true);}
  createRemoteBackup(){const snapshot=[...this.materialized.entries()].map(([entity_id,item])=>({entity_id,record_id:item.envelope.record_id,vector:item.envelope.vector}));return this.mutate(`backup:${randomId(12)}`,{kind:"backup",entity_type:"vault-manifest",value:{cursor:this.cursor,records:snapshot,created_at:new Date().toISOString()}});}
  async restoreArtifact(entityId:string){const item=this.materialized.get(entityId);if(!item?.payload.chunk_ids)throw new Error("SYNC_ARTIFACT_NOT_FOUND");const parts=[];for(const id of item.payload.chunk_ids){const path=`/v1/sync/vaults/${this.vaultId}/chunks/${id}`,body={chunk_id:id},chunk=await this.relay.getChunk(this.vaultId,id,this.proof("GET",path,body));parts.push(decryptChunk(this.rootKey,chunk));}const bytes=Buffer.concat(parts);if(createHash("sha256").update(bytes).digest("hex")!==item.payload.content_sha256)throw new Error("SYNC_ARTIFACT_HASH_MISMATCH");return bytes;}
  get(entityId:string){const item=this.materialized.get(entityId);return item?.payload.kind==="delete"?undefined:item?.payload.value;}
  state(){return {cursor:this.cursor,paused:this.paused,journal:this.journal.length,entities:[...this.materialized.entries()].map(([id,item])=>({id,kind:item.payload.kind,entity_type:item.payload.entity_type,record_id:item.envelope.record_id,vector:item.envelope.vector,conflicts:item.conflicts.map(c=>c.envelope.record_id)})).sort((a,b)=>a.id.localeCompare(b.id))};}
  persistence():SyncPersistence{return {counter:this.counter,cursor:this.cursor,paused:this.paused,journal:[...this.journal],sent:[...this.sent],records:[...this.recordLog],chunks:[...this.chunks.values()]};}
}
