import { verifyRequest } from "./crypto";
import { validateChunkMeta,validateEnvelope,type DeviceRegistration,type EncryptedChunk,type EncryptedEnvelope,type RelayRecord,type SignedRequest,type SyncRelayTransport } from "./protocol";

type StoredChunk={meta:Omit<EncryptedChunk,"ciphertext">;parts:Buffer[];received:number;complete:boolean};
type Vault={devices:Map<string,DeviceRegistration>;records:RelayRecord[];recordIds:Set<string>;chunks:Map<string,StoredChunk>;nonces:Set<string>;nextSequence:number};
export class InMemoryZeroKnowledgeRelay implements SyncRelayTransport{
  private vaults=new Map<string,Vault>();
  private authenticate(vaultId:string,proof:SignedRequest,method:string,path:string,body:unknown):Vault{const vault=this.vaults.get(vaultId);if(!vault)throw new Error("SYNC_VAULT_NOT_FOUND");const device=vault.devices.get(proof.device_id);if(!device||device.revoked_at)throw new Error("SYNC_DEVICE_REVOKED");if(vault.nonces.has(proof.nonce))throw new Error("SYNC_REPLAY_REJECTED");if(!verifyRequest(device.signing_public_key,proof,method,path,body))throw new Error("SYNC_SIGNATURE_INVALID");vault.nonces.add(proof.nonce);if(vault.nonces.size>10_000)vault.nonces.clear();return vault;}
  async registerVault(vaultId:string,device:DeviceRegistration,proof:SignedRequest){if(this.vaults.has(vaultId))throw new Error("SYNC_VAULT_EXISTS");if(proof.device_id!==device.device_id||!verifyRequest(device.signing_public_key,proof,"POST",`/v1/sync/vaults/${vaultId}`,device))throw new Error("SYNC_BOOTSTRAP_PROOF_INVALID");this.vaults.set(vaultId,{devices:new Map([[device.device_id,device]]),records:[],recordIds:new Set(),chunks:new Map(),nonces:new Set([proof.nonce]),nextSequence:1});}
  async enrollDevice(vaultId:string,device:DeviceRegistration,proof:SignedRequest){const body=device,vault=this.authenticate(vaultId,proof,"POST",`/v1/sync/vaults/${vaultId}/devices`,body);if(vault.devices.get(device.device_id)?.revoked_at)throw new Error("SYNC_DEVICE_ID_REVOKED");vault.devices.set(device.device_id,device);}
  async revokeDevice(vaultId:string,deviceId:string,proof:SignedRequest){const body={device_id:deviceId},vault=this.authenticate(vaultId,proof,"DELETE",`/v1/sync/vaults/${vaultId}/devices/${deviceId}`,body),device=vault.devices.get(deviceId);if(!device||device.revoked_at)throw new Error("SYNC_DEVICE_NOT_FOUND");if([...vault.devices.values()].filter(row=>!row.revoked_at).length===1)throw new Error("SYNC_LAST_DEVICE_REQUIRED");device.revoked_at=new Date().toISOString();}
  async push(vaultId:string,envelopes:EncryptedEnvelope[],proof:SignedRequest){if(envelopes.length>500)throw new Error("SYNC_BATCH_TOO_LARGE");const body={envelopes},vault=this.authenticate(vaultId,proof,"POST",`/v1/sync/vaults/${vaultId}/records`,body),accepted=[];for(const envelope of envelopes){validateEnvelope(envelope);if(envelope.vault_id!==vaultId||envelope.device_id!==proof.device_id)throw new Error("SYNC_ENVELOPE_SCOPE_INVALID");if(vault.recordIds.has(envelope.record_id)){accepted.push(envelope.record_id);continue;}vault.recordIds.add(envelope.record_id);vault.records.push({sequence:vault.nextSequence++,envelope});accepted.push(envelope.record_id);}return {accepted};}
  async pull(vaultId:string,after:number,limit:number,proof:SignedRequest){const body={after,limit},vault=this.authenticate(vaultId,proof,"GET",`/v1/sync/vaults/${vaultId}/records`,body),records=vault.records.filter(row=>row.sequence>after).slice(0,Math.max(1,Math.min(500,limit))),cursor=records.at(-1)?.sequence??after;return {records,cursor};}
  async missingChunks(vaultId:string,ids:string[],proof:SignedRequest){const body={ids},vault=this.authenticate(vaultId,proof,"POST",`/v1/sync/vaults/${vaultId}/chunks/missing`,body);return ids.filter(id=>!vault.chunks.get(id)?.complete);}
  async putChunkPart(vaultId:string,meta:Omit<EncryptedChunk,"ciphertext">,offset:number,ciphertextPart:string,final:boolean,proof:SignedRequest){validateChunkMeta(meta);const decoded=Buffer.from(ciphertextPart,"base64url");if(decoded.length>512*1024)throw new Error("SYNC_CHUNK_PART_TOO_LARGE");const body={meta,offset,ciphertext_part:ciphertextPart,final},vault=this.authenticate(vaultId,proof,"PUT",`/v1/sync/vaults/${vaultId}/chunks/${meta.chunk_id}`,body);let stored=vault.chunks.get(meta.chunk_id);if(stored?.complete)return {complete:true,received:stored.received};if(!stored){if(offset!==0)throw new Error("SYNC_CHUNK_OFFSET_MISMATCH");stored={meta,parts:[],received:0,complete:false};vault.chunks.set(meta.chunk_id,stored);}if(stored.received!==offset)throw new Error("SYNC_CHUNK_OFFSET_MISMATCH");if(stored.meta.nonce!==meta.nonce||stored.meta.tag!==meta.tag||stored.meta.size!==meta.size)throw new Error("SYNC_CHUNK_METADATA_MISMATCH");if(final&&stored.received+decoded.length!==meta.size)throw new Error("SYNC_CHUNK_SIZE_MISMATCH");stored.parts.push(decoded);stored.received+=decoded.length;if(final)stored.complete=true;return {complete:stored.complete,received:stored.received};}
  async getChunk(vaultId:string,id:string,proof:SignedRequest){const body={chunk_id:id},vault=this.authenticate(vaultId,proof,"GET",`/v1/sync/vaults/${vaultId}/chunks/${id}`,body),stored=vault.chunks.get(id);if(!stored?.complete)throw new Error("SYNC_CHUNK_NOT_FOUND");return {...stored.meta,ciphertext:Buffer.concat(stored.parts).toString("base64url")};}
  async resetDevice(vaultId:string,proof:SignedRequest){this.authenticate(vaultId,proof,"POST",`/v1/sync/vaults/${vaultId}/reset`,{});}
  async deleteVault(vaultId:string,proof:SignedRequest){this.authenticate(vaultId,proof,"DELETE",`/v1/sync/vaults/${vaultId}`,{});this.vaults.delete(vaultId);}
  inspectOpaque(vaultId:string){const vault=this.vaults.get(vaultId);if(!vault)return null;return {devices:[...vault.devices.values()].map(d=>({device_id:d.device_id,revoked:!!d.revoked_at})),records:vault.records.map(r=>({sequence:r.sequence,record_id:r.envelope.record_id,entity_id:r.envelope.entity_id,ciphertext_bytes:Buffer.from(r.envelope.ciphertext,"base64url").length})),chunks:[...vault.chunks.values()].map(c=>({chunk_id:c.meta.chunk_id,size:c.meta.size,received:c.received,complete:c.complete}))};}
}
