import { createHash } from "node:crypto";
import { Pool,type PoolClient } from "pg";
import { verifyRequest } from "../../../packages/cloud-sync/src/crypto";
import { validateChunkMeta,validateEnvelope,type DeviceRegistration,type EncryptedChunk,type EncryptedEnvelope,type RelayRecord,type SignedRequest,type SyncRelayTransport } from "../../../packages/cloud-sync/src/protocol";

export class PostgresZeroKnowledgeRelay implements SyncRelayTransport{
  constructor(private readonly pool:Pool){}
  private async authenticated<T>(vaultId:string,proof:SignedRequest,method:string,path:string,body:unknown,work:(client:PoolClient)=>Promise<T>):Promise<T>{const client=await this.pool.connect();try{await client.query("BEGIN");await client.query(`DELETE FROM sync_request_nonces WHERE expires_at<now()`);const device=await client.query(`SELECT signing_public_key,revoked_at FROM sync_devices WHERE vault_id=$1 AND device_id=$2 FOR SHARE`,[vaultId,proof.device_id]);if(device.rowCount!==1||device.rows[0].revoked_at)throw new Error("SYNC_DEVICE_REVOKED");if(!verifyRequest(device.rows[0].signing_public_key,proof,method,path,body))throw new Error("SYNC_SIGNATURE_INVALID");const nonceHash=createHash("sha256").update(proof.nonce).digest("hex");await client.query(`INSERT INTO sync_request_nonces(vault_id,device_id,nonce_hash,expires_at) VALUES($1,$2,$3,now()+interval '10 minutes')`,[vaultId,proof.device_id,nonceHash]).catch(()=>{throw new Error("SYNC_REPLAY_REJECTED")});const result=await work(client);await client.query("COMMIT");return result;}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}}
  async registerVault(vaultId:string,device:DeviceRegistration,proof:SignedRequest){if(proof.device_id!==device.device_id||!verifyRequest(device.signing_public_key,proof,"POST",`/v1/sync/vaults/${vaultId}`,device))throw new Error("SYNC_BOOTSTRAP_PROOF_INVALID");const client=await this.pool.connect();try{await client.query("BEGIN");await client.query(`INSERT INTO sync_vaults(vault_id) VALUES($1)`,[vaultId]);await client.query(`INSERT INTO sync_devices(vault_id,device_id,signing_public_key,encryption_public_key,enrolled_at) VALUES($1,$2,$3,$4,$5)`,[vaultId,device.device_id,device.signing_public_key,device.encryption_public_key,device.enrolled_at]);await client.query("COMMIT");}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}}
  enrollDevice(vaultId:string,device:DeviceRegistration,proof:SignedRequest){return this.authenticated(vaultId,proof,"POST",`/v1/sync/vaults/${vaultId}/devices`,device,async client=>{await client.query(`INSERT INTO sync_devices(vault_id,device_id,signing_public_key,encryption_public_key,enrolled_at) VALUES($1,$2,$3,$4,$5) ON CONFLICT(vault_id,device_id) DO UPDATE SET signing_public_key=EXCLUDED.signing_public_key,encryption_public_key=EXCLUDED.encryption_public_key,enrolled_at=EXCLUDED.enrolled_at WHERE sync_devices.revoked_at IS NULL`,[vaultId,device.device_id,device.signing_public_key,device.encryption_public_key,device.enrolled_at]);});}
  revokeDevice(vaultId:string,deviceId:string,proof:SignedRequest){const body={device_id:deviceId};return this.authenticated(vaultId,proof,"DELETE",`/v1/sync/vaults/${vaultId}/devices/${deviceId}`,body,async client=>{const active=await client.query(`SELECT device_id FROM sync_devices WHERE vault_id=$1 AND revoked_at IS NULL FOR UPDATE`,[vaultId]);if((active.rowCount??0)<=1)throw new Error("SYNC_LAST_DEVICE_REQUIRED");const result=await client.query(`UPDATE sync_devices SET revoked_at=now() WHERE vault_id=$1 AND device_id=$2 AND revoked_at IS NULL`,[vaultId,deviceId]);if(result.rowCount!==1)throw new Error("SYNC_DEVICE_NOT_FOUND");});}
  push(vaultId:string,envelopes:EncryptedEnvelope[],proof:SignedRequest){if(envelopes.length>500)throw new Error("SYNC_BATCH_TOO_LARGE");for(const envelope of envelopes)validateEnvelope(envelope);const body={envelopes};return this.authenticated(vaultId,proof,"POST",`/v1/sync/vaults/${vaultId}/records`,body,async client=>{await client.query(`SELECT pg_advisory_xact_lock(hashtextextended($1,0))`,[vaultId]);const cursor=await client.query(`SELECT next_sequence FROM sync_vaults WHERE vault_id=$1 FOR UPDATE`,[vaultId]),accepted=[];let sequence=Number(cursor.rows[0].next_sequence);for(const envelope of envelopes){if(envelope.vault_id!==vaultId||envelope.device_id!==proof.device_id)throw new Error("SYNC_ENVELOPE_SCOPE_INVALID");const result=await client.query(`INSERT INTO sync_records(vault_id,sequence,record_id,device_id,entity_id,envelope,ciphertext_bytes) VALUES($1,$2,$3,$4,$5,$6::jsonb,$7) ON CONFLICT(vault_id,record_id) DO NOTHING`,[vaultId,sequence,envelope.record_id,envelope.device_id,envelope.entity_id,JSON.stringify(envelope),Buffer.from(envelope.ciphertext,"base64url").length]);if(result.rowCount===1)sequence++;accepted.push(envelope.record_id);}await client.query(`UPDATE sync_vaults SET next_sequence=$2 WHERE vault_id=$1`,[vaultId,sequence]);return {accepted};});}
  pull(vaultId:string,after:number,limit:number,proof:SignedRequest){const body={after,limit};return this.authenticated(vaultId,proof,"GET",`/v1/sync/vaults/${vaultId}/records`,body,async client=>{const result=await client.query(`SELECT sequence,envelope FROM sync_records WHERE vault_id=$1 AND sequence>$2 ORDER BY sequence LIMIT $3`,[vaultId,after,Math.max(1,Math.min(500,limit))]),records=result.rows.map(row=>({sequence:Number(row.sequence),envelope:row.envelope})) as RelayRecord[];return {records,cursor:records.at(-1)?.sequence??after};});}
  missingChunks(vaultId:string,ids:string[],proof:SignedRequest){const body={ids};return this.authenticated(vaultId,proof,"POST",`/v1/sync/vaults/${vaultId}/chunks/missing`,body,async client=>{const found=await client.query(`SELECT chunk_id FROM sync_chunks WHERE vault_id=$1 AND chunk_id=ANY($2::text[]) AND complete=true`,[vaultId,ids]),present=new Set(found.rows.map(row=>row.chunk_id));return ids.filter(id=>!present.has(id));});}
  putChunkPart(vaultId:string,meta:Omit<EncryptedChunk,"ciphertext">,offset:number,ciphertextPart:string,final:boolean,proof:SignedRequest){validateChunkMeta(meta);const part=Buffer.from(ciphertextPart,"base64url");if(part.length>512*1024)throw new Error("SYNC_CHUNK_PART_TOO_LARGE");const body={meta,offset,ciphertext_part:ciphertextPart,final};return this.authenticated(vaultId,proof,"PUT",`/v1/sync/vaults/${vaultId}/chunks/${meta.chunk_id}`,body,async client=>{await client.query(`INSERT INTO sync_chunks(vault_id,chunk_id,nonce,auth_tag,plaintext_size) VALUES($1,$2,$3,$4,$5) ON CONFLICT DO NOTHING`,[vaultId,meta.chunk_id,meta.nonce,meta.tag,meta.size]);const current=await client.query(`SELECT nonce,auth_tag,plaintext_size,octet_length(ciphertext) AS received,complete FROM sync_chunks WHERE vault_id=$1 AND chunk_id=$2 FOR UPDATE`,[vaultId,meta.chunk_id]);if(current.rows[0].complete)return {complete:true,received:Number(current.rows[0].received)};if(current.rows[0].nonce!==meta.nonce||current.rows[0].auth_tag!==meta.tag||Number(current.rows[0].plaintext_size)!==meta.size)throw new Error("SYNC_CHUNK_METADATA_MISMATCH");if(Number(current.rows[0].received)!==offset)throw new Error("SYNC_CHUNK_OFFSET_MISMATCH");if(final&&offset+part.length!==meta.size)throw new Error("SYNC_CHUNK_SIZE_MISMATCH");const updated=await client.query(`UPDATE sync_chunks SET ciphertext=ciphertext||$3::bytea,complete=$4 WHERE vault_id=$1 AND chunk_id=$2 RETURNING octet_length(ciphertext) AS received,complete`,[vaultId,meta.chunk_id,part,final]);return {complete:updated.rows[0].complete,received:Number(updated.rows[0].received)};});}
  getChunk(vaultId:string,id:string,proof:SignedRequest){const body={chunk_id:id};return this.authenticated(vaultId,proof,"GET",`/v1/sync/vaults/${vaultId}/chunks/${id}`,body,async client=>{const result=await client.query(`SELECT chunk_id,nonce,auth_tag,plaintext_size,ciphertext FROM sync_chunks WHERE vault_id=$1 AND chunk_id=$2 AND complete=true`,[vaultId,id]);if(result.rowCount!==1)throw new Error("SYNC_CHUNK_NOT_FOUND");const row=result.rows[0];return {chunk_id:row.chunk_id,nonce:row.nonce,tag:row.auth_tag,size:Number(row.plaintext_size),ciphertext:(row.ciphertext as Buffer).toString("base64url")};});}
  resetDevice(vaultId:string,proof:SignedRequest){return this.authenticated(vaultId,proof,"POST",`/v1/sync/vaults/${vaultId}/reset`,{},async()=>{});}
  deleteVault(vaultId:string,proof:SignedRequest){return this.authenticated(vaultId,proof,"DELETE",`/v1/sync/vaults/${vaultId}`,{},async client=>{await client.query(`DELETE FROM sync_vaults WHERE vault_id=$1`,[vaultId]);});}
}
