import{readFileSync}from"node:fs";import{resolve}from"node:path";
import{AUTHORITY_STATES,KERNEL_KINDS,KERNEL_VERSION,authorityRank,canDisclose,stableKernelDigest,validateKernelRecord,validateLifecycleTransition,type KernelKind}from"../../packages/semantic-kernel/src";
import{canonicalKernelURI,parseCKURI}from"../../packages/ckuri/src";
const id=(n:number)=>`018f2f0${n}-7b3c-7a21-8a4b-123456789abc`;
const payloads:Record<KernelKind,Record<string,unknown>>={cko:{title:"Atlas",object_type:"project"},entity:{name:"CERVEL",entity_type:"organization"},claim:{subject:{kind:"entity",id:id(1)},predicate:"founded_by",object:{kind:"entity",id:id(2)}},relationship:{source:{kind:"entity",id:id(1)},predicate:"FOUNDED_BY",target:{kind:"entity",id:id(2)}},event:{event_type:"project_started",participants:[],occurred_at:"2026-08-24T00:00:00Z"},state:{subject:{kind:"entity",id:id(1)},predicate:"funding_status",value:"seed",effective_from:"2026-08-24T00:00:00Z"},memory:{memory_type:"episode",title:"Austin fundraising trip",source_event_ids:[id(3)]},provenance:{event_type:"created",outputs:[{kind:"state",id:id(4)}]},authority:{subject:{kind:"claim",id:id(5)},status:"verified",source_refs:[{kind:"cko",id:id(6)}]},permission:{effect:"allow",operations:["read","reason"],principal_ref:{kind:"entity",id:id(7)},resource_ref:{kind:"cko",id:id(8)}}};
function record(kind:KernelKind){return{id:id(0),node_id:id(1),workspace_id:id(2),kind,lifecycle:"active"as const,sensitivity:"internal"as const,authority:"reported"as const,confidence:.82,payload:payloads[kind],observed_at:"2026-08-24T00:00:00Z",effective_from:null,effective_until:null,supersedes_id:null,policy_id:null,provenance_event_id:null,created_by:id(3)};}
describe("CERVEL Semantic Kernel v1",()=>{
 test("freezes ten interoperable primitives",()=>{expect(KERNEL_VERSION).toBe("1.0");expect(KERNEL_KINDS).toEqual(["cko","entity","claim","relationship","event","state","memory","provenance","authority","permission"]);for(const kind of KERNEL_KINDS)expect(validateKernelRecord(record(kind))).toEqual(record(kind));});
 test("rejects malformed confidence, temporal intervals and primitive payloads",()=>{expect(()=>validateKernelRecord({...record("claim"),confidence:1.1})).toThrow("KERNEL_CONFIDENCE_INVALID");expect(()=>validateKernelRecord({...record("state"),effective_from:"2026-09-01T00:00:00Z",effective_until:"2026-08-01T00:00:00Z"})).toThrow("KERNEL_EFFECTIVE_INTERVAL_INVALID");expect(()=>validateKernelRecord({...record("claim"),payload:{subject:{},predicate:"x"}})).toThrow("KERNEL_PAYLOAD_OBJECT_REQUIRED");expect(()=>validateKernelRecord({...record("permission"),payload:{...payloads.permission,operations:["steal"]}})).toThrow("KERNEL_PERMISSION_INVALID");});
 test("enforces lifecycle, sensitivity and authority semantics",()=>{expect(()=>validateLifecycleTransition("superseded","active")).toThrow("KERNEL_LIFECYCLE_TRANSITION_INVALID");expect(()=>validateLifecycleTransition("archived","active")).not.toThrow();expect(canDisclose("confidential","internal")).toBe(false);expect(canDisclose("internal","confidential")).toBe(true);expect(authorityRank("official")).toBeGreaterThan(authorityRank("reported"));expect(AUTHORITY_STATES).toContain("disputed");});
 test("produces stable canonical digests and kernel CKURIs",()=>{expect(stableKernelDigest({b:2,a:1})).toBe(stableKernelDigest({a:1,b:2}));const uri=canonicalKernelURI("LOCAL","state",id(4));expect(uri).toBe(`cervel://local/kernel/state/${id(4)}`);expect(parseCKURI(uri)).toMatchObject({authority:"local",kernelResource:{kind:"state",id:id(4)}});});
 test("ships a strict versioned schema and compatibility migration",()=>{const schema=JSON.parse(readFileSync(resolve("packages/contracts/v1.0/semantic-kernel.schema.json"),"utf8")),migration=readFileSync(resolve("db/migrations/031_semantic_kernel_v1.sql"),"utf8");expect(schema.$id).toContain("semantic-kernel/1.0");expect(schema.additionalProperties).toBe(false);for(const token of["semantic_kernel_records","semantic_kernel_bindings","semantic_kernel_versions","payload_sha256","ENABLE ROW LEVEL SECURITY","semantic_kernel_payload_gin_idx"])expect(migration).toContain(token);});
});
