import{classifySensitivity,classifyTask,DEFAULT_CAPABILITY_REGISTRY,planRoute}from"../../packages/intelligence-gateway/src";
import{AnthropicMessagesAdapter,OpenAICompatibleAdapter}from"../../apps/api/src/model-adapters";
const policy={offline_only:false,network_allowed:true,monthly_budget_usd:25,spent_usd:0,max_request_usd:1,allow_confidential_external:false,allow_restricted_external:false,quality_floor:.55};
const providers=DEFAULT_CAPABILITY_REGISTRY.map(p=>({...p,enabled:true,healthy:true}));
describe("CERVEL Intelligence Gateway",()=>{
 test("classifies task and sensitivity before routing",()=>{expect(classifyTask({query:"analyze our strategy",evidence_count:4})).toBe("analysis");expect(classifyTask({query:"debug this TypeScript API",evidence_count:1})).toBe("coding");expect(classifySensitivity("Review this confidential payroll file")).toBe("confidential");expect(classifySensitivity("Never reveal my private key")).toBe("restricted");});
 test("returns Vault evidence without generation or external disclosure",()=>{const route=planRoute({query:"show the files about CERVEL",evidence_count:8,estimated_input_tokens:1200,policy},providers);expect(route.mode).toBe("retrieval_without_generation");expect(route.selected.provider.kind).toBe("local");expect(route.selected.estimated_cost_usd).toBe(0);expect(route.disclosure.external).toBe(false);});
 test("selects an efficient capable model for complex public work",()=>{const route=planRoute({query:"analyze this strategy and recommend next steps",evidence_count:8,estimated_input_tokens:5000,policy},providers);expect(route.mode).toBe("generation");expect(route.selected.provider.quality).toBeGreaterThanOrEqual(.8);expect(route.fallbacks.length).toBeGreaterThan(1);});
 test("restricted Vault material cannot leave the device",()=>{expect(()=>planRoute({query:"analyze my private key and secret password",evidence_count:2,estimated_input_tokens:1000,policy},providers)).toThrow("INTELLIGENCE_ROUTE_UNAVAILABLE");});
 test("offline-only enforcement excludes every network provider",()=>{const route=planRoute({query:"summarize the Vault notes",evidence_count:5,estimated_input_tokens:2000,policy:{...policy,offline_only:true,network_allowed:false}},providers);expect(route.selected.provider.kind).toBe("local");expect(route.fallbacks.every(x=>x.provider.kind==="local")).toBe(true);});
 test("evidence sensitivity overrides an innocent-looking query",()=>{const route=planRoute({query:"summarize this",sensitivity_hint:"restricted",evidence_count:5,estimated_input_tokens:2000,policy:{...policy,offline_only:true,network_allowed:false}},providers);expect(route.sensitivity).toBe("restricted");expect(route.selected.provider.kind).toBe("local");});
 test("budget exhaustion fails closed instead of silently spending",()=>{expect(()=>planRoute({query:"analyze a public market strategy",evidence_count:3,estimated_input_tokens:20_000,policy:{...policy,spent_usd:25}},providers.filter(x=>x.id!=="enterprise"))).toThrow("INTELLIGENCE_ROUTE_UNAVAILABLE");});
 test("capability registry covers all supported endpoints",()=>{expect(new Set(DEFAULT_CAPABILITY_REGISTRY.map(x=>x.id))).toEqual(new Set(["local:deterministic","local:ollama","openai","anthropic","google","openrouter","enterprise"]));});
 test("Anthropic adapter preserves the evidence-only contract",async()=>{const original=global.fetch;global.fetch=jest.fn(async()=>new Response(JSON.stringify({id:"msg_1",content:[{type:"text",text:"Supported [1]"}]}),{status:200}))as any;try{await expect(new AnthropicMessagesAdapter("key","model").execute({query:"q",contested:false,evidence:[{text:"e",citation:"ck://x"}]})).resolves.toMatchObject({provider:"anthropic",text:"Supported [1]"});expect(global.fetch).toHaveBeenCalledWith("https://api.anthropic.com/v1/messages",expect.objectContaining({method:"POST"}));}finally{global.fetch=original;}});
 test("compatible remote endpoints require explicit network permission",async()=>{await expect(new OpenAICompatibleAdapter("https://enterprise.example/v1/","key","model",false).execute({query:"q",contested:false,evidence:[]})).rejects.toThrow("MODEL_NETWORK_PERMISSION_REQUIRED");});
});
