export function renderWorkspaceAlpha(): string {
  return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>CERVEL Workspace</title><style>
:root{color-scheme:dark;--bg:#090b10;--panel:#10141c;--line:#222938;--text:#f4f7fb;--muted:#909bad;--accent:#d8ff66}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:14px Inter,ui-sans-serif,system-ui,-apple-system,sans-serif}button,input,textarea{font:inherit}.app{display:grid;grid-template-columns:240px 1fr;min-height:100vh}.side{border-right:1px solid var(--line);padding:22px 16px;position:sticky;top:0;height:100vh}.brand{font-size:20px;font-weight:800;letter-spacing:.16em;margin:4px 10px 28px}.brand b{color:var(--accent)}nav button{display:block;width:100%;text-align:left;border:0;background:transparent;color:var(--muted);padding:11px 12px;border-radius:9px;cursor:pointer;margin:3px 0}nav button:hover,nav button.active{background:#171c26;color:var(--text)}main{padding:28px 34px;max-width:1300px;width:100%}.top{display:flex;justify-content:space-between;align-items:center;margin-bottom:26px}.eyebrow{color:var(--accent);text-transform:uppercase;font-size:11px;letter-spacing:.14em}.title{font-size:28px;font-weight:720;margin:4px 0}.muted{color:var(--muted)}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:12px}.card{background:var(--panel);border:1px solid var(--line);border-radius:14px;padding:16px}.card h3{margin:0 0 7px}.meta{font-size:12px;color:var(--muted);margin-top:10px}.search,.ask{width:100%;background:#0d1118;border:1px solid var(--line);color:var(--text);border-radius:11px;padding:12px}.ask{min-height:100px;resize:vertical}.primary{border:0;border-radius:9px;padding:10px 14px;background:var(--accent);color:#111;font-weight:700;cursor:pointer}.row{display:flex;gap:10px;align-items:center}.grow{flex:1}.pill{display:inline-block;padding:4px 7px;border:1px solid var(--line);border-radius:99px;color:var(--muted);font-size:11px}.answer{white-space:pre-wrap;line-height:1.55}.graph{position:relative;min-height:460px;overflow:hidden}.node{position:absolute;padding:7px 10px;border:1px solid #465066;border-radius:99px;background:#151b25;max-width:180px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.login{max-width:520px;margin:12vh auto}.login input{display:block;width:100%;margin:8px 0;background:#0d1118;border:1px solid var(--line);color:var(--text);padding:12px;border-radius:9px}@media(max-width:760px){.app{grid-template-columns:1fr}.side{height:auto;position:relative;border-right:0;border-bottom:1px solid var(--line)}nav{display:flex;overflow:auto}nav button{white-space:nowrap}main{padding:22px 16px}}
</style></head><body><div id="root"></div><script>
const state={token:localStorage.getItem('cervel_session')||'',view:'inbox',bootstrap:null};
const api=async(path,opts={})=>{const headers={'content-type':'application/json',...(opts.headers||{})};if(state.token)headers.authorization='Bearer '+state.token;const r=await fetch(path,{...opts,headers});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'REQUEST_FAILED');return data};
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
function shell(content){return '<div class="app"><aside class="side"><div class="brand">CERVEL<b>.</b></div><nav>'+['inbox','library','ask','entities','graph'].map(v=>'<button data-view="'+v+'" class="'+(state.view===v?'active':'')+'">'+({inbox:'Knowledge Inbox',library:'Library',ask:'Ask CERVEL',entities:'Entities',graph:'Graph Explorer'}[v])+'</button>').join('')+'</nav></aside><main><div class="top"><div><div class="eyebrow">Sovereign knowledge workspace</div><div class="title">'+esc(({inbox:'Knowledge Inbox',library:'Library',ask:'Ask CERVEL',entities:'Semantic Entities',graph:'Knowledge Graph'}[state.view]))+'</div></div><button id="logout">Sign out</button></div>'+content+'</main></div>'}
function login(){document.getElementById('root').innerHTML='<div class="login card"><div class="eyebrow">CERVEL Workspace Alpha</div><div class="title">Enter your sovereign workspace</div><p class="muted">Alpha bootstrap uses your existing CERVEL principal identity. The server exchanges it for an expiring session token; the browser never sends principal headers after sign-in.</p><input id="node" placeholder="Node UUID"><input id="principal" placeholder="Principal UUID"><input id="workspace" placeholder="Workspace UUID (optional)"><button class="primary" id="signin">Create session</button><p id="err" class="muted"></p></div>';document.getElementById('signin').onclick=async()=>{try{const x=await api('/v1/session',{method:'POST',body:JSON.stringify({node_id:node.value,principal_id:principal.value,workspace_id:workspace.value||null})});state.token=x.token;localStorage.setItem('cervel_session',x.token);await boot()}catch(e){err.textContent=e.message}}}
async function boot(){try{state.bootstrap=await api('/v1/workspace');render()}catch(e){localStorage.removeItem('cervel_session');state.token='';login()}}
async function render(){if(!state.token)return login();let content='';if(state.view==='inbox'||state.view==='library'){const objects=await api('/v1/workspace/objects');content='<div class="row"><input id="q" class="search grow" placeholder="Search objects, notes, documents..."></div><div class="grid" id="objects" style="margin-top:14px">'+objects.map(o=>'<article class="card" data-object="'+o.id+'"><span class="pill">'+esc(o.type)+'</span><h3>'+esc(o.title)+'</h3><div class="muted">'+esc(o.summary||'No summary yet')+'</div><div class="meta">'+o.artifact_count+' artifacts · '+o.fragment_count+' fragments</div></article>').join('')+'</div>'}
if(state.view==='ask')content='<div class="card"><textarea id="question" class="ask" placeholder="Ask a question across your authorized CERVEL knowledge..."></textarea><div class="row" style="margin-top:10px"><button class="primary" id="askbtn">Reason over knowledge</button><span class="muted">CCP → semantic reasoning → cited answer</span></div></div><div id="answer" class="card answer" style="margin-top:14px">Your answer and Trace link will appear here.</div>';
if(state.view==='entities'){const entities=await api('/v1/workspace/entities');content='<div class="grid">'+entities.map(e=>'<article class="card" data-entity="'+e.id+'"><span class="pill">'+esc(e.kind)+'</span><h3>'+esc(e.canonical_name)+'</h3><div class="meta">'+e.claim_count+' connected claims · resolution '+Math.round(Number(e.resolution_confidence||0)*100)+'%</div></article>').join('')+'</div>'}
if(state.view==='graph'){const g=await api('/v1/workspace/graph');content='<div class="card"><div class="muted">'+g.nodes.length+' entities · '+g.edges.length+' semantic edges</div><div class="graph">'+g.nodes.slice(0,40).map((n,i)=>'<div class="node" style="left:'+(5+(i*23)%80)+'%;top:'+(45+(i*67)%360)+'px">'+esc(n.canonical_name)+'</div>').join('')+'</div></div>'}
document.getElementById('root').innerHTML=shell(content);wire()}
function wire(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;render()});document.getElementById('logout').onclick=async()=>{await api('/v1/session',{method:'DELETE'}).catch(()=>{});localStorage.removeItem('cervel_session');state.token='';login()};const q=document.getElementById('q');if(q)q.onchange=async()=>{const x=await api('/v1/workspace/objects?q='+encodeURIComponent(q.value));document.getElementById('objects').innerHTML=x.map(o=>'<article class="card"><h3>'+esc(o.title)+'</h3><div class="muted">'+esc(o.summary||'')+'</div></article>').join('')};const ask=document.getElementById('askbtn');if(ask)ask.onclick=async()=>{const out=document.getElementById('answer');out.textContent='Reasoning…';try{const r=await api('/v1/workspace/ask',{method:'POST',body:JSON.stringify({query:document.getElementById('question').value})});out.innerHTML='<strong>'+esc(r.answer)+'</strong><div class="meta">Confidence '+Math.round(Number(r.semantic?.confidence?.final||0)*100)+'% · <a href="/trace/'+r.id+'" target="_blank">Open full Trace</a></div>'}catch(e){out.textContent=e.message}}}
state.token?boot():login();
</script></body></html>`;
}
