import{MCP_TOOLS,approveWrite,authorize,issueOpaqueToken,mcpCapabilities,proposeWrite,tokenDigest,type AccessGrant}from"../../packages/external-gateway/src";
const grant:AccessGrant={client_id:"client",node_id:"node",principal_id:"principal",scopes:["retrieval:read","write:propose"],library_ids:["allowed"],expires_at:"2099-01-01T00:00:00Z",budget:{max_fragments:2,max_bytes:100,max_sensitive_fragments:0,period:"request"}};
describe("External AI and Agent Gateway",()=>{
 test("exposes a provider-neutral MCP contract",()=>{expect(mcpCapabilities().protocolVersion).toBe("2025-06-18");expect(MCP_TOOLS.map(x=>x.name)).toEqual(["cervel_search","cervel_reason","cervel_trace","cervel_propose_write"]);expect(MCP_TOOLS.find(x=>x.name==="cervel_propose_write")?.read_only).toBe(false);});
 test("enforces scope, library, byte, fragment, and sensitive disclosure budgets",()=>{const d=authorize(grant,"retrieval:read",[{id:"a",bytes:40,sensitive:false,library_id:"allowed"},{id:"b",bytes:30,sensitive:true,library_id:"allowed"},{id:"c",bytes:40,sensitive:false,library_id:"other"},{id:"d",bytes:40,sensitive:false,library_id:"allowed"}]);expect(d).toMatchObject({allowed:true,code:"BUDGET_PARTIAL",disclosed_ids:["a","d"],bytes:80,sensitive_count:0});expect(authorize(grant,"reasoning:execute").code).toBe("SCOPE_DENIED");});
 test("fails closed after expiry or revocation",()=>{expect(authorize({...grant,revoked_at:new Date().toISOString()},"retrieval:read").code).toBe("GRANT_REVOKED");expect(authorize({...grant,expires_at:"2020-01-01T00:00:00Z"},"retrieval:read").code).toBe("GRANT_EXPIRED");});
 test("binds human write approval to the reviewed payload digest",()=>{const p=proposeWrite({id:"p",grant_id:"g",tool:"create_object",arguments:{title:"Approved"}});expect(approveWrite(p,p.input_digest).status).toBe("approved");expect(()=>approveWrite(p,tokenDigest("changed"))).toThrow("PROPOSAL_CHANGED_AFTER_REVIEW");});
 test("issues non-recoverable bearer credentials",()=>{const token=issueOpaqueToken();expect(token).toMatch(/^cvl_/);expect(tokenDigest(token)).toHaveLength(64);expect(tokenDigest(token)).not.toContain(token);});
 test("fails closed when one response exceeds the byte ceiling",()=>{const d=authorize(grant,"retrieval:read",[{id:"fragment",bytes:101,sensitive:false}]);expect(d).toMatchObject({allowed:true,code:"BUDGET_PARTIAL",disclosed_ids:[],bytes:0});});
});
