import { spawn } from "node:child_process";
import { readFile, readdir, stat, unlink } from "node:fs/promises";
import { homedir } from "node:os";
import { basename, extname, join, resolve } from "node:path";
import { atomicWrite, createVault, decryptBuffer, encryptBuffer, unlockVault, type VaultManifest, type VaultSecrets } from "../../local-node/src/vault";
import { LocalCloudSyncController } from "../../local-node/src/cloud-sync";

export type BootstrapIdentity={nodeId:string;workspaceId:string;principalId:string;storageLocationId:string;authority:string};
export type ProviderConfiguration={provider:"local"|"ollama"|"openai-compatible";base_url:string;model:string;api_key?:string;allow_network:boolean};
export type OpenVault={root:string;manifest:VaultManifest;identity:BootstrapIdentity;url:string};
type Unlocked={manifest:VaultManifest;secrets:VaultSecrets;artifactKey:Buffer};

const contentTypes:Record<string,string>={".txt":"text/plain",".md":"text/markdown",".json":"application/json",".csv":"text/csv",".html":"text/html",".pdf":"application/pdf"};
const wait=(ms:number)=>new Promise(resolveWait=>setTimeout(resolveWait,ms));

export class LocalNodeClient {
  private root:string|null=null;private passphrase:string|null=null;private unlocked:Unlocked|null=null;private identity:BootstrapIdentity|null=null;private cloudSync:LocalCloudSyncController|null=null;private readonly port:number;
  constructor(private readonly appRoot:string,port=8787){this.port=port;}
  get isOpen(){return Boolean(this.root&&this.unlocked&&this.identity);}
  get vaultRoot(){return this.root;}
  async create(root:string,name:string,authority:string,passphrase:string):Promise<OpenVault>{await createVault(root,name,authority,passphrase);return this.open(root,passphrase);}
  async open(root:string,passphrase:string):Promise<OpenVault>{this.root=resolve(root);this.passphrase=passphrase;try{this.unlocked=await unlockVault(this.root,passphrase);await this.ensureStarted();this.identity=await this.readIdentity();await this.publishCaptureHost();return {root:this.root,manifest:this.unlocked.manifest,identity:this.identity,url:this.url};}catch(error){this.forget();throw error;}}
  forget():void{void unlink(join(homedir(),".cervel","native-hosts","default.json")).catch(()=>{});this.root=null;this.passphrase=null;this.unlocked=null;this.identity=null;this.cloudSync=null;}
  private get url(){return `http://127.0.0.1:${this.port}`;}
  private cliPath():string{const compiled=join(this.appRoot,"dist/apps/local-node/src/cli.js");return compiled;}
  private async runCli(command:string,args:string[]=[]):Promise<Record<string,unknown>>{
    const root=this.root,passphrase=this.passphrase;if(!root||!passphrase)throw new Error("VAULT_LOCKED");
    return new Promise((resolveRun,reject)=>{let stdout="",stderr="";
      void this.providerEnvironment().then(providerEnv=>{const child=spawn(process.execPath,[this.cliPath(),command,"--vault",root,"--port",String(this.port),...args],{cwd:this.appRoot,env:{...process.env,...providerEnv,ELECTRON_RUN_AS_NODE:"1",CERVEL_VAULT_PASSPHRASE:passphrase},windowsHide:true,stdio:["ignore","pipe","pipe"]});
      child.stdout.on("data",(chunk:Buffer)=>stdout+=chunk.toString());child.stderr.on("data",(chunk:Buffer)=>stderr+=chunk.toString());child.on("error",reject);child.on("close",(code:number|null)=>{if(code!==0)return reject(new Error(stderr.trim()||`cervel ${command} failed (${code})`));const line=stdout.trim().split("\n").at(-1);try{resolveRun(line?JSON.parse(line):{ok:true});}catch{reject(new Error("Local Node returned invalid lifecycle output"));}});}).catch(reject);
    });
  }
  private async providerEnvironment():Promise<NodeJS.ProcessEnv>{if(!this.unlocked)return {};const config=await this.getProviderConfiguration();if(config.provider==="local")return {CERVEL_REASONING_PROVIDER:"local"};return {CERVEL_REASONING_PROVIDER:"openai-compatible",CERVEL_MODEL_BASE_URL:config.base_url,CERVEL_MODEL_NAME:config.model,CERVEL_MODEL_API_KEY:config.api_key??"",CERVEL_ALLOW_MODEL_NETWORK:String(config.allow_network)};}
  async ensureStarted():Promise<void>{if(await this.healthy())return;await this.runCli("start");for(let i=0;i<40;i++){if(await this.healthy())return;await wait(250);}throw new Error("LOCAL_NODE_START_TIMEOUT");}
  async healthy():Promise<boolean>{try{return (await fetch(`${this.url}/ready`,{signal:AbortSignal.timeout(1200)})).ok;}catch{return false;}}
  async status():Promise<Record<string,unknown>>{if(!this.root)return {open:false,running:false};const lifecycle=await this.runCli("status");return {...lifecycle,open:this.isOpen,healthy:await this.healthy(),url:this.url};}
  async lock():Promise<void>{if(this.root&&this.passphrase)await this.runCli("lock");this.forget();}
  private async readIdentity():Promise<BootstrapIdentity>{if(!this.root)throw new Error("VAULT_LOCKED");const raw=await readFile(join(this.root,"runtime","bootstrap.json"),"utf8"),parsed=JSON.parse(raw);return {nodeId:parsed.nodeId,workspaceId:parsed.workspaceId,principalId:parsed.principalId,storageLocationId:parsed.storageLocationId,authority:parsed.authority};}
  private async publishCaptureHost():Promise<void>{if(!this.unlocked||!this.identity)return;await atomicWrite(join(homedir(),".cervel","native-hosts","default.json"),JSON.stringify({format:"cervel-capture-host/v0.1",vault:"default",local_node_url:this.url,local_api_token:this.unlocked.secrets.local_api_token,node_id:this.identity.nodeId,workspace_id:this.identity.workspaceId,principal_id:this.identity.principalId,storage_location_id:this.identity.storageLocationId})+"\n",0o600);}
  async request(path:string,init:{method?:string;body?:unknown}={}):Promise<any>{if(!this.unlocked||!this.identity)throw new Error("VAULT_LOCKED");const response=await fetch(`${this.url}${path}`,{method:init.method??"GET",headers:{"content-type":"application/json","x-cervel-local-token":this.unlocked.secrets.local_api_token,"x-cervel-principal-id":this.identity.principalId},body:init.body===undefined?undefined:JSON.stringify(init.body),signal:AbortSignal.timeout(30000)});const text=await response.text();let payload:any;try{payload=text?JSON.parse(text):null;}catch{payload={error:text};}if(!response.ok)throw new Error(payload?.error??`LOCAL_NODE_HTTP_${response.status}`);return payload;}
  async ingestFile(path:string):Promise<any>{const bytes=await readFile(path),title=basename(path),object=await this.request("/v1/objects",{method:"POST",body:{node_id:this.identity!.nodeId,workspace_id:this.identity!.workspaceId,type:"document",title}});const artifact=await this.request(`/v1/objects/${object.id}/artifacts`,{method:"POST",body:{storage_location_id:this.identity!.storageLocationId,filename:title,mime_type:contentTypes[extname(path).toLowerCase()]??"application/octet-stream",content_base64:bytes.toString("base64")}});return {object,artifact};}
  async createNote(title:string,content:string):Promise<any>{const object=await this.request("/v1/objects",{method:"POST",body:{node_id:this.identity!.nodeId,workspace_id:this.identity!.workspaceId,type:"note",title,summary:content.slice(0,280)}});const artifact=await this.request(`/v1/objects/${object.id}/artifacts`,{method:"POST",body:{storage_location_id:this.identity!.storageLocationId,filename:`${title.replace(/[^a-z0-9_-]+/gi,"-")}.md`,mime_type:"text/markdown",content_base64:Buffer.from(content).toString("base64")}});return {object,artifact};}
  async listObjects(type?:string,q?:string):Promise<any>{const params=new URLSearchParams({node_id:this.identity!.nodeId});if(type)params.set("type",type);if(q)params.set("q",q);return this.request(`/v1/local/objects?${params}`);}
  async overview():Promise<any>{return this.request("/v1/local/overview");}
  async graph():Promise<any>{return this.request(`/v1/local/graph?node_id=${encodeURIComponent(this.identity!.nodeId)}`);}
  async search(query:string):Promise<any>{return this.request("/v1/search",{method:"POST",body:{node_id:this.identity!.nodeId,workspace_id:this.identity!.workspaceId,query}});}
  async ask(query:string):Promise<any>{return this.request("/v1/reason",{method:"POST",body:{node_id:this.identity!.nodeId,workspace_id:this.identity!.workspaceId,query}});}
  async trace(answerId:string):Promise<any>{return this.request(`/v1/answers/${encodeURIComponent(answerId)}/trace`);}
  async operation(command:"backup"|"vault-verify"|"restore",input?:string):Promise<any>{if(command==="vault-verify")return this.runCli("vault",["verify"]);if(command==="restore")return this.runCli("restore",["--from",String(input)]);return this.runCli(command);}
  async getProviderConfiguration():Promise<ProviderConfiguration>{if(!this.root||!this.unlocked)throw new Error("VAULT_LOCKED");try{return JSON.parse(decryptBuffer(await readFile(join(this.root,"private","desktop-provider.cvlt")),this.unlocked.artifactKey).toString("utf8"));}catch{return {provider:"local",base_url:"http://127.0.0.1:11434",model:"",allow_network:false};}}
  async setProviderConfiguration(config:ProviderConfiguration):Promise<ProviderConfiguration>{if(!this.root||!this.unlocked)throw new Error("VAULT_LOCKED");let parsed:URL;try{parsed=new URL(config.base_url);}catch{throw new Error("PROVIDER_URL_INVALID");}const local=["localhost","127.0.0.1","::1"].includes(parsed.hostname);if(!config.allow_network&&!local&&config.provider!=="local")throw new Error("REMOTE_PROVIDER_REQUIRES_NETWORK_PERMISSION");const previous=await this.getProviderConfiguration(),saved={...config,api_key:config.api_key||previous.api_key};await atomicWrite(join(this.root,"private","desktop-provider.cvlt"),encryptBuffer(Buffer.from(JSON.stringify(saved)),this.unlocked.artifactKey));await this.runCli("lock");for(let i=0;i<20&&await this.healthy();i++)await wait(100);await this.ensureStarted();this.identity=await this.readIdentity();return {...saved,api_key:saved.api_key?"••••••••":undefined};}
  private async syncController(){if(this.cloudSync)return this.cloudSync;if(!this.root||!this.passphrase)throw new Error("VAULT_LOCKED");this.cloudSync=await LocalCloudSyncController.load(this.root,this.passphrase);return this.cloudSync;}
  async cloudSyncAction(action:string,input:any={}):Promise<any>{if(!this.root||!this.passphrase)throw new Error("VAULT_LOCKED");if(action==="enable"){if(!input.relay_url)throw new Error("SYNC_RELAY_REQUIRED");this.cloudSync=await LocalCloudSyncController.enable(this.root,this.passphrase,input.relay_url);return this.cloudSync.status();}if(action==="status"){try{return (await this.syncController()).status();}catch(error:any){if(error?.code==="ENOENT")return {enabled:false};throw error;}}const controller=await this.syncController();if(action==="run")return controller.sync();if(action==="pause")return controller.pause(true);if(action==="resume")return controller.pause(false);if(action==="reset")return controller.reset();if(action==="backup")return controller.backup();if(action==="delete")return controller.deleteRemote(input.confirm_vault_id);if(action==="revoke")return controller.revoke(input.device_id);throw new Error("SYNC_ACTION_UNSUPPORTED");}
}

export async function discoverVaults(home:string):Promise<Array<{path:string;name:string;id:string;created_at:string}>>{const base=join(home,".cervel","vaults");let entries:string[]=[];try{entries=await readdir(base);}catch{return [];}const found=[];for(const name of entries){const path=join(base,name);try{if(!(await stat(path)).isDirectory())continue;const manifest=JSON.parse(await readFile(join(path,"vault.json"),"utf8"));found.push({path,name:manifest.name,id:manifest.id,created_at:manifest.created_at});}catch{}}return found.sort((a,b)=>b.created_at.localeCompare(a.created_at));}
