import { randomBytes } from "node:crypto";
import { CloudSyncEngine } from "../../packages/cloud-sync/src/engine";
import { createEnrollmentBundle,generateDeviceIdentity,openEnrollmentBundle } from "../../packages/cloud-sync/src/crypto";
import { InMemoryZeroKnowledgeRelay } from "../../packages/cloud-sync/src/relay";
import { compareVectors } from "../../packages/cloud-sync/src/protocol";

async function pair(){const relay=new InMemoryZeroKnowledgeRelay(),setup=CloudSyncEngine.newVault(relay),a=new CloudSyncEngine(setup.vaultId,setup.rootKey,setup.device,relay);await a.register();const device=generateDeviceIdentity(),bundle=createEnrollmentBundle(setup.rootKey,setup.vaultId,device.registration),opened=openEnrollmentBundle(bundle,device.encryption_private_key);expect(opened.equals(setup.rootKey)).toBe(true);await a.enrollDevice(device.registration);const b=new CloudSyncEngine(setup.vaultId,opened,device,relay);return {relay,a,b,setup,device};}

describe("CERVEL zero-knowledge Cloud Sync",()=>{
  test("version vectors distinguish causal and concurrent mutations",()=>{expect(compareVectors({a:1},{a:2})).toBe("before");expect(compareVectors({a:2},{a:1})).toBe("after");expect(compareVectors({a:1},{b:1})).toBe("concurrent");});
  test("two offline devices resolve conflicts deterministically and converge",async()=>{const {a,b}=await pair();a.put("cko:decision","cko",{title:"Local A",secret:"alpha"});b.put("cko:decision","cko",{title:"Local B",secret:"beta"});await a.sync();await b.sync();await a.sync();expect(a.get("cko:decision")).toEqual(b.get("cko:decision"));expect(a.state()).toEqual(b.state());expect(a.state().entities[0].conflicts).toHaveLength(1);});
  test("artifact chunks are Vault-scoped, deduplicated and resumably restorable",async()=>{const {relay,a,b,setup}=await pair(),bytes=Buffer.concat([randomBytes(700_000),Buffer.from("durable tail")]);a.attachArtifact("artifact:one",bytes);a.attachArtifact("artifact:two",bytes);await a.sync();const opaque=relay.inspectOpaque(setup.vaultId)!;expect(opaque.chunks).toHaveLength(1);expect(opaque.chunks[0]).toMatchObject({complete:true});await b.sync();expect((await b.restoreArtifact("artifact:one")).equals(bytes)).toBe(true);});
  test("relay metadata cannot reveal knowledge content or logical identifiers",async()=>{const {relay,a,setup}=await pair();a.put("cko:private-plan","note",{title:"Acquisition target",source_path:"/Users/yann/private.md"});await a.sync();const serialized=JSON.stringify(relay.inspectOpaque(setup.vaultId));expect(serialized).not.toContain("private-plan");expect(serialized).not.toContain("Acquisition target");expect(serialized).not.toContain("private.md");expect(serialized).not.toContain("note");});
  test("pause, reset, backup, revocation and complete remote deletion fail closed",async()=>{const {relay,a,b,setup,device}=await pair();a.pause();a.put("cko:offline","cko",{value:1});expect((await a.sync()).paused).toBe(true);a.pause(false);a.createRemoteBackup();await a.sync();await b.sync();expect(b.get("cko:offline")).toEqual({value:1});await b.reset();await b.sync();expect(b.get("cko:offline")).toEqual({value:1});await a.revokeDevice(device.registration.device_id);await expect(b.sync()).rejects.toThrow("SYNC_DEVICE_REVOKED");await a.deleteRemote();expect(relay.inspectOpaque(setup.vaultId)).toBeNull();await expect(a.sync()).resolves.toMatchObject({paused:true});});
  test("tampered enrollment bundles cannot disclose the client root key",async()=>{const device=generateDeviceIdentity(),bundle=createEnrollmentBundle(randomBytes(32),"vault",device.registration);bundle.ciphertext=bundle.ciphertext.slice(0,-2)+"aa";expect(()=>openEnrollmentBundle(bundle,device.encryption_private_key)).toThrow();});
  test("encrypted journal and materialized state survive a Local Node restart",async()=>{const {a,setup,relay}=await pair();a.put("cko:durable","cko",{value:"offline state"});await a.sync();const restarted=new CloudSyncEngine(setup.vaultId,setup.rootKey,setup.device,relay,a.persistence());expect(restarted.get("cko:durable")).toEqual({value:"offline state"});expect(restarted.state()).toEqual(a.state());});
  test("the relay refuses removal of the final recovery-capable device",async()=>{const relay=new InMemoryZeroKnowledgeRelay(),setup=CloudSyncEngine.newVault(relay),only=new CloudSyncEngine(setup.vaultId,setup.rootKey,setup.device,relay);await only.register();await expect(only.revokeDevice(setup.device.registration.device_id)).rejects.toThrow("SYNC_LAST_DEVICE_REQUIRED");});
});
