import {generateEmbodimentDeviceV2,createEnrollmentChallengeV2,sealSyncRootForDeviceV2,openSyncRootForDeviceV2} from "../../packages/cloud-sync/src/device-crypto";
import {newDeviceRegistryV2,enrollDeviceV2,revokeDeviceV2,rotateSessionsToEpoch,assertDeviceEpoch} from "../../packages/cloud-sync/src/device-registry";
const permissions=(vault:string)=>[{capability:"sync.read" as const,effect:"allow" as const,scope:{vault_id:vault}},{capability:"sync.write" as const,effect:"allow" as const,scope:{vault_id:vault}},{capability:"device.pair" as const,effect:"allow" as const,scope:{vault_id:vault}}];const caps=["sync.read","sync.write","device.pair"] as const;
const enroll=(device:ReturnType<typeof generateEmbodimentDeviceV2>)=>{const registry=newDeviceRegistryV2("vault_alpha"),challenge=createEnrollmentChallengeV2("vault_alpha","node_local",device.identity);return enrollDeviceV2(registry,device.identity,{request_id:challenge.request_id,authorizer_device_id:"dev_authorizer_12345678901234567890",authorizer_signature:"relay-authorized",permissions:permissions("vault_alpha")});};
describe("CERVEL Sync v2 device enrollment",()=>{
 it("binds Desktop Extension and Mobile to stable embodiment identities",()=>{for(const kind of ["desktop","browser_extension","mobile"] as const){const device=generateEmbodimentDeviceV2({kind,display_name:`CERVEL ${kind}`,capabilities:[...caps],requested_permissions:permissions("vault_alpha"),seed:kind});expect(device.identity.device_id).toMatch(/^dev_/);expect(device.identity.embodiment_id).toMatch(/^emb_/);expect(device.identity.kind).toBe(kind);expect(device.identity.key_fingerprint).toHaveLength(64);}});
 it("encrypts the sync root to one recipient and binds the approved grant",()=>{const root=Buffer.alloc(32,7),mobile=generateEmbodimentDeviceV2({kind:"mobile",display_name:"Phone",capabilities:[...caps],requested_permissions:permissions("vault_alpha"),seed:"phone"}),{grant}=enroll(mobile),bundle=sealSyncRootForDeviceV2(root,{vault_id:"vault_alpha",device:mobile.identity,sync_epoch:1,grant});expect(bundle.ciphertext).not.toContain(root.toString("base64url"));expect(openSyncRootForDeviceV2(bundle,mobile,grant)).toEqual(root);const tampered={...grant,approved_permissions:[{capability:"sync.read" as const,effect:"deny" as const,scope:{vault_id:"vault_alpha"}}]};expect(()=>openSyncRootForDeviceV2(bundle,mobile,tampered)).toThrow("ENROLLMENT_GRANT_DIGEST_MISMATCH");const other=generateEmbodimentDeviceV2({kind:"desktop",display_name:"Mac",capabilities:[...caps],requested_permissions:permissions("vault_alpha"),seed:"mac"});expect(()=>openSyncRootForDeviceV2(bundle,other,grant)).toThrow("ENROLLMENT_BUNDLE_BINDING_FAILURE");});
 it("prevents capability and permission-effect escalation",()=>{const requested=[{capability:"sync.read" as const,effect:"approval_required" as const,scope:{vault_id:"vault_alpha"}},{capability:"device.pair" as const,effect:"allow" as const,scope:{vault_id:"vault_alpha"}}],device=generateEmbodimentDeviceV2({kind:"browser_extension",display_name:"Extension",capabilities:[...caps],requested_permissions:requested,seed:"ext"}),registry=newDeviceRegistryV2("vault_alpha"),challenge=createEnrollmentChallengeV2("vault_alpha","node_local",device.identity);expect(()=>enrollDeviceV2(registry,device.identity,{request_id:challenge.request_id,authorizer_device_id:"dev_authorizer_12345678901234567890",authorizer_signature:"sig",permissions:[{capability:"sync.read",effect:"allow",scope:{vault_id:"vault_alpha"}}]})).toThrow("ENROLLMENT_PERMISSION_ESCALATION");});
 it("revocation advances the sync epoch and invalidates stale sessions",()=>{const device=generateEmbodimentDeviceV2({kind:"mobile",display_name:"Phone",capabilities:[...caps],requested_permissions:permissions("vault_alpha"),seed:"phone-2"}),enrolled=enroll(device).registry;expect(assertDeviceEpoch(enrolled,device.identity.device_id,1).identity.kind).toBe("mobile");const revoked=revokeDeviceV2(enrolled,device.identity.device_id);expect(revoked.sync_epoch).toBe(2);expect(()=>assertDeviceEpoch(revoked,device.identity.device_id,1)).toThrow("DEVICE_REVOKED_OR_UNKNOWN");expect(rotateSessionsToEpoch(revoked).sync_epoch).toBe(2);});
});
