import{createHash}from"node:crypto";import type{ClassificationInput,CorpusRule,TaxonomyNode}from"../../corpus-engine/src";import type{AuthorityState}from"../../semantic-kernel/src";
export const ENTERPRISE_CORPUS_VERSION="1.0"as const;
export type EnterpriseBranch={key:string;title:string;description:string;sensitivity:"internal"|"confidential"|"restricted";authority_default:AuthorityState;terms:string[];subtabs:string[]};
const b=(key:string,title:string,description:string,sensitivity:EnterpriseBranch["sensitivity"],authority_default:AuthorityState,terms:string[],subtabs:string[]):EnterpriseBranch=>({key,title,description,sensitivity,authority_default,terms,subtabs});
export const ENTERPRISE_BRANCHES:readonly EnterpriseBranch[]=[
 b("organization","Organization","Identity, structure, governance, locations, and organizational state.","internal","official",["organization","company","governance","structure","office"],["Identity","Structure","Governance","Locations","Policies"]),
 b("people","People","Employees, teams, roles, capabilities, and organizational relationships.","confidential","verified",["employee","people","team","role","hiring","talent"],["Directory","Teams","Roles","Hiring","Capabilities"]),
 b("strategy","Strategy","Mission, positioning, choices, objectives, and strategic plans.","confidential","approved",["strategy","mission","vision","objective","competitive","roadmap"],["Mission","Objectives","Plans","Analysis","Decisions"]),
 b("operations","Operations","Processes, workflows, service delivery, controls, and execution.","internal","verified",["operation","process","workflow","procedure","delivery","supply"],["Processes","Workflows","Controls","Vendors","Performance"]),
 b("projects","Projects","Initiatives, milestones, decisions, dependencies, and deliverables.","internal","approved",["project","milestone","deliverable","initiative","dependency","launch"],["Portfolio","Active","Planned","Completed","Decisions"]),
 b("products","Products","Products, services, requirements, releases, and product knowledge.","internal","verified",["product","service","feature","requirement","release","pricing"],["Portfolio","Requirements","Roadmaps","Releases","Feedback"]),
 b("customers","Customers","Accounts, needs, feedback, success, support, and customer history.","confidential","verified",["customer","client","account","support","success","feedback"],["Accounts","Needs","Success","Support","Feedback"]),
 b("sales","Sales","Pipeline, opportunities, proposals, contracts, and revenue execution.","confidential","verified",["sales","pipeline","lead","opportunity","proposal","deal"],["Pipeline","Accounts","Opportunities","Proposals","Forecasts"]),
 b("marketing","Marketing","Markets, campaigns, brand, content, channels, and performance.","internal","approved",["marketing","campaign","brand","content","audience","channel"],["Brand","Markets","Campaigns","Content","Analytics"]),
 b("finance","Finance","Budgets, accounting, revenue, costs, forecasts, and financial reporting.","restricted","official",["finance","budget","revenue","expense","accounting","forecast","invoice"],["Budget","Revenue","Costs","Reporting","Forecasts"]),
 b("legal-risk-compliance","Legal / Risk / Compliance","Contracts, obligations, controls, risks, audits, and regulatory knowledge.","restricted","official",["legal","risk","compliance","contract","audit","regulation","policy"],["Contracts","Risk","Compliance","Audits","Obligations"]),
 b("research","Research","Research programs, evidence, experiments, findings, and sources.","internal","verified",["research","study","evidence","experiment","finding","source"],["Programs","Evidence","Experiments","Findings","Sources"]),
 b("institutional-knowledge","Institutional Knowledge","Methods, standards, decisions, lessons, and reusable organizational know-how.","internal","approved",["institutional","method","standard","playbook","lesson","decision"],["Methods","Standards","Playbooks","Decisions","Lessons"]),
 b("technology","Technology","Architecture, systems, software, infrastructure, and technical operations.","restricted","verified",["technology","architecture","software","infrastructure","api","deployment","system"],["Architecture","Systems","Software","Infrastructure","Operations"]),
 b("data","Data","Datasets, schemas, lineage, quality, governance, and analytics.","restricted","verified",["data","dataset","schema","lineage","quality","analytics","warehouse"],["Catalog","Schemas","Lineage","Quality","Governance"]),
 b("ai-agents","AI / Agents","Models, agents, prompts, evaluations, tools, and AI governance.","restricted","approved",["ai","model","agent","prompt","evaluation","inference","embedding"],["Models","Agents","Prompts","Evaluations","Governance"]),
 b("enterprise-memory","Enterprise Memory","Events, decisions, transitions, incidents, and organizational history.","confidential","reported",["memory","history","incident","transition","retrospective","timeline"],["Timeline","Events","Decisions","Incidents","Retrospectives"]),
 b("external-ecosystem","External Ecosystem","Partners, suppliers, regulators, competitors, markets, and external dependencies.","confidential","reported",["partner","supplier","regulator","competitor","market","ecosystem"],["Partners","Suppliers","Regulators","Competitors","Markets"])
]as const;
export const ENTERPRISE_TAXONOMY:TaxonomyNode[]=ENTERPRISE_BRANCHES.map(x=>({key:x.key,title:x.title,tabs:[{key:"overview",title:"Overview",subtabs:x.subtabs}]}));
export const ENTERPRISE_RULES:CorpusRule[]=ENTERPRISE_BRANCHES.map(x=>({field:"topic",terms:x.terms,weight:.55,mega_tab:x.key,tab:"overview"}));
const narrative=(i:ClassificationInput)=>[i.type,i.title,i.summary,...(i.tags??[]),...(i.topics??[]),...(i.verticals??[]),...(i.intents??[])].filter(Boolean).join(" ").toLowerCase();
export function classifyEnterprise(input:ClassificationInput,threshold=.25){const text=narrative(input);return ENTERPRISE_BRANCHES.flatMap(branch=>{const hits=branch.terms.filter(term=>text.includes(term));if(!hits.length)return[];return[{mega_tab:branch.key,tab:"overview",subtab:null,confidence:Math.min(.99,Number((.25+hits.length*.12).toFixed(3))),reasons:hits.map(x=>`enterprise:${branch.key}:${x}`),sensitivity:branch.sensitivity,authority:"inferred"as AuthorityState,authority_target:branch.authority_default}];}).filter(x=>x.confidence>=threshold).sort((a,b)=>b.confidence-a.confidence||a.mega_tab.localeCompare(b.mega_tab));}
export function enterpriseBranch(key:string){const result=ENTERPRISE_BRANCHES.find(x=>x.key===key);if(!result)throw new Error("ENTERPRISE_BRANCH_NOT_FOUND");return result;}
export function enterprisePolicyDigest(){return createHash("sha256").update(JSON.stringify(ENTERPRISE_BRANCHES)).digest("hex");}
