import type { PoolClient } from "pg";
import { uuidv7 } from "./uuidv7";
import { assembleContextPackage } from "./context";

export type AgentPermission="memory:read"|"memory:write"|"claim:write"|"context:read"|"events:read"|"watch:read";
const permissions:AgentPermission[]=["memory:read","memory:write","claim:write","context:read","events:read","watch:read"];
const clamp=(value:number)=>Math.max(0,Math.min(1,value));
const ZERO_UUID="00000000-0000-0000-0000-000000000000";

export function validateAgentPermissions(values:string[]):AgentPermission[]{const unique=[...new Set(values)];if(unique.some(value=>!permissions.includes(value as AgentPermission)))throw Object.assign(new Error("INVALID_AGENT_PERMISSION"),{statusCode:400});return unique as AgentPermission[];}

export async function assertAgentProvisioner(client:PoolClient,principalId:string,nodeId:string){const row=await client.query(`SELECT 1 FROM principals WHERE id=$1 AND node_id=$2 AND attributes->>'role'='admin'`,[principalId,nodeId]);if(row.rowCount!==1)throw Object.assign(new Error("AGENT_PROVISIONING_FORBIDDEN"),{statusCode:403});}

export async function loadAgentScope(client:PoolClient,input:{principalId:string;nodeId:string;workspaceId:string;permission:AgentPermission}){const row=await client.query(`SELECT ai.*,g.permissions FROM agent_identities ai JOIN agent_workspace_grants g ON g.agent_id=ai.id AND g.node_id=ai.node_id JOIN workspaces w ON w.id=g.workspace_id AND w.node_id=g.node_id WHERE ai.principal_id=$1 AND ai.node_id=$2 AND ai.enabled=true AND g.workspace_id=$3`,[input.principalId,input.nodeId,input.workspaceId]);if(row.rowCount!==1)throw Object.assign(new Error("AGENT_WORKSPACE_FORBIDDEN"),{statusCode:403});if(!(row.rows[0].permissions as string[]).includes(input.permission))throw Object.assign(new Error("AGENT_PERMISSION_DENIED"),{statusCode:403});return row.rows[0];}

async function assertAgentSubjectScope(client:PoolClient,nodeId:string,workspaceId:string,subjectType:string,subjectId:string){let result;if(subjectType==="cko")result=await client.query(`SELECT 1 FROM knowledge_objects WHERE id=$1 AND node_id=$2 AND workspace_id=$3 AND lifecycle_status<>'deleted'`,[subjectId,nodeId,workspaceId]);else if(subjectType==="claim")result=await client.query(`SELECT 1 FROM claims c WHERE c.id=$1 AND c.node_id=$2 AND ((c.subject_type='cko' AND EXISTS(SELECT 1 FROM knowledge_objects ko WHERE ko.id=c.subject_id AND ko.node_id=$2 AND ko.workspace_id=$3 AND ko.lifecycle_status<>'deleted')) OR EXISTS(SELECT 1 FROM claim_evidence ce JOIN fragments f ON f.id=ce.fragment_id JOIN knowledge_objects ko ON ko.id=f.cko_id WHERE ce.claim_id=c.id AND ko.node_id=$2 AND ko.workspace_id=$3 AND ko.lifecycle_status<>'deleted'))`,[subjectId,nodeId,workspaceId]);else if(subjectType==="entity")result=await client.query(`SELECT 1 FROM entities e WHERE e.id=$1 AND e.node_id=$2 AND EXISTS(SELECT 1 FROM knowledge_objects ko WHERE ko.id=e.canonical_cko_id AND ko.workspace_id=$3 AND ko.node_id=$2 AND ko.lifecycle_status<>'deleted')`,[subjectId,nodeId,workspaceId]);else throw Object.assign(new Error("AGENT_SUBJECT_TYPE_UNSUPPORTED"),{statusCode:400});if(result.rowCount!==1)throw Object.assign(new Error("AGENT_SUBJECT_FORBIDDEN"),{statusCode:403});}

export async function writeAgentObservation(client:PoolClient,input:{principalId:string;nodeId:string;workspaceId:string;subjectType:string;subjectId:string;observation:string;confidence?:number;details?:Record<string,unknown>;claim?:{predicate:string;literalValue:unknown;epistemicStatus?:string}}){const agent=await loadAgentScope(client,{...input,permission:"memory:write"});if(!input.observation?.trim())throw Object.assign(new Error("OBSERVATION_REQUIRED"),{statusCode:400});await assertAgentSubjectScope(client,input.nodeId,input.workspaceId,input.subjectType,input.subjectId);let claimId:string|null=null;if(input.claim){if(!(agent.permissions as string[]).includes("claim:write"))throw Object.assign(new Error("AGENT_CLAIM_PERMISSION_DENIED"),{statusCode:403});if(!input.claim.predicate?.trim())throw Object.assign(new Error("CLAIM_PREDICATE_REQUIRED"),{statusCode:400});claimId=uuidv7();await client.query(`INSERT INTO claims(id,node_id,subject_type,subject_id,predicate,object_kind,literal_value,literal_datatype,qualifiers,epistemic_status,confidence,created_by) VALUES($1,$2,$3,$4,$5,'literal',$6::jsonb,'application/json',$7::jsonb,$8,$9,$10)`,[claimId,input.nodeId,input.subjectType,input.subjectId,input.claim.predicate.trim(),JSON.stringify(input.claim.literalValue),JSON.stringify({workspace_id:input.workspaceId,agent_id:agent.id,source:"agent_runtime"}),input.claim.epistemicStatus??"claimed",clamp(input.confidence??.7),input.principalId]);}const id=uuidv7();const result=await client.query(`INSERT INTO agent_observations(id,agent_id,node_id,workspace_id,subject_type,subject_id,observation,confidence,details,created_claim_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb,$10) RETURNING *`,[id,agent.id,input.nodeId,input.workspaceId,input.subjectType,input.subjectId,input.observation.trim(),clamp(input.confidence??.7),JSON.stringify(input.details??{}),claimId]);return result.rows[0];}

export async function buildAgentContext(client:PoolClient,input:{principalId:string;nodeId:string;workspaceId:string;query:string;taskType?:string;profile?:string;maxEvidenceItems?:number}){await loadAgentScope(client,{...input,permission:"context:read"});if(!input.query?.trim())throw Object.assign(new Error("QUERY_REQUIRED"),{statusCode:400});return assembleContextPackage(client,{nodeId:input.nodeId,workspaceId:input.workspaceId,principalId:input.principalId,query:input.query.trim(),taskType:input.taskType,profile:input.profile,asOf:null,libraryIds:[],maxEvidenceItems:input.maxEvidenceItems});}

export async function createAgentSubscription(client:PoolClient,input:{principalId:string;nodeId:string;workspaceId:string;watchId?:string|null;eventTypes?:string[];impactKinds?:string[];minConfidence?:number}){const agent=await loadAgentScope(client,{...input,permission:"events:read"});if(input.watchId){if(!(agent.permissions as string[]).includes("watch:read"))throw Object.assign(new Error("AGENT_WATCH_PERMISSION_DENIED"),{statusCode:403});const watch=await client.query(`SELECT 1 FROM knowledge_watches WHERE id=$1 AND node_id=$2 AND workspace_id=$3 AND principal_id=$4 AND enabled=true`,[input.watchId,input.nodeId,input.workspaceId,input.principalId]);if(watch.rowCount!==1)throw Object.assign(new Error("AGENT_WATCH_NOT_FOUND"),{statusCode:404});}const id=uuidv7();const row=await client.query(`INSERT INTO agent_subscriptions(id,agent_id,node_id,workspace_id,watch_id,event_types,impact_kinds,min_confidence) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *`,[id,agent.id,input.nodeId,input.workspaceId,input.watchId??null,input.eventTypes??[],input.impactKinds??[],clamp(input.minConfidence??.55)]);return row.rows[0];}

export async function pollAgentSignals(client:PoolClient,input:{principalId:string;nodeId:string;workspaceId:string;subscriptionId:string;limit?:number}){const agent=await loadAgentScope(client,{...input,permission:"events:read"});const subResult=await client.query(`SELECT * FROM agent_subscriptions WHERE id=$1 AND agent_id=$2 AND node_id=$3 AND workspace_id=$4 AND enabled=true`,[input.subscriptionId,agent.id,input.nodeId,input.workspaceId]);if(subResult.rowCount!==1)throw Object.assign(new Error("AGENT_SUBSCRIPTION_NOT_FOUND"),{statusCode:404});const sub=subResult.rows[0],limit=Math.max(1,Math.min(100,input.limit??30));const canReadWatch=(agent.permissions as string[]).includes("watch:read");const signals=await client.query(`WITH signals AS (SELECT ke.id AS event_id,NULL::uuid AS alert_id,ke.observed_at AS occurred_at,ke.event_type,ke.subject_type,ke.subject_id,ke.confidence,ke.summary,ke.details,NULL::text AS severity,NULL::jsonb AS why_now FROM knowledge_events ke WHERE ke.node_id=$1 AND ke.workspace_id=$2 AND ke.observed_at >= $3 AND ke.confidence >= $4 AND (cardinality($5::text[])=0 OR ke.event_type=ANY($5::text[])) AND (cardinality($6::text[])=0 OR EXISTS(SELECT 1 FROM knowledge_event_impacts kei WHERE kei.event_id=ke.id AND kei.impact_kind=ANY($6::text[]))) UNION ALL SELECT wa.event_id,wa.id AS alert_id,wa.surfaced_at AS occurred_at,ke.event_type,ke.subject_type,ke.subject_id,ke.confidence,wa.title AS summary,ke.details,wa.severity,wa.why_now FROM watch_alerts wa JOIN knowledge_events ke ON ke.id=wa.event_id WHERE $7::boolean=true AND wa.node_id=$1 AND wa.workspace_id=$2 AND wa.principal_id=$8 AND wa.surfaced_at >= $3 AND ($9::uuid IS NULL OR wa.watch_id=$9) AND (cardinality($5::text[])=0 OR ke.event_type=ANY($5::text[])) AND (cardinality($6::text[])=0 OR EXISTS(SELECT 1 FROM knowledge_event_impacts kei WHERE kei.event_id=ke.id AND kei.impact_kind=ANY($6::text[])))) SELECT * FROM signals WHERE (occurred_at,event_id,COALESCE(alert_id,$10::uuid)) > ($3,$11::uuid,$12::uuid) ORDER BY occurred_at ASC,event_id ASC,alert_id ASC NULLS FIRST LIMIT $13`,[input.nodeId,input.workspaceId,sub.cursor_at,sub.min_confidence,sub.event_types,sub.impact_kinds,canReadWatch,input.principalId,sub.watch_id,ZERO_UUID,sub.cursor_event_id,sub.cursor_alert_id,limit]);for(const signal of signals.rows)await client.query(`INSERT INTO agent_delivery_receipts(id,subscription_id,agent_id,event_id,alert_id) VALUES($1,$2,$3,$4,$5) ON CONFLICT DO NOTHING`,[uuidv7(),sub.id,agent.id,signal.event_id,signal.alert_id]);if(signals.rows.length){const last=signals.rows[signals.rows.length-1];await client.query(`UPDATE agent_subscriptions SET cursor_at=$2,cursor_event_id=$3,cursor_alert_id=$4 WHERE id=$1`,[sub.id,last.occurred_at,last.event_id,last.alert_id??ZERO_UUID]);}return signals.rows;}
