import type { FastifyInstance } from "fastify";
import { withTransaction } from "./db";
import { assertPrincipalInNode } from "./access";
import { uuidv7 } from "./uuidv7";
import { buildAgentContext,loadAgentScope,pollAgentSignals,writeAgentObservation } from "./agent-runtime";

function principal(request:any){const value=request.headers["x-cervel-principal-id"];if(typeof value!=="string"||!value)throw Object.assign(new Error("X-CERVEL-PRINCIPAL-ID is required"),{statusCode:401});return value;}

export function registerAgentRoutes(app:FastifyInstance){
  app.post("/v1/agents",async(request,reply)=>{const p=principal(request),body=request.body as any;const row=await withTransaction(async client=>{await assertPrincipalInNode(client,p,body.node_id);const id=uuidv7();return client.query(`INSERT INTO agent_identities(id,node_id,principal_id,name,kind,provider,external_key,description,capabilities,metadata) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10::jsonb) RETURNING *`,[id,body.node_id,body.principal_id,body.name,body.kind??"internal",body.provider??null,body.external_key??null,body.description??null,body.capabilities??[],JSON.stringify(body.metadata??{})]);});return reply.code(201).send(row.rows[0]);});
  app.post("/v1/agents/:id/grants",async(request,reply)=>{const p=principal(request),{id}=request.params as {id:string},body=request.body as any;const row=await withTransaction(async client=>{await assertPrincipalInNode(client,p,body.node_id);const agent=await client.query(`SELECT 1 FROM agent_identities WHERE id=$1 AND node_id=$2`,[id,body.node_id]);if(agent.rowCount!==1)throw Object.assign(new Error("AGENT_NOT_FOUND"),{statusCode:404});return client.query(`INSERT INTO agent_workspace_grants(agent_id,node_id,workspace_id,permissions,created_by) VALUES($1,$2,$3,$4,$5) ON CONFLICT(agent_id,workspace_id) DO UPDATE SET permissions=EXCLUDED.permissions RETURNING *`,[id,body.node_id,body.workspace_id,body.permissions??[],p]);});return reply.code(201).send(row.rows[0]);});
  app.get("/v1/agent/session",async(request,reply)=>{const p=principal(request),q=request.query as any;const agent=await withTransaction(client=>loadAgentScope(client,{principalId:p,nodeId:q.node_id,workspaceId:q.workspace_id,permission:"memory:read"}));return reply.send({agent_id:agent.id,node_id:agent.node_id,workspace_id:q.workspace_id,permissions:agent.permissions,capabilities:agent.capabilities});});
  app.post("/v1/agent/observations",async(request,reply)=>{const p=principal(request),body=request.body as any;const result=await withTransaction(client=>writeAgentObservation(client,{principalId:p,nodeId:body.node_id,workspaceId:body.workspace_id,subjectType:body.subject_type,subjectId:body.subject_id,observation:body.observation,confidence:body.confidence,details:body.details,claim:body.claim}));return reply.code(201).send(result);});
  app.get("/v1/agent/observations",async(request,reply)=>{const p=principal(request),q=request.query as any;const rows=await withTransaction(async client=>{const agent=await loadAgentScope(client,{principalId:p,nodeId:q.node_id,workspaceId:q.workspace_id,permission:"memory:read"});return client.query(`SELECT * FROM agent_observations WHERE agent_id=$1 AND node_id=$2 AND workspace_id=$3 ORDER BY created_at DESC LIMIT $4`,[agent.id,q.node_id,q.workspace_id,Math.max(1,Math.min(100,Number(q.limit??30)))]);});return reply.send({observations:rows.rows});});
  app.post("/v1/agent/context",async(request,reply)=>{const p=principal(request),body=request.body as any;const result=await withTransaction(client=>buildAgentContext(client,{principalId:p,nodeId:body.node_id,workspaceId:body.workspace_id,query:body.query,taskType:body.task_type,profile:body.profile,maxEvidenceItems:body.max_evidence_items}));return reply.code(201).send(result);});
  app.post("/v1/agent/subscriptions",async(request,reply)=>{const p=principal(request),body=request.body as any;const row=await withTransaction(async client=>{const agent=await loadAgentScope(client,{principalId:p,nodeId:body.node_id,workspaceId:body.workspace_id,permission:"events:read"});const id=uuidv7();return client.query(`INSERT INTO agent_subscriptions(id,agent_id,node_id,workspace_id,watch_id,event_types,impact_kinds,min_confidence) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *`,[id,agent.id,body.node_id,body.workspace_id,body.watch_id??null,body.event_types??[],body.impact_kinds??[],Math.max(0,Math.min(1,body.min_confidence??.55))]);});return reply.code(201).send(row.rows[0]);});
  app.get("/v1/agent/subscriptions/:id/signals",async(request,reply)=>{const p=principal(request),{id}=request.params as {id:string},q=request.query as any;const signals=await withTransaction(client=>pollAgentSignals(client,{principalId:p,nodeId:q.node_id,workspaceId:q.workspace_id,subscriptionId:id,limit:Number(q.limit??30)}));return reply.send({signals});});
  app.post("/v1/agent/deliveries/:id/ack",async(request,reply)=>{const p=principal(request),{id}=request.params as {id:string};const row=await withTransaction(async client=>client.query(`UPDATE agent_delivery_receipts r SET acknowledged_at=now() FROM agent_identities a WHERE r.id=$1 AND r.agent_id=a.id AND a.principal_id=$2 RETURNING r.*`,[id,p]));if(row.rowCount!==1)return reply.code(404).send({error:"AGENT_DELIVERY_NOT_FOUND"});return reply.send(row.rows[0]);});
}
