import type { FastifyInstance,FastifyRequest } from "fastify";
import { withTransaction } from "./db";
import { assertPrincipalInNode } from "./access";
import { createKnowledgeObject } from "./objects";
import { registerArtifact } from "./artifacts";
import { ingestTextArtifact } from "./ingestion";
import { embedMissingFragments } from "./embeddings";
import { appendProvenanceEvent } from "./provenance";
import { uuidv7 } from "./uuidv7";
import { evidenceHashes,validateEvidence,type BrowserEvidence } from "../../../packages/capture-extension/src";

function principal(request:FastifyRequest){const value=request.headers["x-cervel-principal-id"];if(typeof value!=="string"||!value)throw Object.assign(new Error("LOCAL_PRINCIPAL_REQUIRED"),{statusCode:401});return value;}

export function registerCaptureRoutes(app:FastifyInstance){
  app.post("/v1/local/captures",async(request,reply)=>{const principalId=principal(request),raw=request.body as BrowserEvidence&{node_id:string;workspace_id:string;storage_location_id:string},evidence=validateEvidence(raw),hashes=evidenceHashes(evidence);const result=await withTransaction(async client=>{
    await assertPrincipalInNode(client,principalId,raw.node_id);const workspace=await client.query(`SELECT 1 FROM workspaces WHERE id=$1 AND node_id=$2`,[raw.workspace_id,raw.node_id]);if(workspace.rowCount!==1)throw Object.assign(new Error("CAPTURE_WORKSPACE_SCOPE_INVALID"),{statusCode:403});await client.query(`SELECT pg_advisory_xact_lock(hashtextextended($1,0))`,[hashes.fingerprint]);
    const duplicate=await client.query(`SELECT bc.id,bc.cko_id,bc.capture_job_id,ko.title FROM browser_captures bc JOIN knowledge_objects ko ON ko.id=bc.cko_id WHERE bc.node_id=$1 AND bc.workspace_id=$2 AND bc.fingerprint=$3`,[raw.node_id,raw.workspace_id,hashes.fingerprint]);if(duplicate.rowCount)return {duplicate:true,...duplicate.rows[0]};
    const node=await client.query(`SELECT slug FROM nodes WHERE id=$1`,[raw.node_id]),jobId=uuidv7();await client.query(`INSERT INTO capture_jobs(id,node_id,workspace_id,principal_id,source_type,status,filename,source_url,mime_type,metadata) VALUES($1,$2,$3,$4,$5,'processing',$6,$7,$8,$9::jsonb)`,[jobId,raw.node_id,raw.workspace_id,principalId,evidence.capture_type,evidence.title,evidence.source_url,evidence.mime_type,JSON.stringify({request_id:evidence.request_id,trust:"untrusted_web_content"})]);
    const object=await createKnowledgeObject(client,{nodeId:raw.node_id,workspaceId:raw.workspace_id,type:"web_evidence",title:evidence.title,summary:evidence.user.note??`Captured ${evidence.capture_type} from ${new URL(evidence.canonical_url).hostname}`,createdBy:principalId,nodeAuthority:node.rows[0].slug});
    const artifactPayload=Buffer.from(JSON.stringify({format:CAPTURE_ARCHIVE_FORMAT,evidence:{...evidence,content_base64:evidence.content_base64?"[binary artifact]":undefined},content:evidence.content_base64?undefined:evidence.content_text},null,2));
    const artifact=await registerArtifact(client,{nodeId:raw.node_id,ckoId:object.id,storageLocationId:raw.storage_location_id,role:"original",mimeType:"application/vnd.cervel.browser-evidence+json",filename:`capture-${evidence.request_id}.json`,bytes:artifactPayload,actorPrincipalId:principalId});
    const ingestion=await ingestTextArtifact(client,{nodeId:raw.node_id,ckoId:object.id,artifactId:artifact.id,mimeType:"application/json",bytes:artifactPayload,actorPrincipalId:principalId});if(ingestion.ingested)await embedMissingFragments(client,raw.node_id,object.id);let binaryArtifact:null|Awaited<ReturnType<typeof registerArtifact>>=null;if(evidence.content_base64){binaryArtifact=await registerArtifact(client,{nodeId:raw.node_id,ckoId:object.id,storageLocationId:raw.storage_location_id,role:"snapshot",mimeType:evidence.mime_type,filename:`capture-${evidence.request_id}.${evidence.capture_type==="image"?"png":"bin"}`,bytes:hashes.content,actorPrincipalId:principalId});}
    const captureId=uuidv7(),source={canonical_url:evidence.canonical_url,source_url:evidence.source_url,source_origin:new URL(evidence.source_url).origin,author:evidence.author??null,published_at:evidence.published_at??null,captured_at:evidence.captured_at,trust:"untrusted_web_content",instruction_policy:"never_execute"};await client.query(`INSERT INTO browser_captures(id,node_id,workspace_id,principal_id,cko_id,capture_job_id,capture_type,canonical_url,source_url,source_origin,author,published_at,captured_at,fingerprint,content_sha256,tags,capture_intent,project_ref,provenance) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19::jsonb)`,[captureId,raw.node_id,raw.workspace_id,principalId,object.id,jobId,evidence.capture_type,evidence.canonical_url,evidence.source_url,source.source_origin,evidence.author??null,evidence.published_at??null,evidence.captured_at,hashes.fingerprint,hashes.content_sha256,evidence.user.tags??[],evidence.user.capture_intent??null,evidence.user.project_ref??null,JSON.stringify({...source,acquisition:evidence.provenance})]);
    const outputs=[{resourceType:"cko" as const,resourceId:object.id},{resourceType:"artifact" as const,resourceId:artifact.id,sha256:artifact.sha256},...(binaryArtifact?[{resourceType:"artifact" as const,resourceId:binaryArtifact.id,sha256:binaryArtifact.sha256}]:[])],provenanceEventId=await appendProvenanceEvent(client,{nodeId:raw.node_id,eventType:"browser_evidence_captured",actorType:"human",actorPrincipalId:principalId,outputs,source,parameters:{capture_type:evidence.capture_type,tags:evidence.user.tags??[],capture_intent:evidence.user.capture_intent??null,content_sha256:hashes.content_sha256}});await client.query(`UPDATE capture_jobs SET status='ready',cko_id=$2,completed_at=now(),updated_at=now() WHERE id=$1`,[jobId,object.id]);return {duplicate:false,id:captureId,job_id:jobId,cko_id:object.id,canonical_uri:object.canonical_uri,artifact_id:artifact.id,binary_artifact_id:binaryArtifact?.id??null,provenance_event_id:provenanceEventId};
  });return reply.code(result.duplicate?200:201).send(result);});
  app.get("/v1/local/captures/:id",async(request,reply)=>{const principalId=principal(request),{id}=request.params as {id:string};const row=await withTransaction(async client=>{const result=await client.query(`SELECT cj.id,cj.status,cj.error_message,cj.cko_id,cj.updated_at FROM capture_jobs cj WHERE cj.id=$1 AND cj.principal_id=$2`,[id,principalId]);if(result.rowCount!==1)throw Object.assign(new Error("CAPTURE_JOB_NOT_FOUND"),{statusCode:404});return result.rows[0];});return reply.send(row);});
}
const CAPTURE_ARCHIVE_FORMAT="cervel-browser-evidence/v0.1";
