import type { FastifyInstance } from "fastify";
import { withTransaction } from "./db";
import { assertPrincipalInNode } from "./access";
import { appendCkepEvent,createCkepSubscription,pollCkepSubscription,queryCkepEvents,replayCkepStream } from "./ckep-runtime";
import type { CkepEnvelope } from "../../../packages/ckep/src";

function principal(request:any){const value=request.headers["x-cervel-principal-id"];if(typeof value!=="string"||!value)throw Object.assign(new Error("X-CERVEL-PRINCIPAL-ID is required"),{statusCode:401});return value;}
async function assertWorkspace(client:any,nodeId:string,workspaceId:string){const row=await client.query(`SELECT 1 FROM workspaces WHERE id=$1 AND node_id=$2`,[workspaceId,nodeId]);if(row.rowCount!==1)throw Object.assign(new Error("WORKSPACE_NOT_FOUND"),{statusCode:404});}

export function registerCkepRoutes(app:FastifyInstance){
  app.post("/v1/ckep/events",async(request,reply)=>{const p=principal(request),body=request.body as {node_id:string;workspace_id:string;event:CkepEnvelope};const result=await withTransaction(async client=>{await assertPrincipalInNode(client,p,body.node_id);await assertWorkspace(client,body.node_id,body.workspace_id);return appendCkepEvent(client,{nodeId:body.node_id,workspaceId:body.workspace_id,principalId:p,envelope:body.event});});return reply.code(result.created?201:200).send(result);});
  app.get("/v1/ckep/events",async(request,reply)=>{const p=principal(request),q=request.query as {node_id?:string;workspace_id?:string;event_type?:string;subject_type?:string;subject_uri?:string;after_sequence?:string;limit?:string};if(!q.node_id||!q.workspace_id)return reply.code(400).send({error:"NODE_AND_WORKSPACE_REQUIRED"});const rows=await withTransaction(async client=>{await assertPrincipalInNode(client,p,q.node_id!);await assertWorkspace(client,q.node_id!,q.workspace_id!);return queryCkepEvents(client,{nodeId:q.node_id!,workspaceId:q.workspace_id!,eventTypes:q.event_type?[q.event_type]:undefined,subjectType:q.subject_type,subjectUri:q.subject_uri,afterSequence:q.after_sequence?Number(q.after_sequence):undefined,limit:q.limit?Number(q.limit):undefined});});return reply.send({events:rows});});
  app.get("/v1/ckep/replay",async(request,reply)=>{const p=principal(request),q=request.query as {node_id?:string;workspace_id?:string;from_sequence?:string;to_sequence?:string;limit?:string};if(!q.node_id||!q.workspace_id)return reply.code(400).send({error:"NODE_AND_WORKSPACE_REQUIRED"});const rows=await withTransaction(async client=>{await assertPrincipalInNode(client,p,q.node_id!);await assertWorkspace(client,q.node_id!,q.workspace_id!);return replayCkepStream(client,{nodeId:q.node_id!,workspaceId:q.workspace_id!,fromSequence:q.from_sequence?Number(q.from_sequence):undefined,toSequence:q.to_sequence?Number(q.to_sequence):undefined,limit:q.limit?Number(q.limit):undefined});});return reply.send({events:rows});});
  app.post("/v1/ckep/subscriptions",async(request,reply)=>{const p=principal(request),body=request.body as any;const sub=await withTransaction(async client=>{await assertPrincipalInNode(client,p,body.node_id);await assertWorkspace(client,body.node_id,body.workspace_id);return createCkepSubscription(client,{nodeId:body.node_id,workspaceId:body.workspace_id,principalId:p,name:body.name,eventTypes:body.event_types,subjectTypes:body.subject_types,subjectUris:body.subject_uris,minConfidence:body.min_confidence});});return reply.code(201).send(sub);});
  app.get("/v1/ckep/subscriptions/:id/events",async(request,reply)=>{const p=principal(request),{id}=request.params as {id:string},q=request.query as {node_id?:string;workspace_id?:string;limit?:string};if(!q.node_id||!q.workspace_id)return reply.code(400).send({error:"NODE_AND_WORKSPACE_REQUIRED"});const rows=await withTransaction(async client=>{await assertPrincipalInNode(client,p,q.node_id!);return pollCkepSubscription(client,{nodeId:q.node_id!,workspaceId:q.workspace_id!,principalId:p,subscriptionId:id,limit:q.limit?Number(q.limit):undefined});});return reply.send({events:rows});});
  app.post("/v1/ckep/deliveries/:id/ack",async(request,reply)=>{const p=principal(request),{id}=request.params as {id:string};const row=await withTransaction(async client=>client.query(`UPDATE ckep_delivery_receipts r SET acknowledged_at=COALESCE(r.acknowledged_at,now()) FROM ckep_subscriptions s WHERE r.id=$1 AND r.subscription_id=s.id AND s.principal_id=$2 RETURNING r.*`,[id,p]));if(row.rowCount!==1)return reply.code(404).send({error:"CKEP_DELIVERY_NOT_FOUND"});return reply.send(row.rows[0]);});
}
