import type { FastifyInstance, FastifyRequest } from "fastify";
import { assertPrincipalInNode } from "./access";
import { withTransaction } from "./db";
import { addManualMembership, classifyCko, createClassificationHook, createCustomCorpus, ensureBuiltinCorpora, getCkoMemberships, grantCorpusAccess, listCorpora, queryCorpusView, removeMembership } from "./corpus-engine";
import { corpusRuntimeEnvelope, runtimeCorpusViewKey } from "./corpus-runtime-view";
import { querySemanticViews } from "./corpus-semantic-views";
const principal=(r:FastifyRequest)=>{const p=r.headers["x-cervel-principal-id"];if(typeof p!=="string"||!p)throw Object.assign(new Error("X-CERVEL-PRINCIPAL-ID is required"),{statusCode:401});return p;};
export function registerCorpusRoutes(app:FastifyInstance){
 app.post("/v1/corpora/bootstrap",async(r,reply)=>{const p=principal(r),b=r.body as any;return reply.code(201).send(await withTransaction(async c=>{await assertPrincipalInNode(c,p,b.node_id);return ensureBuiltinCorpora(c,{nodeId:b.node_id,workspaceId:b.workspace_id,principalId:p});}));});
 app.get("/v1/corpora",async r=>{const p=principal(r),q=r.query as any;return withTransaction(async c=>{await assertPrincipalInNode(c,p,q.node_id);await ensureBuiltinCorpora(c,{nodeId:q.node_id,workspaceId:q.workspace_id,principalId:p});return{corpora:await listCorpora(c,{nodeId:q.node_id,workspaceId:q.workspace_id,principalId:p})};});});
 app.get("/v1/corpora/:id",async r=>{const p=principal(r),q=r.query as any,id=(r.params as any).id;return withTransaction(async c=>{await assertPrincipalInNode(c,p,q.node_id);const corpora=await listCorpora(c,{nodeId:q.node_id,workspaceId:q.workspace_id,principalId:p}),corpus=corpora.find((x:any)=>x.id===id);if(!corpus)throw Object.assign(new Error("CORPUS_NOT_FOUND"),{statusCode:404});return corpus;});});
 app.get("/v1/corpora/:id/taxonomy",async r=>{const p=principal(r),q=r.query as any,id=(r.params as any).id;return withTransaction(async c=>{await assertPrincipalInNode(c,p,q.node_id);const corpora=await listCorpora(c,{nodeId:q.node_id,workspaceId:q.workspace_id,principalId:p}),corpus=corpora.find((x:any)=>x.id===id);if(!corpus)throw Object.assign(new Error("CORPUS_NOT_FOUND"),{statusCode:404});return{corpus_id:corpus.id,corpus_key:corpus.corpus_key,title:corpus.title,taxonomy:corpus.taxonomy};});});
 app.get("/v1/corpus-runtime",async r=>{const p=principal(r),q=r.query as any;return withTransaction(async c=>{await assertPrincipalInNode(c,p,q.node_id);await ensureBuiltinCorpora(c,{nodeId:q.node_id,workspaceId:q.workspace_id,principalId:p});const corpora=await listCorpora(c,{nodeId:q.node_id,workspaceId:q.workspace_id,principalId:p});return{views:corpora.filter((x:any)=>x.built_in).map((x:any)=>({view:x.corpus_key,corpus_id:x.id,title:x.title,visibility:x.visibility,taxonomy:x.taxonomy})),switch_semantics:"read-only-canonical-cko-projection",duplication_policy:"canonical-cko-references-only"};});});
 app.get("/v1/corpus-runtime/:view/semantic-views",async r=>{const p=principal(r),q=r.query as any,view=runtimeCorpusViewKey((r.params as any).view);return withTransaction(async c=>{await assertPrincipalInNode(c,p,q.node_id);return querySemanticViews(c,{nodeId:q.node_id,workspaceId:q.workspace_id,principalId:p,view});});});
 app.get("/v1/corpus-runtime/:view",async r=>{const p=principal(r),q=r.query as any,view=runtimeCorpusViewKey((r.params as any).view);return withTransaction(async c=>{await assertPrincipalInNode(c,p,q.node_id);const result=await queryCorpusView(c,{nodeId:q.node_id,workspaceId:q.workspace_id,principalId:p,corpusKey:view,megaTab:q.mega_tab,tab:q.tab,subtab:q.subtab,limit:q.limit?Number(q.limit):undefined});return{engine_version:result.engine_version,...corpusRuntimeEnvelope(view,result.objects)};});});
 app.post("/v1/corpora",async(r,reply)=>{const p=principal(r),b=r.body as any;return reply.code(201).send(await withTransaction(async c=>{await assertPrincipalInNode(c,p,b.node_id);return createCustomCorpus(c,{nodeId:b.node_id,workspaceId:b.workspace_id,principalId:p,key:b.key,title:b.title,description:b.description,visibility:b.visibility,taxonomy:b.taxonomy,rules:b.rules,extensionOfId:b.extension_of_id});}));});
 app.post("/v1/corpora/:id/hooks",async(r,reply)=>{const p=principal(r),b=r.body as any;return reply.code(201).send(await withTransaction(c=>createClassificationHook(c,{corpusId:(r.params as any).id,principalId:p,name:b.name,eventType:b.event_type,matcher:b.matcher,targetCoordinate:b.target_coordinate,minimumConfidence:b.minimum_confidence})));});
 app.put("/v1/corpora/:id/grants/:principalId",async r=>{const p=principal(r),b=r.body as any,params=r.params as any;return withTransaction(c=>grantCorpusAccess(c,{corpusId:params.id,actorPrincipalId:p,principalId:params.principalId,accessLevel:b.access_level}));});
 app.post("/v1/corpora/classify/:ckoId",async(r,reply)=>{const p=principal(r),b=r.body as any;return reply.code(201).send(await withTransaction(async c=>{await assertPrincipalInNode(c,p,b.node_id);return classifyCko(c,{nodeId:b.node_id,workspaceId:b.workspace_id,principalId:p,ckoId:(r.params as any).ckoId,triggerEvent:b.trigger_event,accept:b.accept});}));});
 app.post("/v1/corpora/:id/memberships",async(r,reply)=>{const p=principal(r),b=r.body as any;return reply.code(201).send(await withTransaction(c=>addManualMembership(c,{corpusId:(r.params as any).id,ckoId:b.cko_id,principalId:p,megaTab:b.mega_tab,tab:b.tab,subtab:b.subtab,confidence:b.confidence})));});
 app.get("/v1/corpora/memberships/:ckoId",async r=>{const p=principal(r),q=r.query as any;return withTransaction(async c=>{await assertPrincipalInNode(c,p,q.node_id);return{memberships:await getCkoMemberships(c,{nodeId:q.node_id,workspaceId:q.workspace_id,principalId:p,ckoId:(r.params as any).ckoId})};});});
 app.delete("/v1/corpora/memberships/:membershipId",async r=>{const p=principal(r),b=(r.body??{}) as any;return withTransaction(c=>removeMembership(c,{membershipId:(r.params as any).membershipId,principalId:p,reason:b.reason}));});
 app.get("/v1/corpus-view",async r=>{const p=principal(r),q=r.query as any;return withTransaction(async c=>{await assertPrincipalInNode(c,p,q.node_id);return queryCorpusView(c,{nodeId:q.node_id,workspaceId:q.workspace_id,principalId:p,corpusKey:q.corpus_key,megaTab:q.mega_tab,tab:q.tab,subtab:q.subtab,limit:q.limit?Number(q.limit):undefined});});});
}
