import { createHash } from "node:crypto";
import type { PoolClient } from "pg";
import { uuidv7 } from "./uuidv7";
import { BUILTIN_CORPORA, CORPUS_ENGINE_VERSION, classifyForCorpora, validateCorpusDefinition, type ClassificationInput, type CorpusDefinition, type CorpusVisibility } from "../../../packages/corpus-engine/src";
import { LIFE_RULES, LIFE_TAXONOMY } from "../../../packages/life-corpus/src";
import { ENTERPRISE_RULES, ENTERPRISE_TAXONOMY } from "../../../packages/enterprise-corpus/src";

const digest = (value: unknown) => createHash("sha256").update(JSON.stringify(value)).digest("hex");
async function workspaceScope(c: PoolClient, nodeId: string, workspaceId: string) { const r=await c.query(`SELECT 1 FROM workspaces WHERE id=$1 AND node_id=$2`,[workspaceId,nodeId]); if(r.rowCount!==1) throw Object.assign(new Error("CORPUS_WORKSPACE_SCOPE_INVALID"),{statusCode:404}); }
const visible = (alias="cd") => `(${alias}.visibility IN ('public','node') OR ${alias}.owner_principal_id=$3 OR EXISTS(SELECT 1 FROM corpus_access_grants cag WHERE cag.corpus_id=${alias}.id AND cag.principal_id=$3))`;

export async function ensureBuiltinCorpora(c:PoolClient,input:{nodeId:string;workspaceId:string;principalId:string}){
  await workspaceScope(c,input.nodeId,input.workspaceId);const rows=[];
  for(const base of BUILTIN_CORPORA){
    const def:CorpusDefinition=base.key==="life"?{...base,taxonomy:LIFE_TAXONOMY,rules:LIFE_RULES}:base.key==="enterprise"?{...base,taxonomy:ENTERPRISE_TAXONOMY,rules:ENTERPRISE_RULES}:base;
    if(def.key==="life"||def.key==="enterprise"){
      const table=def.key==="life"?"life_corpus_branch_policies":"enterprise_branch_policies";
      const installed=await c.query(`SELECT cd.* FROM corpus_definitions cd WHERE cd.node_id=$1 AND cd.workspace_id=$2 AND cd.corpus_key=$3 AND EXISTS(SELECT 1 FROM ${table} p WHERE p.corpus_id=cd.id)`,[input.nodeId,input.workspaceId,def.key]);
      if(installed.rowCount){
        const refreshed=await c.query(`UPDATE corpus_definitions SET title=$1,description=$2,taxonomy=$3::jsonb,classification_rules=$4::jsonb,updated_at=now() WHERE id=$5 RETURNING *`,[def.title,def.description,JSON.stringify(def.taxonomy),JSON.stringify(def.rules),installed.rows[0].id]);
        rows.push(refreshed.rows[0]);continue;
      }
    }
    const id=uuidv7(),r=await c.query(`INSERT INTO corpus_definitions(id,node_id,workspace_id,corpus_key,title,description,built_in,visibility,taxonomy,classification_rules,owner_principal_id) VALUES($1,$2,$3,$4,$5,$6,true,$7,$8::jsonb,$9::jsonb,$10) ON CONFLICT(node_id,workspace_id,corpus_key) DO UPDATE SET title=EXCLUDED.title,description=EXCLUDED.description,taxonomy=EXCLUDED.taxonomy,classification_rules=EXCLUDED.classification_rules,updated_at=now() RETURNING *`,[id,input.nodeId,input.workspaceId,def.key,def.title,def.description,def.visibility,JSON.stringify(def.taxonomy),JSON.stringify(def.rules),input.principalId]);rows.push(r.rows[0]);
  }
  return {engine_version:CORPUS_ENGINE_VERSION,corpora:rows};
}
export async function listCorpora(c:PoolClient,input:{nodeId:string;workspaceId:string;principalId:string}){await workspaceScope(c,input.nodeId,input.workspaceId);const r=await c.query(`SELECT cd.*,coalesce((SELECT count(*)::int FROM corpus_memberships cm WHERE cm.corpus_id=cd.id),0) membership_count FROM corpus_definitions cd WHERE cd.node_id=$1 AND cd.workspace_id=$2 AND cd.enabled=true AND ${visible()} ORDER BY cd.built_in DESC,cd.title`,[input.nodeId,input.workspaceId,input.principalId]);return r.rows;}
export async function createCustomCorpus(c:PoolClient,input:{nodeId:string;workspaceId:string;principalId:string;key:string;title:string;description:string;visibility:CorpusVisibility;taxonomy:CorpusDefinition["taxonomy"];rules?:CorpusDefinition["rules"];extensionOfId?:string|null}){
  await workspaceScope(c,input.nodeId,input.workspaceId);const def=validateCorpusDefinition({key:input.key,title:input.title,description:input.description,visibility:input.visibility,taxonomy:input.taxonomy,rules:input.rules??[]});
  if(input.extensionOfId){const parent=await c.query(`SELECT 1 FROM corpus_definitions WHERE id=$1 AND node_id=$2 AND workspace_id=$3`,[input.extensionOfId,input.nodeId,input.workspaceId]);if(parent.rowCount!==1)throw Object.assign(new Error("CORPUS_EXTENSION_PARENT_NOT_FOUND"),{statusCode:404});}
  const r=await c.query(`INSERT INTO corpus_definitions(id,node_id,workspace_id,corpus_key,title,description,built_in,extension_of_id,visibility,taxonomy,classification_rules,owner_principal_id) VALUES($1,$2,$3,$4,$5,$6,false,$7,$8,$9::jsonb,$10::jsonb,$11) RETURNING *`,[uuidv7(),input.nodeId,input.workspaceId,def.key,def.title,def.description,input.extensionOfId??null,def.visibility,JSON.stringify(def.taxonomy),JSON.stringify(def.rules),input.principalId]);return r.rows[0];
}
export async function createClassificationHook(c:PoolClient,input:{corpusId:string;principalId:string;name:string;eventType:string;matcher:Record<string,unknown>;targetCoordinate:{mega_tab:string;tab:string;subtab?:string};minimumConfidence?:number}){const corpus=await c.query(`SELECT * FROM corpus_definitions WHERE id=$1 AND (owner_principal_id=$2 OR EXISTS(SELECT 1 FROM corpus_access_grants WHERE corpus_id=$1 AND principal_id=$2 AND access_level='manage'))`,[input.corpusId,input.principalId]);if(corpus.rowCount!==1)throw Object.assign(new Error("CORPUS_MANAGE_FORBIDDEN"),{statusCode:403});const confidence=input.minimumConfidence??.5;if(confidence<0||confidence>1)throw Object.assign(new Error("CORPUS_HOOK_CONFIDENCE_INVALID"),{statusCode:400});const r=await c.query(`INSERT INTO corpus_classification_hooks(id,corpus_id,name,event_type,matcher,target_coordinate,minimum_confidence,created_by) VALUES($1,$2,$3,$4,$5::jsonb,$6::jsonb,$7,$8) RETURNING *`,[uuidv7(),input.corpusId,input.name,input.eventType,JSON.stringify(input.matcher),JSON.stringify(input.targetCoordinate),confidence,input.principalId]);return r.rows[0];}
export async function grantCorpusAccess(c:PoolClient,input:{corpusId:string;actorPrincipalId:string;principalId:string;accessLevel:"view"|"classify"|"manage"}){if(!["view","classify","manage"].includes(input.accessLevel))throw Object.assign(new Error("CORPUS_ACCESS_LEVEL_INVALID"),{statusCode:400});const allowed=await c.query(`SELECT 1 FROM corpus_definitions cd WHERE cd.id=$1 AND (cd.owner_principal_id=$2 OR EXISTS(SELECT 1 FROM corpus_access_grants WHERE corpus_id=$1 AND principal_id=$2 AND access_level='manage'))`,[input.corpusId,input.actorPrincipalId]);if(allowed.rowCount!==1)throw Object.assign(new Error("CORPUS_MANAGE_FORBIDDEN"),{statusCode:403});const target=await c.query(`SELECT 1 FROM principals p JOIN corpus_definitions cd ON cd.node_id=p.node_id WHERE cd.id=$1 AND p.id=$2`,[input.corpusId,input.principalId]);if(target.rowCount!==1)throw Object.assign(new Error("CORPUS_GRANTEE_SCOPE_INVALID"),{statusCode:400});const r=await c.query(`INSERT INTO corpus_access_grants(corpus_id,principal_id,access_level,granted_by) VALUES($1,$2,$3,$4) ON CONFLICT(corpus_id,principal_id) DO UPDATE SET access_level=EXCLUDED.access_level,granted_by=EXCLUDED.granted_by RETURNING *`,[input.corpusId,input.principalId,input.accessLevel,input.actorPrincipalId]);return r.rows[0];}

function hookCandidate(h:any,input:ClassificationInput){const matcher=h.matcher as {field?:keyof ClassificationInput;terms?:string[]};const raw=matcher.field?input[matcher.field]:undefined,text=(Array.isArray(raw)?raw.join(" "):String(raw??"")).toLowerCase(),hits=(matcher.terms??[]).filter(x=>text.includes(String(x).toLowerCase()));if(!hits.length)return null;return{corpus_key:h.corpus_key,confidence:Number(h.minimum_confidence),mega_tab:h.target_coordinate.mega_tab,tab:h.target_coordinate.tab,subtab:h.target_coordinate.subtab??null,reasons:[`hook:${h.name}:${hits.join(",")}`]};}
export async function classifyCko(c:PoolClient,input:{nodeId:string;workspaceId:string;principalId:string;ckoId:string;triggerEvent?:string;accept?:boolean}){
  const object=(await c.query(`SELECT * FROM knowledge_objects WHERE id=$1 AND node_id=$2 AND workspace_id=$3 AND lifecycle_status<>'deleted'`,[input.ckoId,input.nodeId,input.workspaceId])).rows[0];if(!object)throw Object.assign(new Error("CORPUS_CKO_NOT_FOUND"),{statusCode:404});
  const defs=await c.query(`SELECT * FROM corpus_definitions cd WHERE cd.node_id=$1 AND cd.workspace_id=$2 AND cd.enabled=true AND ${visible()} ORDER BY cd.corpus_key`,[input.nodeId,input.workspaceId,input.principalId]);
  const extensions=object.extensions??object.metadata??{};const classification:ClassificationInput={type:object.type,title:object.title,summary:object.summary,languages:object.languages,jurisdictions:object.jurisdictions,tags:extensions.tags??object.tags??[],topics:extensions.topics??[],verticals:extensions.verticals??[],intents:extensions.intents??[]};
  const runtimeDefs:CorpusDefinition[]=defs.rows.map((d:any)=>({key:d.corpus_key,title:d.title,description:d.description,visibility:d.visibility,taxonomy:d.taxonomy,rules:d.classification_rules,extension_of:d.extension_of_id}));let candidates=classifyForCorpora(classification,runtimeDefs);
  const hooks=await c.query(`SELECT h.*,cd.corpus_key FROM corpus_classification_hooks h JOIN corpus_definitions cd ON cd.id=h.corpus_id WHERE cd.node_id=$1 AND cd.workspace_id=$2 AND h.enabled=true AND h.event_type=$3`,[input.nodeId,input.workspaceId,input.triggerEvent??"manual"]);for(const h of hooks.rows){const candidate=hookCandidate(h,classification);if(candidate)candidates.push(candidate);}
  const accepted:string[]=[];if(input.accept!==false)for(const candidate of candidates){const corpus=defs.rows.find((d:any)=>d.corpus_key===candidate.corpus_key);if(!corpus)continue;const suppressed=await c.query(`SELECT 1 FROM corpus_membership_suppressions WHERE corpus_id=$1 AND cko_id=$2 AND mega_tab=$3 AND tab=$4 AND subtab=$5 AND enterprise_tenant_id IS NULL LIMIT 1`,[corpus.id,input.ckoId,candidate.mega_tab,candidate.tab,candidate.subtab??""]);if(suppressed.rowCount)continue;if(corpus.corpus_key==="enterprise"&&(await c.query(`SELECT 1 FROM enterprise_tenants WHERE corpus_id=$1 LIMIT 1`,[corpus.id])).rowCount)continue;const policy=corpus.corpus_key==="life"?(await c.query(`SELECT sensitivity,visibility FROM life_corpus_branch_policies WHERE corpus_id=$1 AND mega_tab=$2 AND tab=$3 AND subtab IN($4,'') ORDER BY subtab<>'' DESC LIMIT 1`,[corpus.id,candidate.mega_tab,candidate.tab,candidate.subtab??""])).rows[0]:null,id=uuidv7();const r=await c.query(`INSERT INTO corpus_memberships(id,corpus_id,cko_id,mega_tab,tab,subtab,membership_source,confidence,reasons,classified_by,branch_sensitivity,branch_visibility) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb,$10,$11,$12) ON CONFLICT(corpus_id,cko_id,mega_tab,tab,subtab,enterprise_tenant_id) DO UPDATE SET confidence=GREATEST(corpus_memberships.confidence,EXCLUDED.confidence),reasons=EXCLUDED.reasons,branch_sensitivity=EXCLUDED.branch_sensitivity,branch_visibility=EXCLUDED.branch_visibility,updated_at=now() WHERE corpus_memberships.membership_source<>'manual' RETURNING id`,[id,corpus.id,input.ckoId,candidate.mega_tab,candidate.tab,candidate.subtab??"",candidate.reasons[0]?.startsWith("hook:")?"hook":"automatic",candidate.confidence,JSON.stringify(candidate.reasons),input.principalId,policy?.sensitivity??"internal",policy?.visibility??"node"]);if(r.rowCount)accepted.push(r.rows[0].id);}
  const receiptId=uuidv7();await c.query(`INSERT INTO corpus_classification_receipts(id,node_id,workspace_id,cko_id,engine_version,input_digest,candidates,accepted_membership_ids,trigger_event,created_by) VALUES($1,$2,$3,$4,$5,$6,$7::jsonb,$8,$9,$10)`,[receiptId,input.nodeId,input.workspaceId,input.ckoId,CORPUS_ENGINE_VERSION,digest(classification),JSON.stringify(candidates),accepted,input.triggerEvent??"manual",input.principalId]);return{receipt_id:receiptId,engine_version:CORPUS_ENGINE_VERSION,cko_id:input.ckoId,candidates,accepted_membership_ids:accepted};
}
export async function autoClassifyCkoIfRegistered(c:PoolClient,input:{nodeId:string;workspaceId:string;principalId:string;ckoId:string;triggerEvent:"cko.created"|"cko.updated"|"compiler.completed"|"capture.ingested"}){const registered=await c.query(`SELECT count(*)::int n FROM corpus_definitions WHERE node_id=$1 AND workspace_id=$2 AND enabled=true AND built_in=true`,[input.nodeId,input.workspaceId]);const count=Number(registered.rows[0]?.n??0);if(!count)return null;if(count<BUILTIN_CORPORA.length)await ensureBuiltinCorpora(c,{nodeId:input.nodeId,workspaceId:input.workspaceId,principalId:input.principalId});return classifyCko(c,input);}
function assertTaxonomyCoordinate(corpus:any,megaTab:string,tab:string,subtab?:string){const branch=(Array.isArray(corpus.taxonomy)?corpus.taxonomy:[]).find((x:any)=>x.key===megaTab);const tabDef=branch?.tabs?.find((x:any)=>x.key===tab);if(!branch||!tabDef||subtab&&!(tabDef.subtabs??[]).includes(subtab))throw Object.assign(new Error("CORPUS_TAXONOMY_COORDINATE_INVALID"),{statusCode:400});}
export async function addManualMembership(c:PoolClient,input:{corpusId:string;ckoId:string;principalId:string;megaTab:string;tab:string;subtab?:string;confidence?:number}){const corpus=(await c.query(`SELECT cd.* FROM corpus_definitions cd JOIN knowledge_objects ko ON ko.id=$2 AND ko.node_id=cd.node_id AND ko.workspace_id=cd.workspace_id WHERE cd.id=$1 AND ${visible("cd")}`,[input.corpusId,input.ckoId,input.principalId])).rows[0];if(!corpus)throw Object.assign(new Error("CORPUS_MEMBERSHIP_SCOPE_FORBIDDEN"),{statusCode:403});assertTaxonomyCoordinate(corpus,input.megaTab,input.tab,input.subtab);if(corpus.corpus_key==="enterprise"&&(await c.query(`SELECT 1 FROM enterprise_tenants WHERE corpus_id=$1 LIMIT 1`,[corpus.id])).rowCount)throw Object.assign(new Error("ENTERPRISE_TENANT_CONTEXT_REQUIRED"),{statusCode:400});const branch=corpus.corpus_key==="life"?(await c.query(`SELECT sensitivity,visibility FROM life_corpus_branch_policies WHERE corpus_id=$1 AND mega_tab=$2 AND tab=$3 AND subtab IN($4,'') ORDER BY subtab<>'' DESC LIMIT 1`,[input.corpusId,input.megaTab,input.tab,input.subtab??""])).rows[0]:null,sensitivity=branch?.sensitivity??"internal",visibility=branch?.visibility??(corpus.visibility==="private"?"private":"node");await c.query(`DELETE FROM corpus_membership_suppressions WHERE corpus_id=$1 AND cko_id=$2 AND mega_tab=$3 AND tab=$4 AND subtab=$5 AND enterprise_tenant_id IS NULL`,[input.corpusId,input.ckoId,input.megaTab,input.tab,input.subtab??""]);const r=await c.query(`INSERT INTO corpus_memberships(id,corpus_id,cko_id,mega_tab,tab,subtab,membership_source,confidence,reasons,classified_by,branch_sensitivity,branch_visibility) VALUES($1,$2,$3,$4,$5,$6,'manual',$7,'["manual filing"]'::jsonb,$8,$9,$10) ON CONFLICT(corpus_id,cko_id,mega_tab,tab,subtab,enterprise_tenant_id) DO UPDATE SET membership_source='manual',confidence=EXCLUDED.confidence,reasons='["manual filing"]'::jsonb,classified_by=EXCLUDED.classified_by,branch_sensitivity=EXCLUDED.branch_sensitivity,branch_visibility=EXCLUDED.branch_visibility,updated_at=now() RETURNING *`,[uuidv7(),input.corpusId,input.ckoId,input.megaTab,input.tab,input.subtab??"",input.confidence??1,input.principalId,sensitivity,visibility]);return r.rows[0];}
export async function getCkoMemberships(c:PoolClient,input:{nodeId:string;workspaceId:string;principalId:string;ckoId:string}){await workspaceScope(c,input.nodeId,input.workspaceId);const r=await c.query(`SELECT v.* FROM corpus_cko_semantic_view v JOIN corpus_definitions cd ON cd.id=v.corpus_id WHERE v.node_id=$1 AND v.workspace_id=$2 AND v.cko_id=$4 AND ${visible("cd")} AND (v.branch_visibility<>'sealed' OR EXISTS(SELECT 1 FROM life_sealed_access_sessions s WHERE s.corpus_id=v.corpus_id AND s.principal_id=$3 AND s.mega_tab=v.mega_tab AND s.subtab=v.subtab AND s.revoked_at IS NULL AND s.expires_at>now())) AND (v.enterprise_tenant_id IS NULL OR EXISTS(SELECT 1 FROM enterprise_tenant_members etm WHERE etm.tenant_id=v.enterprise_tenant_id AND etm.principal_id=$3)) ORDER BY v.corpus_key,v.mega_tab,v.tab,v.subtab`,[input.nodeId,input.workspaceId,input.principalId,input.ckoId]);return r.rows;}
export async function removeMembership(c:PoolClient,input:{membershipId:string;principalId:string;reason?:string}){const row=(await c.query(`SELECT cm.*,cd.owner_principal_id FROM corpus_memberships cm JOIN corpus_definitions cd ON cd.id=cm.corpus_id WHERE cm.id=$1 AND (cm.classified_by=$2 OR cd.owner_principal_id=$2 OR EXISTS(SELECT 1 FROM corpus_access_grants g WHERE g.corpus_id=cd.id AND g.principal_id=$2 AND g.access_level='manage')) FOR UPDATE`,[input.membershipId,input.principalId])).rows[0];if(!row)throw Object.assign(new Error("CORPUS_MEMBERSHIP_REMOVE_FORBIDDEN"),{statusCode:403});await c.query(`DELETE FROM corpus_memberships WHERE id=$1`,[row.id]);await c.query(`INSERT INTO corpus_membership_suppressions(id,corpus_id,cko_id,mega_tab,tab,subtab,enterprise_tenant_id,created_by,reason) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT(corpus_id,cko_id,mega_tab,tab,subtab,enterprise_tenant_id) DO UPDATE SET created_by=EXCLUDED.created_by,reason=EXCLUDED.reason,created_at=now()`,[uuidv7(),row.corpus_id,row.cko_id,row.mega_tab,row.tab,row.subtab??"",row.enterprise_tenant_id??null,input.principalId,input.reason??"user override"]);return{removed:true,cko_id:row.cko_id,corpus_id:row.corpus_id,coordinate:{mega_tab:row.mega_tab,tab:row.tab,subtab:row.subtab??""},suppressed:true};}

export async function queryCorpusView(c:PoolClient,input:{nodeId:string;workspaceId:string;principalId:string;corpusKey?:string;megaTab?:string;tab?:string;subtab?:string;limit?:number}){await workspaceScope(c,input.nodeId,input.workspaceId);const limit=Math.max(1,Math.min(200,input.limit??50));const r=await c.query(`SELECT v.* FROM corpus_cko_semantic_view v JOIN corpus_definitions cd ON cd.id=v.corpus_id WHERE v.node_id=$1 AND v.workspace_id=$2 AND ${visible("cd")} AND ($4::text IS NULL OR v.corpus_key=$4) AND ($5::text IS NULL OR v.mega_tab=$5) AND ($6::text IS NULL OR v.tab=$6) AND ($7::text IS NULL OR v.subtab=$7) AND (v.branch_visibility<>'sealed' OR EXISTS(SELECT 1 FROM life_sealed_access_sessions s WHERE s.corpus_id=v.corpus_id AND s.principal_id=$3 AND s.mega_tab=v.mega_tab AND s.subtab=v.subtab AND s.revoked_at IS NULL AND s.expires_at>now())) AND (v.enterprise_tenant_id IS NULL OR EXISTS(SELECT 1 FROM enterprise_tenant_members etm WHERE etm.tenant_id=v.enterprise_tenant_id AND etm.principal_id=$3)) ORDER BY v.confidence DESC,v.cko_updated_at DESC LIMIT $8`,[input.nodeId,input.workspaceId,input.principalId,input.corpusKey??null,input.megaTab??null,input.tab??null,input.subtab??null,limit]);return{engine_version:CORPUS_ENGINE_VERSION,objects:r.rows};}
