import type{FastifyInstance,FastifyRequest}from"fastify";import{assertPrincipalInNode}from"./access";import{withTransaction}from"./db";import{classifyEnterpriseCko,createEnterpriseScope,fileEnterpriseCko,grantEnterpriseMember,installEnterpriseCorpus,queryEnterpriseCorpus}from"./enterprise-corpus";
const principal=(r:FastifyRequest)=>{const p=r.headers["x-cervel-principal-id"];if(typeof p!=="string"||!p)throw Object.assign(new Error("X-CERVEL-PRINCIPAL-ID is required"),{statusCode:401});return p;};
export function registerEnterpriseCorpusRoutes(app:FastifyInstance){
 app.post("/v1/enterprise/bootstrap",async(r,reply)=>{const p=principal(r),b=r.body as any;return reply.code(201).send(await withTransaction(async c=>{await assertPrincipalInNode(c,p,b.node_id);return installEnterpriseCorpus(c,{nodeId:b.node_id,workspaceId:b.workspace_id,principalId:p,tenantKey:b.tenant_key,name:b.name,legalName:b.legal_name,domain:b.domain,jurisdiction:b.jurisdiction});}));});
 app.put("/v1/enterprise/tenants/:tenantId/members/:principalId",async r=>{const p=principal(r),b=r.body as any,x=r.params as any;return withTransaction(c=>grantEnterpriseMember(c,{tenantId:x.tenantId,actorPrincipalId:p,principalId:x.principalId,role:b.role}));});
 app.post("/v1/enterprise/tenants/:tenantId/scopes",async(r,reply)=>{const p=principal(r),b=r.body as any;return reply.code(201).send(await withTransaction(c=>createEnterpriseScope(c,{tenantId:(r.params as any).tenantId,principalId:p,scopeKey:b.scope_key,name:b.name,scopeType:b.scope_type,parentScopeId:b.parent_scope_id,authorityStatus:b.authority_status,authorityMetadata:b.authority_metadata})));});
 app.post("/v1/enterprise/tenants/:tenantId/classify/:ckoId",async(r,reply)=>{const p=principal(r),b=(r.body??{})as any,x=r.params as any;return reply.code(201).send(await withTransaction(c=>classifyEnterpriseCko(c,{tenantId:x.tenantId,principalId:p,ckoId:x.ckoId,scopeId:b.scope_id,source:"manual"})));});
 app.put("/v1/enterprise/tenants/:tenantId/file/:ckoId",async r=>{const p=principal(r),b=r.body as any,x=r.params as any;return withTransaction(c=>fileEnterpriseCko(c,{tenantId:x.tenantId,principalId:p,ckoId:x.ckoId,megaTab:b.mega_tab,subtab:b.subtab,scopeId:b.scope_id,authorityStatus:b.authority_status,authorityMetadata:b.authority_metadata}));});
 app.get("/v1/enterprise/tenants/:tenantId",async r=>{const p=principal(r),q=r.query as any;return withTransaction(c=>queryEnterpriseCorpus(c,{tenantId:(r.params as any).tenantId,principalId:p,scopeId:q.scope_id,megaTab:q.mega_tab,limit:q.limit?Number(q.limit):undefined}));});
}
