import type { FastifyInstance } from "fastify";
import { withTransaction } from "./db";
import { assertPrincipalInNode } from "./access";
import { analyzeKnowledgeEvolution, whatChanged } from "./knowledge-evolution";
import { registerImpactRoutes } from "./impact-routes";
function principal(request:any){const value=request.headers["x-cervel-principal-id"];if(typeof value!=="string"||!value)throw Object.assign(new Error("X-CERVEL-PRINCIPAL-ID is required"),{statusCode:401});return value;}
async function assertWorkspace(client:any,nodeId:string,workspaceId:string){const row=await client.query(`SELECT id FROM workspaces WHERE id=$1 AND node_id=$2`,[workspaceId,nodeId]);if(row.rowCount!==1)throw Object.assign(new Error("WORKSPACE_NOT_FOUND"),{statusCode:404});}
export function registerEvolutionRoutes(app:FastifyInstance){
registerImpactRoutes(app);
app.post("/v1/evolution/analyze",async(request,reply)=>{const p=principal(request),body=request.body as {node_id:string;workspace_id:string;cko_id:string;previous_artifact_id?:string;current_artifact_id:string;previous_version?:number;current_version:number};const result=await withTransaction(async client=>{await assertPrincipalInNode(client,p,body.node_id);await assertWorkspace(client,body.node_id,body.workspace_id);return analyzeKnowledgeEvolution(client,{nodeId:body.node_id,workspaceId:body.workspace_id,ckoId:body.cko_id,previousArtifactId:body.previous_artifact_id,currentArtifactId:body.current_artifact_id,previousVersion:body.previous_version,currentVersion:body.current_version});});return reply.code(201).send(result);});
app.get("/v1/evolution/changes",async(request,reply)=>{const p=principal(request),q=request.query as {node_id?:string;workspace_id?:string;since?:string;cko_id?:string;limit?:string};if(!q.node_id||!q.workspace_id)return reply.code(400).send({error:"NODE_AND_WORKSPACE_REQUIRED"});const result=await withTransaction(async client=>{await assertPrincipalInNode(client,p,q.node_id!);await assertWorkspace(client,q.node_id!,q.workspace_id!);return whatChanged(client,{nodeId:q.node_id!,workspaceId:q.workspace_id!,since:q.since,ckoId:q.cko_id,limit:q.limit?Number(q.limit):undefined});});return reply.send({changes:result});});
app.get("/v1/evolution/claims/:id/history",async(request,reply)=>{const p=principal(request),{id}=request.params as {id:string};const result=await withTransaction(async client=>{const claim=await client.query(`SELECT node_id FROM claims WHERE id=$1`,[id]);if(claim.rowCount!==1)throw Object.assign(new Error("CLAIM_NOT_FOUND"),{statusCode:404});await assertPrincipalInNode(client,p,claim.rows[0].node_id);return client.query(`SELECT * FROM claim_evolutions WHERE node_id=$2 AND (previous_claim_id=$1 OR current_claim_id=$1) ORDER BY observed_at`,[id,claim.rows[0].node_id]);});return reply.send({history:result.rows});});
app.get("/v1/evolution/objects/:id/timeline",async(request,reply)=>{const p=principal(request),{id}=request.params as {id:string};const result=await withTransaction(async client=>{const cko=await client.query(`SELECT node_id,workspace_id FROM knowledge_objects WHERE id=$1`,[id]);if(cko.rowCount!==1)throw Object.assign(new Error("CKO_NOT_FOUND"),{statusCode:404});await assertPrincipalInNode(client,p,cko.rows[0].node_id);return(await client.query(`SELECT ke.*,kd.summary AS diff_summary FROM knowledge_events ke LEFT JOIN knowledge_diffs kd ON kd.id=ke.knowledge_diff_id WHERE ke.node_id=$2 AND ke.workspace_id=$3 AND ke.cko_id=$1 ORDER BY ke.observed_at DESC`,[id,cko.rows[0].node_id,cko.rows[0].workspace_id])).rows;});return reply.send({timeline:result});});
app.get("/v1/evolution/answers/:id/trace",async(request,reply)=>{const p=principal(request),{id}=request.params as {id:string};const result=await withTransaction(async client=>{const answer=await client.query(`SELECT id,node_id,workspace_id,principal_id,context_package_id,answer_text FROM answers WHERE id=$1`,[id]);if(answer.rowCount!==1)throw Object.assign(new Error("ANSWER_NOT_FOUND"),{statusCode:404});if(answer.rows[0].principal_id!==p)throw Object.assign(new Error("FORBIDDEN_ANSWER_SCOPE"),{statusCode:403});const chain=await client.query(`SELECT ac.role,c.id current_claim_id,c.temporal_status,c.superseded_by_claim_id,ce.id evolution_id,ce.evolution_type,ce.previous_claim_id,ke.id knowledge_event_id,ke.event_type,kd.id diff_id,kd.summary diff_summary,f.id fragment_id,f.locator,a.id artifact_id,a.role artifact_role,a.sha256 artifact_sha256,ko.id cko_id,ko.title source_title FROM answer_claims ac JOIN claims c ON c.id=ac.claim_id LEFT JOIN claim_evolutions ce ON ce.current_claim_id=c.id LEFT JOIN knowledge_events ke ON ke.knowledge_diff_id=ce.knowledge_diff_id AND ke.current_claim_id=c.id LEFT JOIN knowledge_diffs kd ON kd.id=ce.knowledge_diff_id LEFT JOIN claim_evidence cev ON cev.claim_id=c.id LEFT JOIN fragments f ON f.id=cev.fragment_id LEFT JOIN artifacts a ON a.id=f.artifact_id LEFT JOIN knowledge_objects ko ON ko.id=f.cko_id WHERE ac.answer_id=$1 AND c.node_id=$2 AND (ko.workspace_id IS NULL OR ko.workspace_id=$3) ORDER BY ac.ordinal,ce.observed_at DESC,f.ordinal`,[id,answer.rows[0].node_id,answer.rows[0].workspace_id]);return{trace_version:"0.2-temporal",answer:{id,text:answer.rows[0].answer_text},context_package_id:answer.rows[0].context_package_id,trace_contract:"Answer → Current Claim → Previous Claim → Knowledge Event → Semantic Diff → Fragment → Artifact Version → Original Source",chain:chain.rows};});return reply.send(result);});
}
