import type { FastifyInstance } from "fastify";
import { withTransaction } from "./db";
import { assertPrincipalInNode } from "./access";
import { analyzeKnowledgeEvolution, whatChanged } from "./knowledge-evolution";

function principal(request:any){const value=request.headers["x-cervel-principal-id"];if(typeof value!=="string"||!value)throw Object.assign(new Error("X-CERVEL-PRINCIPAL-ID is required"),{statusCode:401});return value;}
async function assertWorkspace(client:any,nodeId:string,workspaceId:string){const row=await client.query(`SELECT id FROM workspaces WHERE id=$1 AND node_id=$2`,[workspaceId,nodeId]);if(row.rowCount!==1)throw Object.assign(new Error("WORKSPACE_NOT_FOUND"),{statusCode:404});}

export function registerEvolutionRoutes(app:FastifyInstance){
  app.post("/v1/evolution/analyze",async(request,reply)=>{const p=principal(request);const body=request.body as {node_id:string;workspace_id:string;cko_id:string;previous_artifact_id?:string;current_artifact_id:string;previous_version?:number;current_version:number};const result=await withTransaction(async client=>{await assertPrincipalInNode(client,p,body.node_id);await assertWorkspace(client,body.node_id,body.workspace_id);const cko=await client.query(`SELECT id FROM knowledge_objects WHERE id=$1 AND node_id=$2 AND workspace_id=$3`,[body.cko_id,body.node_id,body.workspace_id]);if(cko.rowCount!==1)throw Object.assign(new Error("CKO_NOT_FOUND"),{statusCode:404});return analyzeKnowledgeEvolution(client,{nodeId:body.node_id,workspaceId:body.workspace_id,ckoId:body.cko_id,previousArtifactId:body.previous_artifact_id,currentArtifactId:body.current_artifact_id,previousVersion:body.previous_version,currentVersion:body.current_version});});return reply.code(201).send(result);});
  app.get("/v1/evolution/changes",async(request,reply)=>{const p=principal(request);const q=request.query as {node_id?:string;workspace_id?:string;since?:string;cko_id?:string;limit?:string};if(!q.node_id||!q.workspace_id)return reply.code(400).send({error:"NODE_AND_WORKSPACE_REQUIRED"});const result=await withTransaction(async client=>{await assertPrincipalInNode(client,p,q.node_id!);await assertWorkspace(client,q.node_id!,q.workspace_id!);return whatChanged(client,{nodeId:q.node_id!,workspaceId:q.workspace_id!,since:q.since,ckoId:q.cko_id,limit:q.limit?Number(q.limit):undefined});});return reply.send({changes:result});});
  app.get("/v1/evolution/claims/:id/history",async(request,reply)=>{const p=principal(request),{id}=request.params as {id:string};const result=await withTransaction(async client=>{const claim=await client.query(`SELECT node_id FROM claims WHERE id=$1`,[id]);if(claim.rowCount!==1)throw Object.assign(new Error("CLAIM_NOT_FOUND"),{statusCode:404});await assertPrincipalInNode(client,p,claim.rows[0].node_id);return client.query(`SELECT * FROM claim_evolutions WHERE previous_claim_id=$1 OR current_claim_id=$1 ORDER BY observed_at`,[id]);});return reply.send({history:result.rows});});
  app.get("/v1/evolution/objects/:id/timeline",async(request,reply)=>{const p=principal(request),{id}=request.params as {id:string};const result=await withTransaction(async client=>{const cko=await client.query(`SELECT node_id,workspace_id FROM knowledge_objects WHERE id=$1`,[id]);if(cko.rowCount!==1)throw Object.assign(new Error("CKO_NOT_FOUND"),{statusCode:404});await assertPrincipalInNode(client,p,cko.rows[0].node_id);const events=await client.query(`SELECT ke.*,kd.summary AS diff_summary FROM knowledge_events ke LEFT JOIN knowledge_diffs kd ON kd.id=ke.knowledge_diff_id WHERE ke.cko_id=$1 ORDER BY ke.observed_at DESC`,[id]);return events.rows;});return reply.send({timeline:result});});
}
