import type { FastifyInstance } from "fastify";
import { withTransaction } from "./db";
import { assertPrincipalInNode } from "./access";
import { dependencyNeighborhood, inferDependenciesFromKnowledge, propagateKnowledgeImpact, upsertDependency } from "./impact-engine";

function principal(request:any){const value=request.headers["x-cervel-principal-id"];if(typeof value!=="string"||!value)throw Object.assign(new Error("X-CERVEL-PRINCIPAL-ID is required"),{statusCode:401});return value;}
async function scope(client:any,nodeId:string,workspaceId:string,principalId:string){await assertPrincipalInNode(client,principalId,nodeId);const row=await client.query(`SELECT 1 FROM workspaces WHERE id=$1 AND node_id=$2`,[workspaceId,nodeId]);if(row.rowCount!==1)throw Object.assign(new Error("WORKSPACE_NOT_FOUND"),{statusCode:404});}

export function registerImpactRoutes(app:FastifyInstance){
  app.post("/v1/dependencies",async(request,reply)=>{const p=principal(request),b=request.body as any;if(!b?.node_id||!b?.workspace_id||!b?.source_type||!b?.source_id||!b?.relation||!b?.target_type||!b?.target_id)return reply.code(400).send({error:"DEPENDENCY_FIELDS_REQUIRED"});const result=await withTransaction(async c=>{await scope(c,b.node_id,b.workspace_id,p);return upsertDependency(c,{nodeId:b.node_id,workspaceId:b.workspace_id,sourceType:b.source_type,sourceId:b.source_id,relation:b.relation,targetType:b.target_type,targetId:b.target_id,confidence:b.confidence,strength:b.strength,createdBy:p,properties:b.properties});});return reply.code(201).send(result);});
  app.post("/v1/dependencies/infer",async(request,reply)=>{const p=principal(request),b=request.body as {node_id:string;workspace_id:string};const result=await withTransaction(async c=>{await scope(c,b.node_id,b.workspace_id,p);return inferDependenciesFromKnowledge(c,{nodeId:b.node_id,workspaceId:b.workspace_id});});return reply.send({dependencies:result});});
  app.get("/v1/dependencies/graph",async(request,reply)=>{const p=principal(request),q=request.query as any;if(!q.node_id||!q.workspace_id||!q.type||!q.id)return reply.code(400).send({error:"NODE_WORKSPACE_TYPE_ID_REQUIRED"});const result=await withTransaction(async c=>{await scope(c,q.node_id,q.workspace_id,p);return dependencyNeighborhood(c,{nodeId:q.node_id,workspaceId:q.workspace_id,type:q.type,id:q.id,depth:q.depth?Number(q.depth):undefined});});return reply.send({edges:result});});
  app.post("/v1/impact/:eventId/propagate",async(request,reply)=>{const p=principal(request),{eventId}=request.params as {eventId:string},b=(request.body??{}) as any;const event=await withTransaction(c=>c.query(`SELECT node_id,workspace_id FROM knowledge_events WHERE id=$1`,[eventId]));if(event.rowCount!==1)return reply.code(404).send({error:"KNOWLEDGE_EVENT_NOT_FOUND"});const result=await withTransaction(async c=>{await scope(c,event.rows[0].node_id,event.rows[0].workspace_id,p);return propagateKnowledgeImpact(c,{eventId,nodeId:event.rows[0].node_id,workspaceId:event.rows[0].workspace_id,maxDepth:b.max_depth,confidenceFloor:b.confidence_floor});});return reply.code(201).send(result);});
  app.get("/v1/impact/:eventId",async(request,reply)=>{const p=principal(request),{eventId}=request.params as {eventId:string};const event=await withTransaction(c=>c.query(`SELECT node_id,workspace_id FROM knowledge_events WHERE id=$1`,[eventId]));if(event.rowCount!==1)return reply.code(404).send({error:"KNOWLEDGE_EVENT_NOT_FOUND"});const result=await withTransaction(async c=>{await scope(c,event.rows[0].node_id,event.rows[0].workspace_id,p);return c.query(`SELECT kei.*,ipr.status AS propagation_status FROM knowledge_event_impacts kei LEFT JOIN impact_propagation_runs ipr ON ipr.id=kei.propagation_run_id WHERE kei.event_id=$1 ORDER BY kei.depth NULLS LAST,kei.confidence DESC`,[eventId]);});return reply.send({impacts:result.rows});});
}
