import type { PoolClient } from "pg";
import { uuidv7 } from "./uuidv7";

type ResourceType="cko"|"claim"|"entity"|"relationship"|"context_package"|"answer"|"library"|"project"|"decision"|"source";
type Relation="depends_on"|"derived_from"|"supports"|"contradicts"|"supersedes"|"affected_by";
type ImpactKind="affected"|"stale"|"invalidated"|"requires_review";

const decay:Record<Relation,number>={depends_on:.9,derived_from:.88,supports:.84,contradicts:.8,supersedes:.95,affected_by:.9};
const kindFor=(relation:Relation):ImpactKind=>relation==="contradicts"||relation==="supersedes"?"requires_review":relation==="derived_from"?"stale":"affected";

export async function upsertDependency(client:PoolClient,input:{nodeId:string;workspaceId:string;sourceType:ResourceType;sourceId:string;relation:Relation;targetType:ResourceType;targetId:string;confidence?:number;strength?:number;createdBy?:string|null;properties?:Record<string,unknown>}){
  if(input.sourceType===input.targetType&&input.sourceId===input.targetId)throw Object.assign(new Error("DEPENDENCY_SELF_REFERENCE"),{statusCode:400});
  const id=uuidv7();const row=await client.query(`INSERT INTO knowledge_dependencies(id,node_id,workspace_id,source_type,source_id,relation,target_type,target_id,confidence,strength,created_by,properties) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12::jsonb) ON CONFLICT(node_id,workspace_id,source_type,source_id,relation,target_type,target_id) DO UPDATE SET confidence=EXCLUDED.confidence,strength=EXCLUDED.strength,properties=EXCLUDED.properties,propagation_enabled=true,valid_until=NULL,updated_at=now() RETURNING *`,[id,input.nodeId,input.workspaceId,input.sourceType,input.sourceId,input.relation,input.targetType,input.targetId,input.confidence??1,input.strength??1,input.createdBy??null,JSON.stringify(input.properties??{})]);return row.rows[0];
}

export async function inferDependenciesFromKnowledge(client:PoolClient,input:{nodeId:string;workspaceId:string}){
  const inserted:any[]=[];
  const claimLinks=await client.query(`SELECT c.id AS claim_id,c.subject_type,c.subject_id,c.object_kind,c.object_ref_type,c.object_ref_id FROM claims c WHERE c.node_id=$1 AND c.temporal_status='current'`,[input.nodeId]);
  for(const c of claimLinks.rows){if(c.subject_type==='cko')inserted.push(await upsertDependency(client,{nodeId:input.nodeId,workspaceId:input.workspaceId,sourceType:'claim',sourceId:c.claim_id,relation:'derived_from',targetType:'cko',targetId:c.subject_id,confidence:.9,strength:.9}));if(c.object_kind==='reference'&&c.object_ref_id&&['cko','claim','entity'].includes(c.object_ref_type))inserted.push(await upsertDependency(client,{nodeId:input.nodeId,workspaceId:input.workspaceId,sourceType:'claim',sourceId:c.claim_id,relation:'depends_on',targetType:c.object_ref_type as ResourceType,targetId:c.object_ref_id,confidence:.82,strength:.82}));}
  const answers=await client.query(`SELECT a.id AS answer_id,a.context_package_id,ac.claim_id,ac.role FROM answers a LEFT JOIN answer_claims ac ON ac.answer_id=a.id WHERE a.node_id=$1 AND a.workspace_id=$2`,[input.nodeId,input.workspaceId]);
  for(const a of answers.rows){if(a.context_package_id)inserted.push(await upsertDependency(client,{nodeId:input.nodeId,workspaceId:input.workspaceId,sourceType:'answer',sourceId:a.answer_id,relation:'derived_from',targetType:'context_package',targetId:a.context_package_id,confidence:.98,strength:1}));if(a.claim_id)inserted.push(await upsertDependency(client,{nodeId:input.nodeId,workspaceId:input.workspaceId,sourceType:'answer',sourceId:a.answer_id,relation:a.role==='conflicting'?'contradicts':'depends_on',targetType:'claim',targetId:a.claim_id,confidence:.95,strength:.95}));}
  const context=await client.query(`SELECT cc.context_package_id,cc.claim_id FROM context_claims cc JOIN context_packages cp ON cp.id=cc.context_package_id WHERE cp.node_id=$1 AND cp.workspace_id=$2`,[input.nodeId,input.workspaceId]);
  for(const row of context.rows)inserted.push(await upsertDependency(client,{nodeId:input.nodeId,workspaceId:input.workspaceId,sourceType:'context_package',sourceId:row.context_package_id,relation:'depends_on',targetType:'claim',targetId:row.claim_id,confidence:.96,strength:.95}));
  const conflicts=await client.query(`SELECT claim_a_id,claim_b_id,confidence FROM claim_conflicts WHERE node_id=$1`,[input.nodeId]);for(const c of conflicts.rows){inserted.push(await upsertDependency(client,{nodeId:input.nodeId,workspaceId:input.workspaceId,sourceType:'claim',sourceId:c.claim_a_id,relation:'contradicts',targetType:'claim',targetId:c.claim_b_id,confidence:Number(c.confidence??.9),strength:.9}));inserted.push(await upsertDependency(client,{nodeId:input.nodeId,workspaceId:input.workspaceId,sourceType:'claim',sourceId:c.claim_b_id,relation:'contradicts',targetType:'claim',targetId:c.claim_a_id,confidence:Number(c.confidence??.9),strength:.9}));}
  const evolutions=await client.query(`SELECT previous_claim_id,current_claim_id,evolution_type,confidence FROM claim_evolutions WHERE node_id=$1 AND workspace_id=$2 AND previous_claim_id IS NOT NULL AND current_claim_id IS NOT NULL`,[input.nodeId,input.workspaceId]);for(const e of evolutions.rows){const relation:Relation=e.evolution_type==='confirmed'?'supports':'supersedes';inserted.push(await upsertDependency(client,{nodeId:input.nodeId,workspaceId:input.workspaceId,sourceType:'claim',sourceId:e.current_claim_id,relation,targetType:'claim',targetId:e.previous_claim_id,confidence:Number(e.confidence??.8),strength:.95}));}
  return inserted;
}

export async function propagateKnowledgeImpact(client:PoolClient,input:{eventId:string;nodeId:string;workspaceId:string;maxDepth?:number;confidenceFloor?:number}){
  const event=await client.query(`SELECT * FROM knowledge_events WHERE id=$1 AND node_id=$2 AND workspace_id=$3`,[input.eventId,input.nodeId,input.workspaceId]);if(event.rowCount!==1)throw Object.assign(new Error("KNOWLEDGE_EVENT_NOT_FOUND"),{statusCode:404});
  const rootType=(event.rows[0].subject_type==='source'?'source':event.rows[0].subject_type) as ResourceType,rootId=String(event.rows[0].subject_id),maxDepth=Math.max(1,Math.min(12,input.maxDepth??4)),floor=Math.max(0,Math.min(1,input.confidenceFloor??.2));const runId=uuidv7();await client.query(`INSERT INTO impact_propagation_runs(id,node_id,workspace_id,event_id,root_type,root_id,max_depth,confidence_floor) VALUES($1,$2,$3,$4,$5,$6,$7,$8)`,[runId,input.nodeId,input.workspaceId,input.eventId,rootType,rootId,maxDepth,floor]);
  type State={type:ResourceType;id:string;depth:number;confidence:number;path:any[]};const queue:State[]=[{type:rootType,id:rootId,depth:0,confidence:Number(event.rows[0].confidence??1),path:[]}],best=new Map<string,number>();let impacted=0;
  while(queue.length){const cur=queue.shift()!;if(cur.depth>=maxDepth)continue;const edges=await client.query(`SELECT * FROM knowledge_dependencies WHERE node_id=$1 AND workspace_id=$2 AND propagation_enabled=true AND valid_until IS NULL AND target_type=$3 AND target_id=$4 ORDER BY confidence DESC`,[input.nodeId,input.workspaceId,cur.type,cur.id]);for(const edge of edges.rows){const relation=edge.relation as Relation,nextConfidence=cur.confidence*Number(edge.confidence??1)*Number(edge.strength??1)*decay[relation],nextDepth=cur.depth+1;if(nextConfidence<floor)continue;const key=`${edge.source_type}:${edge.source_id}`;if((best.get(key)??0)>=nextConfidence)continue;best.set(key,nextConfidence);const path=[...cur.path,{dependency_id:edge.id,relation,from:{type:edge.source_type,id:edge.source_id},to:{type:edge.target_type,id:edge.target_id}}],kind=kindFor(relation);await client.query(`INSERT INTO impact_paths(propagation_run_id,event_id,impacted_type,impacted_id,depth,path,confidence,impact_kind) VALUES($1,$2,$3,$4,$5,$6::jsonb,$7,$8) ON CONFLICT(propagation_run_id,impacted_type,impacted_id,impact_kind) DO UPDATE SET depth=LEAST(impact_paths.depth,EXCLUDED.depth),confidence=GREATEST(impact_paths.confidence,EXCLUDED.confidence),path=CASE WHEN EXCLUDED.confidence>impact_paths.confidence THEN EXCLUDED.path ELSE impact_paths.path END`,[runId,input.eventId,edge.source_type,edge.source_id,nextDepth,JSON.stringify(path),nextConfidence,kind]);await client.query(`INSERT INTO knowledge_event_impacts(event_id,impacted_type,impacted_id,impact_kind,confidence,details,propagation_run_id,depth,path) VALUES($1,$2,$3,$4,$5,$6::jsonb,$7,$8,$9::jsonb) ON CONFLICT(event_id,impacted_type,impacted_id,impact_kind) DO UPDATE SET confidence=GREATEST(knowledge_event_impacts.confidence,EXCLUDED.confidence),details=EXCLUDED.details,propagation_run_id=EXCLUDED.propagation_run_id,depth=LEAST(COALESCE(knowledge_event_impacts.depth,EXCLUDED.depth),EXCLUDED.depth),path=EXCLUDED.path`,[input.eventId,edge.source_type,edge.source_id,kind,nextConfidence,JSON.stringify({via_relation:relation}),runId,nextDepth,JSON.stringify(path)]);impacted++;queue.push({type:edge.source_type,id:edge.source_id,depth:nextDepth,confidence:nextConfidence,path});}}
  await client.query(`UPDATE impact_propagation_runs SET status='succeeded',impacted_count=$2,completed_at=now() WHERE id=$1`,[runId,impacted]);return {run_id:runId,event_id:input.eventId,impacted_count:impacted,impacts:(await client.query(`SELECT * FROM impact_paths WHERE propagation_run_id=$1 ORDER BY depth,confidence DESC`,[runId])).rows};
}

export async function dependencyNeighborhood(client:PoolClient,input:{nodeId:string;workspaceId:string;type:ResourceType;id:string;depth?:number}){const max=Math.max(1,Math.min(6,input.depth??2));const rows=await client.query(`WITH RECURSIVE walk AS (SELECT kd.*,1 AS depth,ARRAY[kd.id]::uuid[] AS edge_path FROM knowledge_dependencies kd WHERE kd.node_id=$1 AND kd.workspace_id=$2 AND kd.valid_until IS NULL AND ((kd.source_type=$3 AND kd.source_id=$4) OR (kd.target_type=$3 AND kd.target_id=$4)) UNION ALL SELECT kd,w.depth+1,w.edge_path||kd.id FROM walk w JOIN knowledge_dependencies kd ON kd.node_id=$1 AND kd.workspace_id=$2 AND kd.valid_until IS NULL AND NOT kd.id=ANY(w.edge_path) AND (kd.source_id=w.target_id OR kd.target_id=w.source_id) WHERE w.depth<$5) SELECT DISTINCT ON(id) * FROM walk ORDER BY id,depth`,[input.nodeId,input.workspaceId,input.type,input.id,max]);return rows.rows;}
