import type{FastifyInstance,FastifyRequest}from"fastify";import{assertPrincipalInNode}from"./access";import{withTransaction}from"./db";import{classifyLifeCko,fileLifeCko,getLifeCorpus,installLifeCorpus,unlockLifeSealedBranch}from"./life-corpus";
const principal=(r:FastifyRequest)=>{const p=r.headers["x-cervel-principal-id"];if(typeof p!=="string"||!p)throw Object.assign(new Error("X-CERVEL-PRINCIPAL-ID is required"),{statusCode:401});return p;};
export function registerLifeCorpusRoutes(app:FastifyInstance){
 app.post("/v1/life/bootstrap",async(r,reply)=>{const p=principal(r),b=r.body as any;return reply.code(201).send(await withTransaction(async c=>{await assertPrincipalInNode(c,p,b.node_id);return installLifeCorpus(c,{nodeId:b.node_id,workspaceId:b.workspace_id,principalId:p});}));});
 app.post("/v1/life/classify/:ckoId",async(r,reply)=>{const p=principal(r),b=r.body as any;return reply.code(201).send(await withTransaction(async c=>{await assertPrincipalInNode(c,p,b.node_id);return classifyLifeCko(c,{nodeId:b.node_id,workspaceId:b.workspace_id,principalId:p,ckoId:(r.params as any).ckoId,source:"manual"});}));});
 app.put("/v1/life/file/:ckoId",async r=>{const p=principal(r),b=r.body as any;return withTransaction(async c=>{await assertPrincipalInNode(c,p,b.node_id);return fileLifeCko(c,{nodeId:b.node_id,workspaceId:b.workspace_id,principalId:p,ckoId:(r.params as any).ckoId,megaTab:b.mega_tab,subtab:b.subtab});});});
 app.post("/v1/life/sealed/unlock",async(r,reply)=>{const p=principal(r),b=r.body as any;return reply.code(201).send(await withTransaction(async c=>{await assertPrincipalInNode(c,p,b.node_id);return unlockLifeSealedBranch(c,{nodeId:b.node_id,workspaceId:b.workspace_id,principalId:p,megaTab:b.mega_tab,subtab:b.subtab,proofType:b.proof_type,proofReference:b.proof_reference,ttlMinutes:b.ttl_minutes});}));});
 app.get("/v1/life",async r=>{const p=principal(r),q=r.query as any;return withTransaction(async c=>{await assertPrincipalInNode(c,p,q.node_id);return getLifeCorpus(c,{nodeId:q.node_id,workspaceId:q.workspace_id,principalId:p,megaTab:q.mega_tab,limit:q.limit?Number(q.limit):undefined});});});
}
