import type{PoolClient}from"pg";
import{canonicalKernelURI}from"../../../packages/ckuri/src";
import{KERNEL_VERSION,stableKernelDigest,validateKernelRecord,validateLifecycleTransition,type AuthorityState,type KernelKind,type LifecycleState,type SensitivityLevel}from"../../../packages/semantic-kernel/src";
import{appendProvenanceEvent}from"./provenance";
import{uuidv7}from"./uuidv7";

export type CreateKernelRecordInput={nodeId:string;workspaceId:string;principalId:string;kind:KernelKind;payload:Record<string,unknown>;lifecycle?:LifecycleState;sensitivity?:SensitivityLevel;authority?:AuthorityState;confidence?:number|null;observedAt?:string;effectiveFrom?:string|null;effectiveUntil?:string|null;supersedesId?:string|null;policyId?:string|null;binding?:{resourceType:string;resourceId:string;role?:"canonical"|"source"|"derived"|"projection"}};
async function scope(client:PoolClient,nodeId:string,workspaceId:string){const r=await client.query(`SELECT n.slug FROM nodes n JOIN workspaces w ON w.node_id=n.id WHERE n.id=$1 AND w.id=$2`,[nodeId,workspaceId]);if(r.rowCount!==1)throw Object.assign(new Error("KERNEL_WORKSPACE_SCOPE_INVALID"),{statusCode:404});return String(r.rows[0].slug);}
function publicRecord(row:any){return{kernel_version:row.kernel_version,id:row.id,node_id:row.node_id,workspace_id:row.workspace_id,kind:row.kind,canonical_uri:row.canonical_uri,lifecycle:row.lifecycle,sensitivity:row.sensitivity,authority:row.authority_status,confidence:row.confidence,payload:row.payload,observed_at:new Date(row.observed_at).toISOString(),effective_from:row.effective_from?new Date(row.effective_from).toISOString():null,effective_until:row.effective_until?new Date(row.effective_until).toISOString():null,supersedes_id:row.supersedes_id,policy_id:row.policy_id,provenance_event_id:row.provenance_event_id,created_by:row.created_by,record_version:row.record_version,created_at:new Date(row.created_at).toISOString(),updated_at:new Date(row.updated_at).toISOString()};}

export async function createKernelRecord(client:PoolClient,input:CreateKernelRecordInput){
 const authority=await scope(client,input.nodeId,input.workspaceId),id=uuidv7(),now=new Date().toISOString(),canonicalUri=canonicalKernelURI(authority,input.kind,id);
 const candidate={id,node_id:input.nodeId,workspace_id:input.workspaceId,kind:input.kind,lifecycle:input.lifecycle??"active",sensitivity:input.sensitivity??"internal",authority:input.authority??"reported",confidence:input.confidence??null,payload:input.payload,observed_at:input.observedAt??now,effective_from:input.effectiveFrom??null,effective_until:input.effectiveUntil??null,supersedes_id:input.supersedesId??null,policy_id:input.policyId??null,provenance_event_id:null,created_by:input.principalId};
 validateKernelRecord(candidate);const digest=stableKernelDigest(input.payload);
 const inserted=await client.query(`INSERT INTO semantic_kernel_records(id,kernel_version,node_id,workspace_id,kind,canonical_uri,lifecycle,sensitivity,authority_status,confidence,payload,payload_sha256,observed_at,effective_from,effective_until,supersedes_id,policy_id,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11::jsonb,$12,$13,$14,$15,$16,$17,$18) RETURNING *`,[id,KERNEL_VERSION,input.nodeId,input.workspaceId,input.kind,canonicalUri,candidate.lifecycle,candidate.sensitivity,candidate.authority,candidate.confidence,JSON.stringify(input.payload),digest,candidate.observed_at,candidate.effective_from,candidate.effective_until,candidate.supersedes_id,candidate.policy_id,input.principalId]);
 if(input.binding)await client.query(`INSERT INTO semantic_kernel_bindings(record_id,resource_type,resource_id,binding_role) VALUES($1,$2,$3,$4)`,[id,input.binding.resourceType,input.binding.resourceId,input.binding.role??"canonical"]);
 const provenanceId=await appendProvenanceEvent(client,{nodeId:input.nodeId,eventType:"semantic_kernel_record_created",actorType:"human",actorPrincipalId:input.principalId,outputs:[{resourceType:"semantic_kernel",resourceId:id,sha256:digest}],parameters:{kernel_version:KERNEL_VERSION,kind:input.kind,canonical_uri:canonicalUri}});
 const row=(await client.query(`UPDATE semantic_kernel_records SET provenance_event_id=$2 WHERE id=$1 RETURNING *`,[id,provenanceId])).rows[0];const snapshot=publicRecord(row),snapshotHash=stableKernelDigest(snapshot);
 await client.query(`INSERT INTO semantic_kernel_versions(id,record_id,version,snapshot,snapshot_sha256,changed_by,change_reason) VALUES($1,$2,1,$3::jsonb,$4,$5,'initial kernel registration')`,[uuidv7(),id,JSON.stringify(snapshot),snapshotHash,input.principalId]);
 return{...snapshot,payload_sha256:digest};
}

export async function getKernelRecord(client:PoolClient,id:string,nodeId:string){const r=await client.query(`SELECT r.*,COALESCE(jsonb_agg(jsonb_build_object('resource_type',b.resource_type,'resource_id',b.resource_id,'binding_role',b.binding_role))FILTER(WHERE b.record_id IS NOT NULL),'[]'::jsonb)bindings FROM semantic_kernel_records r LEFT JOIN semantic_kernel_bindings b ON b.record_id=r.id WHERE r.id=$1 AND r.node_id=$2 GROUP BY r.id`,[id,nodeId]);if(r.rowCount!==1)throw Object.assign(new Error("KERNEL_RECORD_NOT_FOUND"),{statusCode:404});return{...publicRecord(r.rows[0]),bindings:r.rows[0].bindings};}
export async function listKernelRecords(client:PoolClient,input:{nodeId:string;workspaceId:string;kind?:KernelKind;lifecycle?:LifecycleState;limit?:number}){const limit=Math.max(1,Math.min(200,input.limit??50));const r=await client.query(`SELECT * FROM semantic_kernel_records WHERE node_id=$1 AND workspace_id=$2 AND ($3::text IS NULL OR kind=$3) AND ($4::text IS NULL OR lifecycle=$4) ORDER BY observed_at DESC,id LIMIT $5`,[input.nodeId,input.workspaceId,input.kind??null,input.lifecycle??null,limit]);return r.rows.map(publicRecord);}
export async function supersedeKernelRecord(client:PoolClient,oldId:string,input:Omit<CreateKernelRecordInput,"kind"|"supersedesId">){const old=await client.query(`SELECT * FROM semantic_kernel_records WHERE id=$1 AND node_id=$2 AND workspace_id=$3 FOR UPDATE`,[oldId,input.nodeId,input.workspaceId]);if(old.rowCount!==1)throw Object.assign(new Error("KERNEL_RECORD_NOT_FOUND"),{statusCode:404});validateLifecycleTransition(old.rows[0].lifecycle,"superseded");const next=await createKernelRecord(client,{...input,kind:old.rows[0].kind,supersedesId:oldId});const updated=(await client.query(`UPDATE semantic_kernel_records SET lifecycle='superseded',authority_status='superseded',record_version=record_version+1,updated_at=now() WHERE id=$1 RETURNING *`,[oldId])).rows[0];const snapshot=publicRecord(updated);await client.query(`INSERT INTO semantic_kernel_versions(id,record_id,version,snapshot,snapshot_sha256,changed_by,change_reason) VALUES($1,$2,$3,$4::jsonb,$5,$6,'superseded by new kernel record')`,[uuidv7(),oldId,updated.record_version,JSON.stringify(snapshot),stableKernelDigest(snapshot),input.principalId]);return{previous:snapshot,current:next};}
