import type{FastifyInstance,FastifyRequest}from"fastify";import{withTransaction}from"./db";import{assertPrincipalInNode}from"./access";import{createKernelRecord,getKernelRecord,listKernelRecords,supersedeKernelRecord}from"./semantic-kernel";import{KERNEL_KINDS,KERNEL_VERSION,LIFECYCLE_STATES,type KernelKind,type LifecycleState}from"../../../packages/semantic-kernel/src";
function principal(r:FastifyRequest){const p=r.headers["x-cervel-principal-id"];if(typeof p!=="string"||!p)throw Object.assign(new Error("X-CERVEL-PRINCIPAL-ID is required"),{statusCode:401});return p;}
export function registerSemanticKernelRoutes(app:FastifyInstance){
 app.get("/v1/kernel",async()=>({kernel_version:KERNEL_VERSION,status:"active",kinds:KERNEL_KINDS,lifecycle_states:LIFECYCLE_STATES,contract_uri:"https://schemas.cervel.ai/semantic-kernel/1.0/schema.json"}));
 app.post("/v1/kernel/records",async(r,reply)=>{const p=principal(r),b=r.body as any;return reply.code(201).send(await withTransaction(async c=>{await assertPrincipalInNode(c,p,b.node_id);return createKernelRecord(c,{nodeId:b.node_id,workspaceId:b.workspace_id,principalId:p,kind:b.kind,payload:b.payload,lifecycle:b.lifecycle,sensitivity:b.sensitivity,authority:b.authority,confidence:b.confidence,observedAt:b.observed_at,effectiveFrom:b.effective_from,effectiveUntil:b.effective_until,policyId:b.policy_id,binding:b.binding});}));});
 app.get("/v1/kernel/records",async r=>{const p=principal(r),q=r.query as any;return withTransaction(async c=>{await assertPrincipalInNode(c,p,q.node_id);return{records:await listKernelRecords(c,{nodeId:q.node_id,workspaceId:q.workspace_id,kind:q.kind as KernelKind|undefined,lifecycle:q.lifecycle as LifecycleState|undefined,limit:q.limit?Number(q.limit):undefined})};});});
 app.get("/v1/kernel/records/:id",async r=>{const p=principal(r),q=r.query as any,{id}=r.params as any;return withTransaction(async c=>{await assertPrincipalInNode(c,p,q.node_id);return getKernelRecord(c,id,q.node_id);});});
 app.post("/v1/kernel/records/:id/supersede",async(r,reply)=>{const p=principal(r),b=r.body as any,{id}=r.params as any;return reply.code(201).send(await withTransaction(async c=>{await assertPrincipalInNode(c,p,b.node_id);return supersedeKernelRecord(c,id,{nodeId:b.node_id,workspaceId:b.workspace_id,principalId:p,payload:b.payload,lifecycle:"active",sensitivity:b.sensitivity,authority:b.authority,confidence:b.confidence,observedAt:b.observed_at,effectiveFrom:b.effective_from,effectiveUntil:b.effective_until,policyId:b.policy_id,binding:b.binding});}));});
}
