import type { FastifyInstance } from "fastify";
import { withTransaction } from "./db";
import { assertPrincipalInNode } from "./access";
import { createWatch, evaluateEventForWatches, reevaluateRecentEvents } from "./watch-engine";

function principal(request:any){const value=request.headers["x-cervel-principal-id"];if(typeof value!=="string"||!value)throw Object.assign(new Error("X-CERVEL-PRINCIPAL-ID is required"),{statusCode:401});return value;}
async function assertWorkspace(client:any,nodeId:string,workspaceId:string){const row=await client.query(`SELECT id FROM workspaces WHERE id=$1 AND node_id=$2`,[workspaceId,nodeId]);if(row.rowCount!==1)throw Object.assign(new Error("WORKSPACE_NOT_FOUND"),{statusCode:404});}

export function registerWatchRoutes(app:FastifyInstance){
  app.post("/v1/watch",async(request,reply)=>{const p=principal(request),body=request.body as any;const result=await withTransaction(async client=>{await assertPrincipalInNode(client,p,body.node_id);await assertWorkspace(client,body.node_id,body.workspace_id);return createWatch(client,{nodeId:body.node_id,workspaceId:body.workspace_id,principalId:p,name:body.name,intent:body.intent,eventTypes:body.event_types,subjectTypes:body.subject_types,impactKinds:body.impact_kinds,keywords:body.keywords,focus:body.focus,minEventConfidence:body.min_event_confidence,minImpactConfidence:body.min_impact_confidence,minScore:body.min_score,cooldownSeconds:body.cooldown_seconds,channels:body.channels});});return reply.code(201).send(result);});
  app.get("/v1/watch",async(request,reply)=>{const p=principal(request),q=request.query as {node_id?:string;workspace_id?:string};if(!q.node_id||!q.workspace_id)return reply.code(400).send({error:"NODE_AND_WORKSPACE_REQUIRED"});const rows=await withTransaction(async client=>{await assertPrincipalInNode(client,p,q.node_id!);await assertWorkspace(client,q.node_id!,q.workspace_id!);return client.query(`SELECT * FROM knowledge_watches WHERE node_id=$1 AND workspace_id=$2 AND principal_id=$3 ORDER BY created_at DESC`,[q.node_id,q.workspace_id,p]);});return reply.send({watches:rows.rows});});
  app.patch("/v1/watch/:id",async(request,reply)=>{const p=principal(request),{id}=request.params as {id:string},body=request.body as any;const result=await withTransaction(async client=>{const current=await client.query(`SELECT * FROM knowledge_watches WHERE id=$1 AND principal_id=$2`,[id,p]);if(current.rowCount!==1)throw Object.assign(new Error("WATCH_NOT_FOUND"),{statusCode:404});await assertPrincipalInNode(client,p,current.rows[0].node_id);const row=await client.query(`UPDATE knowledge_watches SET name=COALESCE($2,name),intent=COALESCE($3,intent),enabled=COALESCE($4,enabled),event_types=COALESCE($5,event_types),subject_types=COALESCE($6,subject_types),impact_kinds=COALESCE($7,impact_kinds),keywords=COALESCE($8,keywords),focus=COALESCE($9::jsonb,focus),min_event_confidence=COALESCE($10,min_event_confidence),min_impact_confidence=COALESCE($11,min_impact_confidence),min_score=COALESCE($12,min_score),cooldown_seconds=COALESCE($13,cooldown_seconds),channels=COALESCE($14,channels),updated_at=now() WHERE id=$1 RETURNING *`,[id,body.name??null,body.intent??null,body.enabled??null,body.event_types??null,body.subject_types??null,body.impact_kinds??null,body.keywords??null,body.focus?JSON.stringify(body.focus):null,body.min_event_confidence??null,body.min_impact_confidence??null,body.min_score??null,body.cooldown_seconds??null,body.channels??null]);return row.rows[0];});return reply.send(result);});
  app.post("/v1/watch/evaluate/:eventId",async(request,reply)=>{const p=principal(request),{eventId}=request.params as {eventId:string},body=request.body as {node_id:string;workspace_id:string};const result=await withTransaction(async client=>{await assertPrincipalInNode(client,p,body.node_id);await assertWorkspace(client,body.node_id,body.workspace_id);return evaluateEventForWatches(client,{eventId,nodeId:body.node_id,workspaceId:body.workspace_id});});return reply.send({matches:result});});
  app.post("/v1/watch/reevaluate",async(request,reply)=>{const p=principal(request),body=request.body as {node_id:string;workspace_id:string;since?:string;limit?:number};const result=await withTransaction(async client=>{await assertPrincipalInNode(client,p,body.node_id);await assertWorkspace(client,body.node_id,body.workspace_id);return reevaluateRecentEvents(client,{nodeId:body.node_id,workspaceId:body.workspace_id,since:body.since,limit:body.limit});});return reply.send({matches:result});});
  app.get("/v1/watch/inbox",async(request,reply)=>{const p=principal(request),q=request.query as {node_id?:string;workspace_id?:string;status?:string;limit?:string};if(!q.node_id||!q.workspace_id)return reply.code(400).send({error:"NODE_AND_WORKSPACE_REQUIRED"});const rows=await withTransaction(async client=>{await assertPrincipalInNode(client,p,q.node_id!);await assertWorkspace(client,q.node_id!,q.workspace_id!);return client.query(`SELECT wa.*,wm.score,wm.explanation,kw.name AS watch_name,kw.intent AS watch_intent FROM watch_alerts wa JOIN watch_matches wm ON wm.id=wa.match_id JOIN knowledge_watches kw ON kw.id=wa.watch_id WHERE wa.node_id=$1 AND wa.workspace_id=$2 AND wa.principal_id=$3 AND ($4::text IS NULL OR wa.status=$4) ORDER BY wa.surfaced_at DESC LIMIT $5`,[q.node_id,q.workspace_id,p,q.status??null,Math.max(1,Math.min(100,Number(q.limit??30)))]);});return reply.send({alerts:rows.rows});});
  app.patch("/v1/watch/inbox/:id",async(request,reply)=>{const p=principal(request),{id}=request.params as {id:string},body=request.body as {status:"read"|"dismissed"|"unread"};if(!["read","dismissed","unread"].includes(body.status))return reply.code(400).send({error:"INVALID_ALERT_STATUS"});const row=await withTransaction(async client=>client.query(`UPDATE watch_alerts SET status=$3,read_at=CASE WHEN $3='read' THEN now() ELSE read_at END,dismissed_at=CASE WHEN $3='dismissed' THEN now() ELSE dismissed_at END WHERE id=$1 AND principal_id=$2 RETURNING *`,[id,p,body.status]));if(row.rowCount!==1)return reply.code(404).send({error:"WATCH_ALERT_NOT_FOUND"});return reply.send(row.rows[0]);});
}
