const invoke=(cmd,args={})=>window.__TAURI_INTERNALS__?.invoke(cmd,args);
const titles={home:'Your knowledge, persistent.',vault:'Vault',corpora:'Corpus Explorer',search:'Search',graph:'Knowledge Graph',capture:'Capture',cortex:'Cortex',trace:'Trace',models:'Model Settings',connections:'Connections'};
let vaultRoot='';
function show(view){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));document.getElementById(view)?.classList.add('active');document.querySelector(`[data-view="${view}"]`)?.classList.add('active');document.getElementById('view-title').textContent=titles[view]||'CERVEL';}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>show(b.dataset.view));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>show(b.dataset.go));document.getElementById('capture-btn').onclick=()=>show('capture');
function requestVaultCredentials(suggested=''){return new Promise(resolve=>{const veil=document.createElement('div');veil.className='credential-veil';veil.innerHTML=`<form class="credential-card"><small>LOCAL VAULT</small><h3>Unlock CERVEL</h3><p>Your passphrase is used only for this local session and is not stored in the renderer.</p><input name="vault" spellcheck="false" placeholder="Vault path" value="${String(suggested).replaceAll('&','&amp;').replaceAll('"','&quot;')}"><input name="passphrase" type="password" autocomplete="off" placeholder="Vault passphrase"><div><button type="button" data-cancel>Cancel</button><button class="primary" type="submit">Unlock & Start</button></div><small class="credential-error"></small></form>`;document.body.appendChild(veil);const form=veil.querySelector('form'),vault=form.elements.vault,pass=form.elements.passphrase,error=veil.querySelector('.credential-error');pass.focus();veil.querySelector('[data-cancel]').onclick=()=>{veil.remove();resolve(null)};form.onsubmit=e=>{e.preventDefault();if(!vault.value||pass.value.length<12){error.textContent='Choose a Vault and enter a 12+ character passphrase.';return;}const result={vaultPath:vault.value,passphrase:pass.value};pass.value='';veil.remove();resolve(result);};});}
async function refresh(){try{const s=await invoke('node_status');const live=!!s?.running;document.getElementById('node-dot').classList.toggle('live',live);document.getElementById('node-label').textContent=live?'Local Node running':'Local Node offline';document.getElementById('node-endpoint').textContent=s?.endpoint||'127.0.0.1:8787';document.getElementById('connection-node').textContent=live?'Healthy':'Offline';document.getElementById('node-btn').textContent=live?'Stop Node':'Start Node';if(s?.vault){vaultRoot=s.vault;document.getElementById('vault-path').textContent=s.vault.split('/').slice(-2).join('/');}}catch{document.getElementById('node-label').textContent='Desktop bridge unavailable';}}
document.getElementById('node-btn').onclick=async()=>{const running=document.getElementById('node-dot').classList.contains('live');try{if(running){await invoke('stop_local_node');}else{const credentials=await requestVaultCredentials(vaultRoot||await invoke('vault_home')||'');if(!credentials)return;await invoke('start_local_node',credentials);vaultRoot=credentials.vaultPath;credentials.passphrase='';}}catch(e){window.alert(String(e));}finally{setTimeout(refresh,400)}};
document.getElementById('browser-pair').onclick=async()=>{try{const msg=await invoke('register_browser_bridge');document.getElementById('browser-pair').textContent=msg||'Registration started';}catch(e){document.getElementById('browser-pair').textContent='Unlock Vault first';}};
(async()=>{try{vaultRoot=await invoke('vault_home')||'';document.getElementById('vault-path').textContent='Not unlocked';}catch{}await refresh();setInterval(refresh,5000)})();
