const cervelInvoke=(cmd,args={})=>window.__TAURI__?.core?.invoke(cmd,args);
const escapeHtml=(value='')=>String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const explorerState={type:'',corpusKey:'',megaTab:'',subtab:'',label:'All canonical knowledge',selected:''};
let explorerSnapshot=null;
let captureTarget=null;
function friendlyWorkspaceError(error){
  console.error('CERVEL Desktop workspace operation failed',error);
  const text=String(error||'');
  if(text.includes('Unlock a Vault')||text.includes('session is locked'))return 'Unlock your Vault to continue.';
  if(text.includes('Local Node request failed'))return 'The Local Node could not complete this request. Confirm it is healthy, then retry.';
  return 'CERVEL could not complete this operation. Your knowledge was not changed. Retry after confirming the Vault is unlocked.';
}
function setCaptureStatus(message,kind=''){
  const el=document.getElementById('capture-receipt');if(!el)return;el.textContent=message||'';el.dataset.kind=kind;
}
function setExplorerContext(label){explorerState.label=label||'All canonical knowledge';const el=document.getElementById('explorer-context');if(el)el.textContent=explorerState.label}
function resetExplorerToAll(){
  explorerState.type='';explorerState.corpusKey='';explorerState.megaTab='';explorerState.subtab='';explorerState.selected='';
  captureTarget=null;
  setExplorerContext('All canonical knowledge');
}
function activeFolderContext(){
  if(!explorerState.corpusKey||!explorerState.megaTab)return null;
  return {corpusKey:explorerState.corpusKey,megaTab:explorerState.megaTab,subtab:explorerState.subtab||'',label:explorerState.label};
}
function setFolderContext({corpusKey='',megaTab='',subtab='',label='All canonical knowledge'}={}){
  explorerState.type='';explorerState.corpusKey=corpusKey;explorerState.megaTab=megaTab;explorerState.subtab=subtab;explorerState.selected='';
  captureTarget=activeFolderContext();
  setExplorerContext(label);
}
async function fileCapturedObject(ckoId,target=captureTarget){
  if(!ckoId||!target?.corpusKey||!target?.megaTab)return null;
  return cervelInvoke('file_corpus_membership',{ckoId,corpusKey:target.corpusKey,megaTab:target.megaTab,subtab:target.subtab||''});
}
async function refreshKnowledgeSurfaces({reset=false}={}){
  if(reset)resetExplorerToAll();
  await loadExplorer();
  await loadVault(document.getElementById('vault-search')?.value.trim()||'');
  await window.CERVEL_HOME?.loadHome?.();
}
async function loadVaultCatalog(){const host=document.getElementById('vault-catalog');if(!host)return;try{const result=await cervelInvoke('vault_catalog');const vaults=result?.vaults||[];document.getElementById('explorer-vault-count').textContent=String(vaults.length);host.innerHTML=vaults.length?vaults.map(v=>`<button class="explorer-link vault-link ${v.active?'active':''}" data-vault-path="${escapeHtml(v.path)}"><span>${escapeHtml(v.name||'Vault')}</span><b>${v.active?'ACTIVE':'LOCKED'}</b></button>`).join(''):'<div class="explorer-muted">No local Vaults found.</div>';host.querySelectorAll('[data-vault-path]').forEach(button=>button.onclick=async()=>{if(button.classList.contains('active'))return;const credentials=await credentialDialog({suggested:button.dataset.vaultPath,title:'Unlock Vault',action:'Unlock & Start'});if(!credentials)return;try{await cervelInvoke('start_local_node',credentials);credentials.passphrase='';await refresh();await loadExplorer()}catch(error){window.alert(String(error))}})}catch(error){host.innerHTML=`<div class="explorer-muted">${escapeHtml(friendlyWorkspaceError(error))}</div>`}}
function explorerButton(label,count,data){return `<button class="explorer-link" ${Object.entries(data).map(([k,v])=>`data-${k}="${escapeHtml(v)}"`).join(' ')}><span>${escapeHtml(label)}</span><b>${Number(count||0)}</b></button>`}
function corpusTree(view,key){
  const corpusLabel=key==='life'?'Life':'Enterprise';
  const branches=(view?.semantic_views||[]).map(item=>{
    const tabs=Array.isArray(item.tabs)?item.tabs:[];
    const subtabs=[...new Set(tabs.flatMap(tab=>Array.isArray(tab?.subtabs)?tab.subtabs:[]).filter(Boolean))];
    const branchLabel=`${corpusLabel} › ${item.title}`;
    return `<details class="corpus-branch" ${explorerState.corpusKey===key&&explorerState.megaTab===item.key?'open':''}>
      <summary><span>◇ ${escapeHtml(item.title)}</span><b>${Number(item.canonical_cko_count||0)}</b></summary>
      <button class="explorer-link branch-all" data-folder="1" data-corpus="${escapeHtml(key)}" data-mega-tab="${escapeHtml(item.key)}" data-subtab="" data-label="${escapeHtml(branchLabel)}"><span>All ${escapeHtml(item.title)}</span><b>${Number(item.canonical_cko_count||0)}</b></button>
      <div class="corpus-subfolders">${subtabs.map(sub=>`<button class="explorer-link corpus-subfolder" data-folder="1" data-corpus="${escapeHtml(key)}" data-mega-tab="${escapeHtml(item.key)}" data-subtab="${escapeHtml(sub)}" data-label="${escapeHtml(branchLabel+' › '+sub)}"><span>⌑ ${escapeHtml(sub)}</span></button>`).join('')}</div>
    </details>`;
  }).join('');
  return `<details class="corpus-root" open><summary>${corpusLabel} Corpus <b>${Number(view?.canonical_cko_count||0)}</b></summary>${branches}</details>`;
}
async function loadExplorer(){await loadVaultCatalog();const collections=document.getElementById('explorer-collections'),semantic=document.getElementById('explorer-semantic');try{const explorer=await cervelInvoke('vault_explorer');explorerSnapshot=explorer;collections.innerHTML=(explorer.collections||[]).map(item=>explorerButton(item.title,item.canonical_cko_count,{type:item.object_type||'',label:item.title})).join('');const groups=[];for(const key of ['life','enterprise']){const view=explorer.semantic_views?.[key];if(view)groups.push(corpusTree(view,key))}semantic.innerHTML=groups.join('')||'<div class="explorer-muted">No semantic views installed.</div>';
  document.querySelectorAll('#explorer-collections .explorer-link:not([data-folder])').forEach(button=>button.onclick=()=>{resetExplorerToAll();explorerState.type=button.dataset.type||'';setExplorerContext(button.dataset.label||button.textContent);loadVault(document.getElementById('vault-search')?.value.trim()||'')});
  document.querySelectorAll('#explorer-semantic [data-folder]').forEach(button=>button.onclick=()=>{setFolderContext({corpusKey:button.dataset.corpus||'',megaTab:button.dataset.megaTab||'',subtab:button.dataset.subtab||'',label:button.dataset.label||button.textContent});loadVault(document.getElementById('vault-search')?.value.trim()||'')});
  if(!explorerState.selected){renderActivity(explorer.activity||[])}
}catch(error){if(collections)collections.innerHTML=`<div class="explorer-muted">${escapeHtml(friendlyWorkspaceError(error))}</div>`;if(semantic)semantic.innerHTML=''}}
async function loadVault(query=''){const target=document.getElementById('vault-items');if(!target)return;target.innerHTML='<div class="workspace-loading">Loading persistent knowledge…</div>';try{const result=await cervelInvoke('vault_explorer_objects',{query,objectType:explorerState.type,corpusKey:explorerState.corpusKey,megaTab:explorerState.megaTab,subtab:explorerState.subtab,limit:100});const items=result?.objects||[];target.innerHTML=`<div class="folder-toolbar">${activeFolderContext()?`<div><small>SEMANTIC FOLDER</small><strong>${escapeHtml(explorerState.label)}</strong></div><button class="primary" id="folder-add-knowledge">+ Add knowledge here</button>`:''}</div>`+(items.length?items.map(item=>`<button class="knowledge-row ${item.id===explorerState.selected?'selected':''}" data-cko="${escapeHtml(item.id)}"><span class="knowledge-kind">${escapeHtml(item.type||'knowledge')}</span><strong>${escapeHtml(item.title||'Untitled')}</strong><small>${escapeHtml(item.summary||'')}</small><time>${escapeHtml(item.updated_at||'')}</time></button>`).join(''):'<div class="workspace-empty">No matching persistent knowledge in this view.</div>');document.getElementById('folder-add-knowledge')?.addEventListener('click',()=>openCaptureMenu(activeFolderContext()));target.querySelectorAll('[data-cko]').forEach(row=>row.onclick=()=>loadObjectDetail(row.dataset.cko))}catch(error){target.innerHTML=`<div class="workspace-empty">${escapeHtml(friendlyWorkspaceError(error))}</div>`}}
function renderActivity(activity=[]){const host=document.getElementById('inspector-activity');if(!host)return;host.innerHTML=activity.length?activity.map(event=>`<article class="activity-row"><small>${escapeHtml(event.event_type||'EVENT')}</small><strong>${escapeHtml(event.actor_type||'system')}</strong><span>${escapeHtml(event.occurred_at||'')}</span>${event.resource_type?`<em>${escapeHtml(event.io_role||'')} ${escapeHtml(event.resource_type)}</em>`:''}</article>`).join(''):'<div class="workspace-empty">No provenance events for this selection.</div>'}
function propertyRow(label,value){return `<div class="property-row"><span>${escapeHtml(label)}</span><strong>${escapeHtml(value??'—')}</strong></div>`}
function renderProperties(detail){const host=document.getElementById('inspector-properties');if(!host)return;const p=detail?.properties||{},o=detail?.object||{},memberships=detail?.memberships||[];host.innerHTML=`<div class="property-stack">${propertyRow('CKO',o.id)}${propertyRow('Type',o.type)}${propertyRow('Lifecycle',p.lifecycle_status)}${propertyRow('Epistemic',p.epistemic_status)}${propertyRow('Version',p.object_version)}${propertyRow('Confidence',p.confidence)}${propertyRow('Artifacts',p.artifact_count)}${propertyRow('Fragments',p.fragment_count)}${propertyRow('Claims',p.claim_count)}${propertyRow('Updated',p.updated_at)}</div><div class="membership-stack"><small>SEMANTIC MEMBERSHIPS</small>${memberships.length?memberships.map(m=>`<div class="membership-row"><strong>${escapeHtml(m.corpus_key)} · ${escapeHtml(m.mega_tab)}</strong><span>${escapeHtml(m.tab)}${m.subtab?` / ${escapeHtml(m.subtab)}`:''}</span></div>`).join(''):'<span class="explorer-muted">No visible memberships.</span>'}</div>`}
async function loadObjectDetail(id){if(!id)return;explorerState.selected=id;document.querySelectorAll('.knowledge-row').forEach(row=>row.classList.toggle('selected',row.dataset.cko===id));try{const detail=await cervelInvoke('vault_explorer_object',{ckoId:id});renderActivity(detail.activity||[]);renderProperties(detail);document.querySelector('[data-inspector="properties"]')?.click()}catch(error){document.getElementById('inspector-properties').innerHTML=`<div class="workspace-empty">${escapeHtml(friendlyWorkspaceError(error))}</div>`}}
async function saveNote(){const title=document.getElementById('note-title').value.trim(),body=document.getElementById('note-body').value.trim();if(!body)return;const button=document.getElementById('save-note'),status=document.getElementById('note-status');button.disabled=true;button.textContent='Saving…';if(status){status.textContent='Saving securely to your Vault…';status.dataset.kind=''}try{const ckoId=await cervelInvoke('capture_note',{title:title||'Untitled note',body});if(captureTarget)await fileCapturedObject(ckoId);document.getElementById('note-title').value='';document.getElementById('note-body').value='';button.textContent='Saved';if(status){status.textContent=captureTarget?`Saved to ${captureTarget.label}`:'Saved to your Vault';status.dataset.kind='success'}setCaptureStatus(captureTarget?`1 captured · filed in ${captureTarget.label}`:'1 captured · visible in Vault Explorer','success');await refreshKnowledgeSurfaces({reset:!captureTarget});setTimeout(()=>{button.textContent='Save to Vault';if(status){status.textContent='⌘↵ to save';status.dataset.kind=''}},1200)}catch(error){button.textContent='Retry save';if(status){status.textContent=friendlyWorkspaceError(error);status.dataset.kind='error'}setCaptureStatus('Capture failed · nothing was changed','error')}finally{button.disabled=false}}
async function importFiles(paths){if(!paths?.length)return;const receipt=document.getElementById('capture-receipt');receipt.textContent=`Importing ${paths.length} file${paths.length===1?'':'s'}…`;try{const result=await cervelInvoke('capture_files',{paths});for(const id of result.captured_ids||[]){if(captureTarget)await fileCapturedObject(id)}setCaptureStatus(`${result.accepted} captured · ${result.rejected} rejected${captureTarget?' · filed in '+captureTarget.label:''}`,result.rejected?'error':'success');await refreshKnowledgeSurfaces({reset:!captureTarget})}catch(error){setCaptureStatus(friendlyWorkspaceError(error),'error')}}
function fileToBase64(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(reader.error||new Error('Unable to read file'));reader.onload=()=>resolve(String(reader.result).split(',')[1]||'');reader.readAsDataURL(file)})}
async function importBrowserFiles(files){const list=[...files];if(!list.length)return;const receipt=document.getElementById('capture-receipt');receipt.textContent=`Importing ${list.length} file${list.length===1?'':'s'}…`;let accepted=0,rejected=0;for(const file of list){try{const contentBase64=await fileToBase64(file);const ckoId=await cervelInvoke('capture_file_bytes',{filename:file.name,mimeType:file.type||'application/octet-stream',contentBase64});if(captureTarget)await fileCapturedObject(ckoId);accepted++}catch(error){console.error(error);rejected++}}setCaptureStatus(`${accepted} captured · ${rejected} rejected${captureTarget?' · filed in '+captureTarget.label:''}`,rejected?'error':'success');await refreshKnowledgeSurfaces({reset:!captureTarget})}
function chooseFiles(){const input=document.createElement('input');input.type='file';input.multiple=true;input.hidden=true;input.onchange=()=>{void importBrowserFiles(input.files||[]).finally(()=>input.remove())};document.body.appendChild(input);input.click()}
function closeCaptureMenu(){document.querySelector('.capture-action-veil')?.remove()}
function openSourceDialog(){closeCaptureMenu();const veil=document.createElement('div');veil.className='credential-veil capture-action-veil';veil.innerHTML='<form class="credential-card"><small>ADD KNOWLEDGE</small><h3>Add Source</h3><p>Save a source reference into your local Vault. CERVEL records and indexes the URL and your note without fetching the remote page from the Desktop shell.</p><input name="url" type="url" spellcheck="false" placeholder="https://example.com/source" required><input name="title" placeholder="Title (optional)"><textarea name="note" placeholder="Why this source matters (optional)"></textarea><div><button type="button" data-cancel>Cancel</button><button class="primary" type="submit">Add Source</button></div><small class="credential-error"></small></form>';document.body.appendChild(veil);const form=veil.querySelector('form'),error=veil.querySelector('.credential-error');veil.querySelector('[data-cancel]').onclick=()=>veil.remove();form.onsubmit=async e=>{e.preventDefault();const button=form.querySelector('[type="submit"]');button.disabled=true;try{const ckoId=await cervelInvoke('capture_source',{url:form.elements.url.value,title:form.elements.title.value,note:form.elements.note.value});if(captureTarget)await fileCapturedObject(ckoId);veil.remove();await refreshKnowledgeSurfaces({reset:!captureTarget});show('vault')}catch(err){error.textContent=friendlyWorkspaceError(err);button.disabled=false}};form.elements.url.focus()}
async function openCorpus(corpusKey){
  const key=corpusKey==='enterprise'?'enterprise':'life';setFolderContext({corpusKey:key,megaTab:'',subtab:'',label:key==='enterprise'?'Enterprise Corpus':'Life Corpus'});show('vault');await loadExplorer();await loadVault();
}
async function openSemanticView(corpusKey,megaTab,label){
  setFolderContext({corpusKey:corpusKey==='enterprise'?'enterprise':'life',megaTab:megaTab||'',subtab:'',label:label||'Semantic view'});show('vault');await loadExplorer();await loadVault();
}
function openCaptureMenu(target=null){captureTarget=target||null;closeCaptureMenu();const veil=document.createElement('div');veil.className='credential-veil capture-action-veil';veil.innerHTML='<div class="credential-card"><small>UNIFIED KNOWLEDGE CAPTURE</small><h3>+ Add knowledge</h3><p>${captureTarget?'Add directly to '+escapeHtml(captureTarget.label)+'. The CKO remains canonical and is filed by semantic membership only.':'Choose what you want CERVEL to persist through the real Local Node.'}</p><div class="capture-action-list"><button type="button" data-capture-action="note"><strong>Add Note</strong><span>Write knowledge directly into your Vault.</span></button><button type="button" data-capture-action="file"><strong>Import File</strong><span>Choose one or more local files.</span></button><button type="button" data-capture-action="source"><strong>Add Source</strong><span>Save and index a source reference.</span></button></div><div><button type="button" data-cancel>Cancel</button></div></div>';document.body.appendChild(veil);veil.querySelector('[data-cancel]').onclick=()=>veil.remove();veil.querySelector('[data-capture-action="note"]').onclick=()=>{veil.remove();show('capture');document.getElementById('note-title')?.focus()};veil.querySelector('[data-capture-action="file"]').onclick=()=>{veil.remove();show('capture');chooseFiles()};veil.querySelector('[data-capture-action="source"]').onclick=openSourceDialog}
document.addEventListener('DOMContentLoaded',()=>{window.addEventListener('cervel:corpus-change',event=>{const corpus=event.detail?.corpus;if(corpus&&document.getElementById('vault')?.classList.contains('active'))void openCorpus(corpus)});document.getElementById('save-note')?.addEventListener('click',saveNote);document.getElementById('note-body')?.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key==='Enter')saveNote()});for(const id of ['vault-search','global-search']){const search=document.getElementById(id);let timer;search?.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(()=>{loadVault(search.value.trim());if(id==='global-search')document.querySelector('[data-view="vault"]')?.click()},180)})}document.querySelectorAll('[data-inspector]').forEach(button=>button.onclick=()=>{document.querySelectorAll('[data-inspector]').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.inspector-pane').forEach(x=>x.classList.remove('active'));button.classList.add('active');document.getElementById(`inspector-${button.dataset.inspector}`)?.classList.add('active')});document.getElementById('choose-files')?.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();chooseFiles()});const drop=document.getElementById('drop-zone');['dragenter','dragover'].forEach(name=>drop?.addEventListener(name,e=>{e.preventDefault();drop.classList.add('dragging')}));['dragleave','drop'].forEach(name=>drop?.addEventListener(name,e=>{e.preventDefault();drop.classList.remove('dragging')}));drop?.addEventListener('drop',e=>{const files=[...e.dataTransfer.files];const paths=files.map(file=>file.path).filter(Boolean);if(paths.length===files.length&&paths.length)void importFiles(paths);else void importBrowserFiles(files)});document.querySelector('[data-view="vault"]')?.addEventListener('click',async()=>{await loadExplorer();await loadVault()});const globalCapture=document.getElementById('capture-btn');if(globalCapture)globalCapture.onclick=()=>openCaptureMenu(null);const vaultAdd=document.querySelector('#vault .section-head button[data-go="capture"]');if(vaultAdd)vaultAdd.onclick=e=>{e.preventDefault();openCaptureMenu(activeFolderContext())}});window.CERVEL_WORKSPACE={loadExplorer,loadVault,loadObjectDetail,importFiles,importBrowserFiles,openCaptureMenu,openSourceDialog,openCorpus,openSemanticView,refreshKnowledgeSurfaces,resetExplorerToAll,setFolderContext,fileCapturedObject};