use serde::{Deserialize, Serialize};
use std::{fs, net::TcpStream, path::{Path, PathBuf}, process::{Command, Stdio}, sync::Mutex, time::Duration};
use tauri::{AppHandle, Emitter, Manager, State};

const NODE_PORT: u16 = 8787;
const MAX_DESKTOP_FILE_BYTES: u64 = 24 * 1024 * 1024;
#[derive(Default)] struct RuntimeState { active_vault: Option<PathBuf> }
struct NodeRuntime(Mutex<RuntimeState>);
#[derive(Clone, Serialize)] struct NodeStatus { running: bool, endpoint: String, managed_by_desktop: bool, vault: Option<String> }
#[derive(Serialize, Deserialize)] struct Bootstrap { node_id: String, workspace_id: String, principal_id: String, storage_location_id: String }
#[derive(Deserialize)] struct VaultSecrets { local_api_token: String }
#[derive(Serialize, Deserialize)] struct VaultObject { id: String, #[serde(rename="type")] kind: String, title: String, summary: Option<String>, updated_at: String }
#[derive(Deserialize)] struct ObjectList { objects: Vec<VaultObject> }
#[derive(Deserialize)] struct CreatedObject { id: String }
#[derive(Serialize)] struct CaptureReceipt { accepted: usize, rejected: usize }
fn repo_root()->PathBuf { std::env::var("CERVEL_APP_ROOT").map(PathBuf::from).unwrap_or_else(|_|std::env::current_dir().unwrap_or_default()) }
fn dirs_home()->PathBuf { std::env::var_os("HOME").map(PathBuf::from).unwrap_or_else(||PathBuf::from(".")) }
fn is_node_running()->bool { TcpStream::connect_timeout(&format!("127.0.0.1:{NODE_PORT}").parse().unwrap(),Duration::from_millis(250)).is_ok() }
fn status_for(runtime:&NodeRuntime)->NodeStatus { let vault=runtime.0.lock().ok().and_then(|s|s.active_vault.as_ref().map(|p|p.to_string_lossy().to_string()));NodeStatus{running:is_node_running(),endpoint:format!("http://127.0.0.1:{NODE_PORT}"),managed_by_desktop:true,vault} }
fn cli_path()->PathBuf { repo_root().join("dist/apps/local-node/src/cli.js") }
fn validate_vault(path:&Path)->Result<(),String> { if !path.join("vault.json").is_file(){return Err("Select a CERVEL Vault containing vault.json.".into())} Ok(()) }
fn run_cli(command:&str,vault:&Path,passphrase:Option<&str>)->Result<(),String> { let cli=cli_path();if !cli.exists(){return Err("Local Node build not found. Run npm run build first.".into())}let mut process=Command::new("node");process.arg(cli).arg(command).arg("--vault").arg(vault).arg("--port").arg(NODE_PORT.to_string()).stdin(Stdio::null());if let Some(secret)=passphrase{process.env("CERVEL_VAULT_PASSPHRASE",secret);}let output=process.output().map_err(|e|format!("Unable to run CERVEL Local Node: {e}"))?;if !output.status.success(){let message=String::from_utf8_lossy(&output.stderr).trim().to_string();return Err(if message.is_empty(){format!("cervel {command} failed")}else{message})}Ok(()) }
fn active_vault(runtime:&NodeRuntime)->Result<PathBuf,String> { runtime.0.lock().map_err(|_|"Node runtime lock poisoned")?.active_vault.clone().ok_or_else(||"Unlock a Vault first.".into()) }
fn read_runtime(vault:&Path)->Result<(Bootstrap,VaultSecrets),String> { let bootstrap:Bootstrap=serde_json::from_slice(&fs::read(vault.join("runtime/bootstrap.json")).map_err(|_|"Local Node bootstrap metadata is unavailable. Start the Node first.".to_string())?).map_err(|e|e.to_string())?;let secrets:VaultSecrets=serde_json::from_slice(&fs::read(vault.join("runtime/desktop-session.json")).map_err(|_|"Desktop session is locked. Unlock the Vault again.".to_string())?).map_err(|e|e.to_string())?;Ok((bootstrap,secrets)) }
fn api(runtime:&NodeRuntime,method:&str,path:&str,body:Option<serde_json::Value>)->Result<serde_json::Value,String> { let vault=active_vault(runtime)?;let (boot,secrets)=read_runtime(&vault)?;let agent=ureq::Agent::new_with_defaults();let url=format!("http://127.0.0.1:{NODE_PORT}{path}");let request=match method{"GET"=>agent.get(&url),"POST"=>agent.post(&url),_=>return Err("Unsupported Desktop Local Node method".into())}.header("x-cervel-local-token",&secrets.local_api_token).header("x-cervel-principal-id",&boot.principal_id);let mut response=if let Some(payload)=body{request.send_json(payload)}else{request.send_empty()}.map_err(|e|format!("Local Node request failed: {e}"))?;serde_json::from_reader(response.body_mut().as_reader()).map_err(|e|e.to_string()) }
#[tauri::command] fn node_status(runtime:State<NodeRuntime>)->NodeStatus { status_for(&runtime) }
#[tauri::command] fn start_local_node(runtime:State<NodeRuntime>,vault_path:String,passphrase:String)->Result<NodeStatus,String> { if passphrase.len()<12{return Err("Vault passphrase must be at least 12 characters.".into())}let vault=PathBuf::from(vault_path);validate_vault(&vault)?;if !is_node_running(){run_cli("start",&vault,Some(&passphrase))?}let output=Command::new("node").arg(cli_path()).arg("desktop-session").arg("--vault").arg(&vault).env("CERVEL_VAULT_PASSPHRASE",&passphrase).output().map_err(|e|e.to_string())?;if !output.status.success(){return Err(String::from_utf8_lossy(&output.stderr).trim().to_string())}runtime.0.lock().map_err(|_|"Node runtime lock poisoned")?.active_vault=Some(vault);Ok(status_for(&runtime)) }
#[tauri::command] fn stop_local_node(runtime:State<NodeRuntime>)->Result<NodeStatus,String> { let vault=runtime.0.lock().map_err(|_|"Node runtime lock poisoned")?.active_vault.clone();if let Some(vault)=vault{let _=fs::remove_file(vault.join("runtime/desktop-session.json"));if is_node_running(){run_cli("lock",&vault,None)?}}Ok(status_for(&runtime)) }
#[tauri::command] fn vault_home()->String { dirs_home().join(".cervel/vaults").to_string_lossy().to_string() }
#[tauri::command] fn vault_objects(runtime:State<NodeRuntime>,query:String,limit:usize)->Result<Vec<VaultObject>,String> { let vault=active_vault(&runtime)?;let (boot,_)=read_runtime(&vault)?;let q=urlencoding::encode(&query);let value=api(&runtime,"GET",&format!("/v1/local/objects?node_id={}&q={}",urlencoding::encode(&boot.node_id),q),None)?;let mut result:ObjectList=serde_json::from_value(value).map_err(|e|e.to_string())?;result.objects.truncate(limit.min(200));Ok(result.objects) }
#[tauri::command] fn capture_note(runtime:State<NodeRuntime>,title:String,body:String)->Result<String,String> { if body.trim().is_empty(){return Err("Note body is required.".into())}let vault=active_vault(&runtime)?;let (boot,_)=read_runtime(&vault)?;let created:CreatedObject=serde_json::from_value(api(&runtime,"POST","/v1/objects",Some(serde_json::json!({"node_id":boot.node_id,"workspace_id":boot.workspace_id,"type":"note","title":if title.trim().is_empty(){"Untitled note"}else{title.trim()},"summary":body.chars().take(220).collect::<String>()})))?).map_err(|e|e.to_string())?;let _=api(&runtime,"POST",&format!("/v1/objects/{}/artifacts",created.id),Some(serde_json::json!({"storage_location_id":boot.storage_location_id,"filename":"note.txt","mime_type":"text/plain","content_base64":base64::Engine::encode(&base64::engine::general_purpose::STANDARD,body.as_bytes()),"role":"original"})))?;Ok(created.id) }
#[tauri::command] fn capture_files(runtime:State<NodeRuntime>,paths:Vec<String>)->Result<CaptureReceipt,String> { let vault=active_vault(&runtime)?;let (boot,_)=read_runtime(&vault)?;let mut accepted=0;let mut rejected=0;for raw in paths{let path=PathBuf::from(raw);let metadata=match fs::metadata(&path){Ok(v) if v.is_file()&&v.len()<=MAX_DESKTOP_FILE_BYTES=>v,_=>{rejected+=1;continue}};let bytes=match fs::read(&path){Ok(v)=>v,Err(_)=>{rejected+=1;continue}};let filename=path.file_name().and_then(|v|v.to_str()).unwrap_or("File");let created=api(&runtime,"POST","/v1/objects",Some(serde_json::json!({"node_id":boot.node_id,"workspace_id":boot.workspace_id,"type":"file","title":filename,"summary":format!("Desktop file capture · {} bytes",metadata.len())})));let created:CreatedObject=match created.and_then(|v|serde_json::from_value(v).map_err(|e|e.to_string())){Ok(v)=>v,Err(_)=>{rejected+=1;continue}};let artifact=api(&runtime,"POST",&format!("/v1/objects/{}/artifacts",created.id),Some(serde_json::json!({"storage_location_id":boot.storage_location_id,"filename":filename,"mime_type":"application/octet-stream","content_base64":base64::Engine::encode(&base64::engine::general_purpose::STANDARD,&bytes),"role":"original"})));if artifact.is_ok(){accepted+=1}else{rejected+=1}}Ok(CaptureReceipt{accepted,rejected}) }
#[tauri::command] fn choose_capture_files()->Vec<String> { Vec::new() }
#[tauri::command] fn register_browser_bridge(app:AppHandle,passphrase:String)->Result<String,String> { if passphrase.len()<12{return Err("Vault passphrase must be at least 12 characters.".into())}let script=repo_root().join("dist/scripts/browser-alpha-dev-installer.js");if !script.exists(){return Err("Browser bridge installer is not built.".into())}let state=app.state::<NodeRuntime>();let vault=active_vault(&state)?;Command::new("node").arg(script).arg("--browser").arg("chrome").arg("--vault").arg(vault).arg("--no-node").env("CERVEL_VAULT_PASSPHRASE",passphrase).env("CERVEL_DESKTOP_MANAGED","1").stdin(Stdio::null()).stdout(Stdio::null()).stderr(Stdio::null()).spawn().map_err(|e|e.to_string())?;let _=app.emit("browser-bridge:registration-started",());Ok("Browser bridge registration started".into()) }
pub fn run(){tauri::Builder::default().manage(NodeRuntime(Mutex::new(RuntimeState::default()))).invoke_handler(tauri::generate_handler![node_status,start_local_node,stop_local_node,vault_home,vault_objects,capture_note,capture_files,choose_capture_files,register_browser_bridge]).setup(|app|{use tauri::menu::{Menu,MenuItem};use tauri::tray::{TrayIconBuilder,TrayIconEvent};let open=MenuItem::with_id(app,"open","Open CERVEL",true,None::<&str>)?;let status=MenuItem::with_id(app,"status","Local Node status",true,None::<&str>)?;let quit=MenuItem::with_id(app,"quit","Quit",true,None::<&str>)?;let menu=Menu::with_items(app,&[&open,&status,&quit])?;let _tray=TrayIconBuilder::new().menu(&menu).tooltip("CERVEL — Persistent Knowledge Infrastructure").on_menu_event(|app,event|match event.id.as_ref(){"open"=>{if let Some(w)=app.get_webview_window("main"){let _=w.show();let _=w.set_focus();}},"status"=>{let state=app.state::<NodeRuntime>();let _=app.emit("node:status",status_for(&state));},"quit"=>app.exit(0),_=>{}}).on_tray_icon_event(|tray,event|if let TrayIconEvent::Click{..}=event{if let Some(w)=tray.app_handle().get_webview_window("main"){let _=w.show();let _=w.set_focus();}}).build(app)?;Ok(())}).run(tauri::generate_context!()).expect("error while running CERVEL desktop");}