use serde::Serialize;
use serde_json::Value;
use std::{fs,net::TcpStream,path::{Path,PathBuf},process::{Command,Stdio},sync::Mutex,time::Duration};
use tauri::{AppHandle,Emitter,Manager,State};

const NODE_PORT:u16=8787;
#[derive(Default)]struct RuntimeState{active_vault:Option<PathBuf>}
struct NodeRuntime(Mutex<RuntimeState>);
#[derive(Clone,Serialize)]struct NodeStatus{running:bool,endpoint:String,managed_by_desktop:bool,vault:Option<String>}
#[derive(Serialize)]struct VaultObject{id:String,title:String,summary:String,kind:String,updated_at:String}
#[derive(Serialize)]struct CaptureReceipt{accepted:usize,rejected:usize}
fn repo_root()->PathBuf{std::env::var("CERVEL_APP_ROOT").map(PathBuf::from).unwrap_or_else(|_|std::env::current_dir().unwrap_or_default())}
fn dirs_home()->PathBuf{std::env::var_os("HOME").map(PathBuf::from).unwrap_or_else(||PathBuf::from("."))}
fn is_node_running()->bool{TcpStream::connect_timeout(&format!("127.0.0.1:{NODE_PORT}").parse().unwrap(),Duration::from_millis(250)).is_ok()}
fn status_for(runtime:&NodeRuntime)->NodeStatus{let vault=runtime.0.lock().ok().and_then(|s|s.active_vault.as_ref().map(|p|p.to_string_lossy().to_string()));NodeStatus{running:is_node_running(),endpoint:format!("http://127.0.0.1:{NODE_PORT}"),managed_by_desktop:true,vault}}
fn cli_path()->PathBuf{repo_root().join("dist/apps/local-node/src/cli.js")}
fn validate_vault(path:&Path)->Result<(),String>{if !path.join("vault.json").is_file(){return Err("Select a CERVEL Vault containing vault.json.".into())}Ok(())}
fn run_cli(command:&str,vault:&Path,passphrase:Option<&str>)->Result<(),String>{let cli=cli_path();if !cli.exists(){return Err("Local Node build not found. Run npm run build first.".into())}let mut process=Command::new("node");process.arg(cli).arg(command).arg("--vault").arg(vault).arg("--port").arg(NODE_PORT.to_string()).stdin(Stdio::null());if let Some(secret)=passphrase{process.env("CERVEL_VAULT_PASSPHRASE",secret);}let output=process.output().map_err(|e|format!("Unable to run CERVEL Local Node: {e}"))?;if !output.status.success(){let message=String::from_utf8_lossy(&output.stderr).trim().to_string();return Err(if message.is_empty(){format!("cervel {command} failed")}else{message})}Ok(())}
fn active_vault(runtime:&NodeRuntime)->Result<PathBuf,String>{runtime.0.lock().map_err(|_|"Node runtime lock poisoned")?.active_vault.clone().ok_or_else(||"Unlock a Vault first.".into())}
fn workspace_store(vault:&Path)->PathBuf{vault.join("runtime/desktop-workspace.json")}
fn read_workspace(vault:&Path)->Vec<Value>{fs::read_to_string(workspace_store(vault)).ok().and_then(|v|serde_json::from_str(&v).ok()).unwrap_or_default()}
fn write_workspace(vault:&Path,items:&[Value])->Result<(),String>{let path=workspace_store(vault);if let Some(parent)=path.parent(){fs::create_dir_all(parent).map_err(|e|e.to_string())?}fs::write(path,serde_json::to_vec_pretty(items).map_err(|e|e.to_string())?).map_err(|e|e.to_string())}
fn id()->String{use std::time::{SystemTime,UNIX_EPOCH};format!("desktop-{}",SystemTime::now().duration_since(UNIX_EPOCH).unwrap_or_default().as_nanos())}
#[tauri::command]fn node_status(runtime:State<NodeRuntime>)->NodeStatus{status_for(&runtime)}
#[tauri::command]fn start_local_node(runtime:State<NodeRuntime>,vault_path:String,passphrase:String)->Result<NodeStatus,String>{if passphrase.len()<12{return Err("Vault passphrase must be at least 12 characters.".into())}let vault=PathBuf::from(vault_path);validate_vault(&vault)?;if !is_node_running(){run_cli("start",&vault,Some(&passphrase))?}runtime.0.lock().map_err(|_|"Node runtime lock poisoned")?.active_vault=Some(vault);Ok(status_for(&runtime))}
#[tauri::command]fn stop_local_node(runtime:State<NodeRuntime>)->Result<NodeStatus,String>{let vault=runtime.0.lock().map_err(|_|"Node runtime lock poisoned")?.active_vault.clone();if let Some(vault)=vault{if is_node_running(){run_cli("lock",&vault,None)?}}Ok(status_for(&runtime))}
#[tauri::command]fn vault_home()->String{dirs_home().join(".cervel/vaults").to_string_lossy().to_string()}
#[tauri::command]fn vault_objects(runtime:State<NodeRuntime>,query:String,limit:usize)->Result<Vec<VaultObject>,String>{let vault=active_vault(&runtime)?;let q=query.to_lowercase();let mut rows:Vec<VaultObject>=read_workspace(&vault).into_iter().filter_map(|v|{let title=v["title"].as_str()?.to_string();let summary=v["summary"].as_str().unwrap_or("").to_string();if !q.is_empty()&&!format!("{title} {summary}").to_lowercase().contains(&q){return None}Some(VaultObject{id:v["id"].as_str()?.to_string(),title,summary,kind:v["kind"].as_str().unwrap_or("knowledge").to_string(),updated_at:v["updated_at"].as_str().unwrap_or("").to_string()})}).collect();rows.reverse();rows.truncate(limit.min(200));Ok(rows)}
#[tauri::command]fn capture_note(runtime:State<NodeRuntime>,title:String,body:String)->Result<String,String>{if body.trim().is_empty(){return Err("Note body is required.".into())}let vault=active_vault(&runtime)?;let mut items=read_workspace(&vault);let object_id=id();items.push(serde_json::json!({"id":object_id,"kind":"note","title":title.trim(),"summary":body.chars().take(220).collect::<String>(),"body":body,"source":"desktop_capture","provenance":{"embodiment":"desktop","acquisition":"human_authored"},"updated_at":format!("{}",chrono_now())}));write_workspace(&vault,&items)?;Ok(object_id)}
#[tauri::command]fn capture_files(runtime:State<NodeRuntime>,paths:Vec<String>)->Result<CaptureReceipt,String>{let vault=active_vault(&runtime)?;let mut items=read_workspace(&vault);let mut accepted=0;let mut rejected=0;for raw in paths{let path=PathBuf::from(raw);if !path.is_file(){rejected+=1;continue}let metadata=fs::metadata(&path).map_err(|e|e.to_string())?;if metadata.len()>100*1024*1024{rejected+=1;continue}let filename=path.file_name().and_then(|v|v.to_str()).unwrap_or("File").to_string();let artifact_dir=vault.join("artifacts/desktop");fs::create_dir_all(&artifact_dir).map_err(|e|e.to_string())?;let object_id=id();let target=artifact_dir.join(format!("{}-{}",object_id,filename));if fs::copy(&path,&target).is_err(){rejected+=1;continue}items.push(serde_json::json!({"id":object_id,"kind":"file","title":filename,"summary":format!("Desktop file capture · {} bytes",metadata.len()),"artifact_path":target.to_string_lossy(),"source":"desktop_capture","provenance":{"embodiment":"desktop","acquisition":"local_file_import","original_path":path.to_string_lossy()},"updated_at":format!("{}",chrono_now())}));accepted+=1;}write_workspace(&vault,&items)?;Ok(CaptureReceipt{accepted,rejected})}
#[tauri::command]fn choose_capture_files()->Vec<String>{Vec::new()}
fn chrono_now()->u64{use std::time::{SystemTime,UNIX_EPOCH};SystemTime::now().duration_since(UNIX_EPOCH).unwrap_or_default().as_secs()}
#[tauri::command]fn register_browser_bridge(app:AppHandle,passphrase:String)->Result<String,String>{if passphrase.len()<12{return Err("Vault passphrase must be at least 12 characters.".into())}let script=repo_root().join("dist/scripts/browser-alpha-dev-installer.js");if !script.exists(){return Err("Browser bridge installer is not built.".into())}let state=app.state::<NodeRuntime>();let vault=active_vault(&state)?;Command::new("node").arg(script).arg("--browser").arg("chrome").arg("--vault").arg(vault).arg("--no-node").env("CERVEL_VAULT_PASSPHRASE",passphrase).env("CERVEL_DESKTOP_MANAGED","1").stdin(Stdio::null()).stdout(Stdio::null()).stderr(Stdio::null()).spawn().map_err(|e|e.to_string())?;let _=app.emit("browser-bridge:registration-started",());Ok("Browser bridge registration started".into())}
pub fn run(){tauri::Builder::default().manage(NodeRuntime(Mutex::new(RuntimeState::default()))).invoke_handler(tauri::generate_handler![node_status,start_local_node,stop_local_node,vault_home,vault_objects,capture_note,capture_files,choose_capture_files,register_browser_bridge]).setup(|app|{use tauri::menu::{Menu,MenuItem};use tauri::tray::{TrayIconBuilder,TrayIconEvent};let open=MenuItem::with_id(app,"open","Open CERVEL",true,None::<&str>)?;let status=MenuItem::with_id(app,"status","Local Node status",true,None::<&str>)?;let quit=MenuItem::with_id(app,"quit","Quit",true,None::<&str>)?;let menu=Menu::with_items(app,&[&open,&status,&quit])?;let _tray=TrayIconBuilder::new().menu(&menu).tooltip("CERVEL — Persistent Knowledge Infrastructure").on_menu_event(|app,event|match event.id.as_ref(){"open"=>{if let Some(w)=app.get_webview_window("main"){let _=w.show();let _=w.set_focus();}},"status"=>{let state=app.state::<NodeRuntime>();let _=app.emit("node:status",status_for(&state));},"quit"=>app.exit(0),_=>{}}).on_tray_icon_event(|tray,event|if let TrayIconEvent::Click{..}=event{if let Some(w)=tray.app_handle().get_webview_window("main"){let _=w.show();let _=w.set_focus();}}).build(app)?;Ok(())}).run(tauri::generate_context!()).expect("error while running CERVEL desktop");}