use serde::{Deserialize, Serialize};
use std::{fs, net::TcpStream, path::{Path, PathBuf}, process::{Command, Stdio}, sync::Mutex, time::Duration};
use tauri::{AppHandle, Emitter, Manager, State};

const NODE_PORT: u16 = 8787;
const MAX_DESKTOP_FILE_BYTES: u64 = 24 * 1024 * 1024;
#[derive(Default)] struct RuntimeState { active_vault: Option<PathBuf> }
struct NodeRuntime(Mutex<RuntimeState>);
#[derive(Clone, Serialize)] struct NodeStatus { running: bool, endpoint: String, managed_by_desktop: bool, vault: Option<String> }
#[derive(Serialize, Deserialize)]
#[serde(rename_all="camelCase")]
struct Bootstrap { node_id: String, workspace_id: String, principal_id: String, storage_location_id: String }
#[derive(Deserialize)] struct VaultSecrets { local_api_token: String }
#[derive(Serialize, Deserialize)] struct VaultObject { id: String, #[serde(rename="type")] kind: String, title: String, summary: Option<String>, updated_at: String }
#[derive(Deserialize)] struct ObjectList { objects: Vec<VaultObject> }
#[derive(Deserialize)] struct CreatedObject { id: String }
#[derive(Serialize)] struct CaptureReceipt { accepted: usize, rejected: usize }
fn repo_root()->PathBuf { std::env::var("CERVEL_APP_ROOT").map(PathBuf::from).unwrap_or_else(|_|std::env::current_dir().unwrap_or_default()) }
fn dirs_home()->PathBuf { std::env::var_os("HOME").map(PathBuf::from).unwrap_or_else(||PathBuf::from(".")) }
fn is_node_running()->bool { TcpStream::connect_timeout(&format!("127.0.0.1:{NODE_PORT}").parse().unwrap(),Duration::from_millis(250)).is_ok() }
fn runtime_session_valid(vault:&Path)->bool {
    let bootstrap=vault.join("runtime/bootstrap.json");
    let session=vault.join("runtime/desktop-session.json");
    if !bootstrap.is_file()||!session.is_file(){return false}
    let Some(boot)=fs::read(&bootstrap).ok().and_then(|bytes|serde_json::from_slice::<Bootstrap>(&bytes).ok()) else{return false};
    let Some(secrets)=fs::read(&session).ok().and_then(|bytes|serde_json::from_slice::<VaultSecrets>(&bytes).ok()) else{return false};
    if secrets.local_api_token.trim().is_empty(){return false}
    let url=format!("http://127.0.0.1:{NODE_PORT}/v1/local/overview");
    let Ok(mut response)=ureq::Agent::new_with_defaults().get(&url).header("x-cervel-local-token",&secrets.local_api_token).header("x-cervel-principal-id",&boot.principal_id).call() else{return false};
    let Ok(payload)=serde_json::from_reader::<_,serde_json::Value>(response.body_mut().as_reader()) else{return false};
    payload.get("node").and_then(|node|node.get("id")).and_then(|id|id.as_str())==Some(boot.node_id.as_str())
}
fn recover_active_vault(runtime:&NodeRuntime)->Option<PathBuf> {
    if !is_node_running(){return None}
    if let Ok(mut state)=runtime.0.lock(){
        if let Some(vault)=state.active_vault.clone(){
            if runtime_session_valid(&vault){return Some(vault)}
            state.active_vault=None;
        }
        let base=dirs_home().join(".cervel/vaults");
        let mut candidates=Vec::new();
        if let Ok(entries)=fs::read_dir(base){
            for entry in entries.flatten(){
                let path=entry.path();
                if path.is_dir()&&path.join("vault.json").is_file()&&runtime_session_valid(&path){candidates.push(path)}
            }
        }
        if candidates.len()==1{
            state.active_vault=Some(candidates[0].clone());
            return state.active_vault.clone();
        }
    }
    None
}
fn status_for(runtime:&NodeRuntime)->NodeStatus {
    let running=is_node_running();
    let vault=if running{recover_active_vault(runtime).map(|p|p.to_string_lossy().to_string())}else{None};
    NodeStatus{running,endpoint:format!("http://127.0.0.1:{NODE_PORT}"),managed_by_desktop:true,vault}
}
fn cli_path()->PathBuf { repo_root().join("dist/apps/local-node/src/cli.js") }
fn validate_vault(path:&Path)->Result<(),String> { if !path.join("vault.json").is_file(){return Err("Select a CERVEL Vault containing vault.json.".into())} Ok(()) }
fn run_cli(command:&str,vault:&Path,passphrase:Option<&str>)->Result<(),String> { let cli=cli_path();if !cli.exists(){return Err("Local Node build not found. Run npm run build first.".into())}let mut process=Command::new("node");process.arg(cli).arg(command).arg("--vault").arg(vault).arg("--port").arg(NODE_PORT.to_string()).stdin(Stdio::null());if let Some(secret)=passphrase{process.env("CERVEL_VAULT_PASSPHRASE",secret);}let output=process.output().map_err(|e|format!("Unable to run CERVEL Local Node: {e}"))?;if !output.status.success(){let message=String::from_utf8_lossy(&output.stderr).trim().to_string();return Err(if message.is_empty(){format!("cervel {command} failed")}else{message})}Ok(()) }
fn active_vault(runtime:&NodeRuntime)->Result<PathBuf,String> {
    if let Some(vault)=recover_active_vault(runtime){return Ok(vault)}
    Err("Unlock a Vault first.".into())
}
fn read_runtime(vault:&Path)->Result<(Bootstrap,VaultSecrets),String> { let bootstrap:Bootstrap=serde_json::from_slice(&fs::read(vault.join("runtime/bootstrap.json")).map_err(|_|"Local Node bootstrap metadata is unavailable. Start the Node first.".to_string())?).map_err(|e|e.to_string())?;let secrets:VaultSecrets=serde_json::from_slice(&fs::read(vault.join("runtime/desktop-session.json")).map_err(|_|"Desktop session is locked. Unlock the Vault again.".to_string())?).map_err(|e|e.to_string())?;Ok((bootstrap,secrets)) }
fn api(runtime:&NodeRuntime,method:&str,path:&str,body:Option<serde_json::Value>)->Result<serde_json::Value,String> { let vault=active_vault(runtime)?;let (boot,secrets)=read_runtime(&vault)?;let agent=ureq::Agent::new_with_defaults();let url=format!("http://127.0.0.1:{NODE_PORT}{path}");let mut response=match method{"GET"=>agent.get(&url).header("x-cervel-local-token",&secrets.local_api_token).header("x-cervel-principal-id",&boot.principal_id).call(),"POST"=>{let request=agent.post(&url).header("x-cervel-local-token",&secrets.local_api_token).header("x-cervel-principal-id",&boot.principal_id);if let Some(payload)=body{request.send_json(payload)}else{request.send_empty()}},_=>return Err("Unsupported Desktop Local Node method".into())}.map_err(|e|format!("Local Node request failed: {e}"))?;serde_json::from_reader(response.body_mut().as_reader()).map_err(|e|e.to_string()) }
fn capture_bytes(runtime:&NodeRuntime,boot:&Bootstrap,kind:&str,title:&str,summary:&str,filename:&str,mime_type:&str,bytes:&[u8])->Result<String,String>{if bytes.len() as u64>MAX_DESKTOP_FILE_BYTES{return Err("File exceeds the 24 MB Desktop capture limit.".into())}let created:CreatedObject=serde_json::from_value(api(runtime,"POST","/v1/objects",Some(serde_json::json!({"node_id":boot.node_id,"workspace_id":boot.workspace_id,"type":kind,"title":title,"summary":summary})))?).map_err(|e|e.to_string())?;let _=api(runtime,"POST",&format!("/v1/objects/{}/artifacts",created.id),Some(serde_json::json!({"storage_location_id":boot.storage_location_id,"filename":filename,"mime_type":mime_type,"content_base64":base64::Engine::encode(&base64::engine::general_purpose::STANDARD,bytes),"role":"original"})))?;Ok(created.id)}
#[tauri::command] fn node_status(runtime:State<NodeRuntime>)->NodeStatus { status_for(&runtime) }
#[tauri::command] fn start_local_node(runtime:State<NodeRuntime>,vault_path:String,passphrase:String)->Result<NodeStatus,String> { if passphrase.len()<12{return Err("Vault passphrase must be at least 12 characters.".into())}let vault=PathBuf::from(vault_path);validate_vault(&vault)?;if !is_node_running(){run_cli("start",&vault,Some(&passphrase))?}let output=Command::new("node").arg(cli_path()).arg("desktop-session").arg("--vault").arg(&vault).env("CERVEL_VAULT_PASSPHRASE",&passphrase).output().map_err(|e|e.to_string())?;if !output.status.success(){return Err(String::from_utf8_lossy(&output.stderr).trim().to_string())}runtime.0.lock().map_err(|_|"Node runtime lock poisoned")?.active_vault=Some(vault);Ok(status_for(&runtime)) }
#[tauri::command] fn stop_local_node(runtime:State<NodeRuntime>)->Result<NodeStatus,String> { let vault=runtime.0.lock().map_err(|_|"Node runtime lock poisoned")?.active_vault.clone();if let Some(vault)=vault{let _=fs::remove_file(vault.join("runtime/desktop-session.json"));if is_node_running(){run_cli("lock",&vault,None)?}}Ok(status_for(&runtime)) }
#[tauri::command] fn vault_home()->String { dirs_home().join(".cervel/vaults").to_string_lossy().to_string() }
#[tauri::command] fn vault_catalog(runtime:State<NodeRuntime>)->Result<serde_json::Value,String>{let active=runtime.0.lock().map_err(|_|"Node runtime lock poisoned")?.active_vault.clone();let base=dirs_home().join(".cervel/vaults");let mut vaults=Vec::new();if let Ok(entries)=fs::read_dir(base){for entry in entries.flatten(){let path=entry.path();if !path.is_dir(){continue}let manifest_path=path.join("vault.json");let Ok(bytes)=fs::read(&manifest_path) else{continue};let Ok(manifest)=serde_json::from_slice::<serde_json::Value>(&bytes) else{continue};let name=manifest.get("name").and_then(|v|v.as_str()).map(str::to_owned).unwrap_or_else(||entry.file_name().to_string_lossy().into_owned());vaults.push(serde_json::json!({"id":manifest.get("id").and_then(|v|v.as_str()).unwrap_or(""),"name":name,"created_at":manifest.get("created_at").and_then(|v|v.as_str()).unwrap_or(""),"path":path.to_string_lossy(),"active":active.as_ref().map(|p|p==&path).unwrap_or(false)}));}}vaults.sort_by(|a,b|b.get("created_at").and_then(|v|v.as_str()).unwrap_or("").cmp(a.get("created_at").and_then(|v|v.as_str()).unwrap_or("")));Ok(serde_json::json!({"vaults":vaults}))}
#[tauri::command] fn vault_objects(runtime:State<NodeRuntime>,query:String,limit:usize)->Result<Vec<VaultObject>,String> { let vault=active_vault(&runtime)?;let (boot,_)=read_runtime(&vault)?;let q=urlencoding::encode(&query);let value=api(&runtime,"GET",&format!("/v1/local/objects?node_id={}&q={}",urlencoding::encode(&boot.node_id),q),None)?;let mut result:ObjectList=serde_json::from_value(value).map_err(|e|e.to_string())?;result.objects.truncate(limit.min(200));Ok(result.objects) }
#[tauri::command] fn vault_explorer(runtime:State<NodeRuntime>)->Result<serde_json::Value,String>{let vault=active_vault(&runtime)?;let (boot,_)=read_runtime(&vault)?;api(&runtime,"GET",&format!("/v1/local/explorer?node_id={}&workspace_id={}",urlencoding::encode(&boot.node_id),urlencoding::encode(&boot.workspace_id)),None)}
#[tauri::command] fn vault_explorer_objects(runtime:State<NodeRuntime>,query:String,object_type:String,corpus_key:String,mega_tab:String,subtab:String,limit:usize)->Result<serde_json::Value,String>{let vault=active_vault(&runtime)?;let (boot,_)=read_runtime(&vault)?;let mut path=format!("/v1/local/explorer/objects?node_id={}&workspace_id={}&limit={}",urlencoding::encode(&boot.node_id),urlencoding::encode(&boot.workspace_id),limit.min(200));if !query.trim().is_empty(){path.push_str(&format!("&q={}",urlencoding::encode(query.trim())))}if !object_type.trim().is_empty(){path.push_str(&format!("&type={}",urlencoding::encode(object_type.trim())))}if !corpus_key.trim().is_empty(){path.push_str(&format!("&corpus_key={}",urlencoding::encode(corpus_key.trim())))}if !mega_tab.trim().is_empty(){path.push_str(&format!("&mega_tab={}",urlencoding::encode(mega_tab.trim())))}if !subtab.trim().is_empty(){path.push_str(&format!("&subtab={}",urlencoding::encode(subtab.trim())))}api(&runtime,"GET",&path,None)}
#[tauri::command] fn file_corpus_membership(runtime:State<NodeRuntime>,cko_id:String,corpus_key:String,mega_tab:String,subtab:String)->Result<serde_json::Value,String>{let id=cko_id.trim();let corpus=corpus_key.trim();let branch=mega_tab.trim();if id.is_empty()||branch.is_empty()||!(corpus=="life"||corpus=="enterprise"){return Err("Valid CKO and corpus folder context are required.".into())}let vault=active_vault(&runtime)?;let (boot,_)=read_runtime(&vault)?;api(&runtime,"POST","/v1/local/explorer/file",Some(serde_json::json!({"node_id":boot.node_id,"workspace_id":boot.workspace_id,"cko_id":id,"corpus_key":corpus,"mega_tab":branch,"subtab":subtab.trim()})))}
#[tauri::command] fn vault_explorer_object(runtime:State<NodeRuntime>,cko_id:String)->Result<serde_json::Value,String>{let id=cko_id.trim();if id.is_empty()||!id.chars().all(|c|c.is_ascii_alphanumeric()||c=='-'){return Err("Invalid CKO identifier.".into())}let vault=active_vault(&runtime)?;let (boot,_)=read_runtime(&vault)?;api(&runtime,"GET",&format!("/v1/local/explorer/objects/{id}?node_id={}&workspace_id={}",urlencoding::encode(&boot.node_id),urlencoding::encode(&boot.workspace_id)),None)}
#[tauri::command] fn capture_note(runtime:State<NodeRuntime>,title:String,body:String)->Result<String,String> { if body.trim().is_empty(){return Err("Note body is required.".into())}let vault=active_vault(&runtime)?;let (boot,_)=read_runtime(&vault)?;capture_bytes(&runtime,&boot,"note",if title.trim().is_empty(){"Untitled note"}else{title.trim()},&body.chars().take(220).collect::<String>(),"note.txt","text/plain",body.as_bytes()) }
#[tauri::command] fn capture_file_bytes(runtime:State<NodeRuntime>,filename:String,mime_type:String,content_base64:String)->Result<String,String>{let safe_name=Path::new(filename.trim()).file_name().and_then(|v|v.to_str()).unwrap_or("File");if safe_name.is_empty(){return Err("File name is required.".into())}let bytes=base64::Engine::decode(&base64::engine::general_purpose::STANDARD,content_base64.as_bytes()).map_err(|_|"Invalid file payload.".to_string())?;let vault=active_vault(&runtime)?;let (boot,_)=read_runtime(&vault)?;let mime=if mime_type.trim().is_empty(){"application/octet-stream"}else{mime_type.trim()};capture_bytes(&runtime,&boot,"file",safe_name,&format!("Desktop file capture · {} bytes",bytes.len()),safe_name,mime,&bytes)}
#[tauri::command] fn capture_source(runtime:State<NodeRuntime>,url:String,title:String,note:String)->Result<String,String>{let source=url.trim();if source.len()>4096||!(source.starts_with("https://")||source.starts_with("http://")){return Err("Source must be an http(s) URL.".into())}if source.chars().any(|c|c.is_control()){return Err("Source URL contains invalid characters.".into())}let vault=active_vault(&runtime)?;let (boot,_)=read_runtime(&vault)?;let display=if title.trim().is_empty(){source}else{title.trim()};let content=if note.trim().is_empty(){format!("Source: {source}")}else{format!("Source: {source}\n\nNote: {}",note.trim())};capture_bytes(&runtime,&boot,"source",display,&format!("Source reference · {source}"),"source.txt","text/plain",content.as_bytes())}
#[tauri::command] fn capture_files(runtime:State<NodeRuntime>,paths:Vec<String>)->Result<CaptureReceipt,String> { let vault=active_vault(&runtime)?;let (boot,_)=read_runtime(&vault)?;let mut accepted=0;let mut rejected=0;for raw in paths{let path=PathBuf::from(raw);let metadata=match fs::metadata(&path){Ok(v) if v.is_file()&&v.len()<=MAX_DESKTOP_FILE_BYTES=>v,_=>{rejected+=1;continue}};let bytes=match fs::read(&path){Ok(v)=>v,Err(_)=>{rejected+=1;continue}};let filename=path.file_name().and_then(|v|v.to_str()).unwrap_or("File");if capture_bytes(&runtime,&boot,"file",filename,&format!("Desktop file capture · {} bytes",metadata.len()),filename,"application/octet-stream",&bytes).is_ok(){accepted+=1}else{rejected+=1}}Ok(CaptureReceipt{accepted,rejected}) }
#[tauri::command] fn choose_capture_files()->Vec<String> { Vec::new() }
#[tauri::command] fn search_cervel(runtime:State<NodeRuntime>,query:String,limit:usize)->Result<serde_json::Value,String>{let q=query.trim();if q.is_empty(){return Err("Search requires a query.".into())}let vault=active_vault(&runtime)?;let (boot,_)=read_runtime(&vault)?;api(&runtime,"POST","/v1/search",Some(serde_json::json!({"node_id":boot.node_id,"workspace_id":boot.workspace_id,"query":q,"limit":limit.clamp(1,50)}))) }
#[tauri::command] fn ask_cervel(runtime:State<NodeRuntime>,query:String)->Result<serde_json::Value,String>{if query.trim().is_empty(){return Err("Ask CERVEL requires a question.".into())}let vault=active_vault(&runtime)?;let (boot,_)=read_runtime(&vault)?;api(&runtime,"POST","/v1/reason",Some(serde_json::json!({"node_id":boot.node_id,"workspace_id":boot.workspace_id,"query":query.trim(),"profile":"qa","task_type":"desktop_ask","max_evidence_items":12}))) }
#[tauri::command] fn answer_trace(runtime:State<NodeRuntime>,answer_id:String)->Result<serde_json::Value,String>{let id=answer_id.trim();if id.is_empty()||!id.chars().all(|c|c.is_ascii_alphanumeric()||c=='-'){return Err("Invalid answer identifier.".into())}api(&runtime,"GET",&format!("/v1/answers/{id}/trace"),None) }
#[tauri::command] fn knowledge_graph(runtime:State<NodeRuntime>)->Result<serde_json::Value,String>{let vault=active_vault(&runtime)?;let (boot,_)=read_runtime(&vault)?;api(&runtime,"GET",&format!("/v1/local/graph?node_id={}&workspace_id={}",urlencoding::encode(&boot.node_id),urlencoding::encode(&boot.workspace_id)),None)}
#[tauri::command] fn deliverables(runtime:State<NodeRuntime>)->Result<serde_json::Value,String>{let vault=active_vault(&runtime)?;let (boot,_)=read_runtime(&vault)?;api(&runtime,"GET",&format!("/v1/local/deliverables?node_id={}&workspace_id={}",urlencoding::encode(&boot.node_id),urlencoding::encode(&boot.workspace_id)),None)}
#[tauri::command] fn connections(runtime:State<NodeRuntime>)->Result<serde_json::Value,String>{let vault=active_vault(&runtime)?;let (boot,_)=read_runtime(&vault)?;api(&runtime,"GET",&format!("/v1/local/connections?node_id={}&workspace_id={}",urlencoding::encode(&boot.node_id),urlencoding::encode(&boot.workspace_id)),None)}
#[tauri::command] fn intelligence_status(runtime:State<NodeRuntime>)->Result<serde_json::Value,String>{let vault=active_vault(&runtime)?;let (boot,_)=read_runtime(&vault)?;api(&runtime,"GET",&format!("/v1/intelligence/providers?node_id={}",urlencoding::encode(&boot.node_id)),None) }
#[tauri::command] fn intelligence_receipts(runtime:State<NodeRuntime>)->Result<serde_json::Value,String>{let vault=active_vault(&runtime)?;let (boot,_)=read_runtime(&vault)?;api(&runtime,"GET",&format!("/v1/intelligence/receipts?node_id={}&limit=40",urlencoding::encode(&boot.node_id)),None) }
#[tauri::command] fn register_browser_bridge(app:AppHandle,passphrase:String)->Result<String,String> { if passphrase.len()<12{return Err("Vault passphrase must be at least 12 characters.".into())}let script=repo_root().join("dist/scripts/browser-alpha-dev-installer.js");if !script.exists(){return Err("Browser bridge installer is not built.".into())}let state=app.state::<NodeRuntime>();let vault=active_vault(&state)?;Command::new("node").arg(script).arg("--browser").arg("chrome").arg("--vault").arg(vault).arg("--no-node").env("CERVEL_VAULT_PASSPHRASE",passphrase).env("CERVEL_DESKTOP_MANAGED","1").stdin(Stdio::null()).stdout(Stdio::null()).stderr(Stdio::null()).spawn().map_err(|e|e.to_string())?;let _=app.emit("browser-bridge:registration-started",());Ok("Browser bridge registration started".into()) }
pub fn run(){tauri::Builder::default().manage(NodeRuntime(Mutex::new(RuntimeState::default()))).invoke_handler(tauri::generate_handler![node_status,start_local_node,stop_local_node,vault_home,vault_catalog,vault_objects,vault_explorer,vault_explorer_objects,vault_explorer_object,file_corpus_membership,capture_note,capture_file_bytes,capture_source,capture_files,choose_capture_files,search_cervel,ask_cervel,answer_trace,knowledge_graph,deliverables,connections,intelligence_status,intelligence_receipts,register_browser_bridge]).setup(|app|{use tauri::menu::{Menu,MenuItem};use tauri::tray::{TrayIconBuilder,TrayIconEvent};let open=MenuItem::with_id(app,"open","Open CERVEL",true,None::<&str>)?;let status=MenuItem::with_id(app,"status","Local Node status",true,None::<&str>)?;let quit=MenuItem::with_id(app,"quit","Quit",true,None::<&str>)?;let menu=Menu::with_items(app,&[&open,&status,&quit])?;let _tray=TrayIconBuilder::new().menu(&menu).tooltip("CERVEL — Persistent Knowledge Infrastructure").on_menu_event(|app,event|match event.id.as_ref(){"open"=>{if let Some(w)=app.get_webview_window("main"){let _=w.show();let _=w.set_focus();}},"status"=>{let state=app.state::<NodeRuntime>();let _=app.emit("node:status",status_for(&state));},"quit"=>app.exit(0),_=>{}}).on_tray_icon_event(|tray,event|if let TrayIconEvent::Click{..}=event{if let Some(w)=tray.app_handle().get_webview_window("main"){let _=w.show();let _=w.set_focus();}}).build(app)?;Ok(())}).run(tauri::generate_context!()).expect("error while running CERVEL desktop");}
