import { createHash } from "node:crypto";
import { readFile, stat } from "node:fs/promises";
import { resolve } from "node:path";
import { CloudSyncEngine } from "../packages/cloud-sync/src/engine";
import { createEnrollmentBundle, generateDeviceIdentity, openEnrollmentBundle } from "../packages/cloud-sync/src/crypto";
import { InMemoryZeroKnowledgeRelay } from "../packages/cloud-sync/src/relay";
import { GoldenReport, REQUIRED_GOLDEN_CHECKS, stateDigest, verifyTrace } from "../packages/golden-path/src";

const command=process.argv[2]??"run",arg=(name:string)=>{const i=process.argv.indexOf(name);return i<0?undefined:process.argv[i+1];};
const url=process.env.CERVEL_GOLDEN_URL??"http://127.0.0.1:8787",reportPath=resolve(process.env.CERVEL_GOLDEN_REPORT??"reports/golden-path/golden-path.json");
const token=process.env.CERVEL_LOCAL_API_TOKEN??"",principal=process.env.CERVEL_GOLDEN_PRINCIPAL_ID??"",node=process.env.CERVEL_GOLDEN_NODE_ID??"",workspace=process.env.CERVEL_GOLDEN_WORKSPACE_ID??"",storage=process.env.CERVEL_GOLDEN_STORAGE_ID??"";
const requireIdentity=()=>{if(!token||!principal||!node||!workspace||!storage)throw new Error("GOLDEN_LOCAL_IDENTITY_REQUIRED");};
async function request(path:string,init:RequestInit={},mobileCapability?:string){const response=await fetch(new URL(path,url),{...init,headers:{...(!mobileCapability?{"x-cervel-local-token":token,"x-cervel-principal-id":principal}:{authorization:`Bearer ${mobileCapability}`}),...(init.body?{"content-type":"application/json"}:{}),...init.headers},signal:AbortSignal.timeout(60_000)}),text=await response.text();let body:any=text;try{body=text?JSON.parse(text):null;}catch{}if(!response.ok)throw Object.assign(new Error(body?.error??`GOLDEN_HTTP_${response.status}`),{status:response.status,body});return body;}
async function syncDrill(){const relay=new InMemoryZeroKnowledgeRelay(),setup=CloudSyncEngine.newVault(relay),a=new CloudSyncEngine(setup.vaultId,setup.rootKey,setup.device,relay);await a.register();const identity=generateDeviceIdentity(),bundle=createEnrollmentBundle(setup.rootKey,setup.vaultId,identity.registration),key=openEnrollmentBundle(bundle,identity.encryption_private_key);await a.enrollDevice(identity.registration);const b=new CloudSyncEngine(setup.vaultId,key,identity,relay);a.put("cko:golden","cko",{title:"Device A",revision:1});b.put("cko:golden","cko",{title:"Device B",revision:1});await a.sync();await b.sync();await a.sync();const restarted=new CloudSyncEngine(setup.vaultId,setup.rootKey,setup.device,relay,a.persistence());if(stateDigest(restarted.state())!==stateDigest(b.state()))throw new Error("GOLDEN_SYNC_DIVERGED");await a.revokeDevice(identity.registration.device_id);await b.sync().then(()=>{throw new Error("GOLDEN_REVOKED_DEVICE_ACCEPTED");},error=>{if(!String(error).includes("SYNC_DEVICE_REVOKED"))throw error;});return{vault_id:setup.vaultId,state_digest:stateDigest(a.state()),conflicts:a.state().entities[0]?.conflicts.length??0};}
async function run(){requireIdentity();const report=GoldenReport.start(),ready=await request("/ready"),overview=await request("/v1/local/overview");report.pass("vault_created","Encrypted Vault bootstrapped",{node_id:node}).pass("node_ready","Local Node readiness probe passed",{ready}).pass("desktop_boundary","Product surface used only the Local Node API",{endpoint:"/v1/local/overview",deployment_mode:overview.node.deployment_mode});
 const note=await readFile(resolve("fixtures/golden-path/field-note.md"),"utf8"),object=await request("/v1/objects",{method:"POST",body:JSON.stringify({node_id:node,workspace_id:workspace,type:"note",title:"Golden Path field note",summary:"Offline sovereignty and provenance"})}),artifact=await request(`/v1/objects/${object.id}/artifacts`,{method:"POST",body:JSON.stringify({storage_location_id:storage,filename:"field-note.md",mime_type:"text/markdown",content_base64:Buffer.from(note).toString("base64")})});
 const web=await readFile(resolve("fixtures/golden-path/web-evidence.txt"),"utf8"),browserBody={protocol:"cervel-capture/v0.1",request_id:`golden-browser-${Date.now()}`,capture_type:"page",source_url:"https://evidence.example.test/sovereign",canonical_url:"https://evidence.example.test/sovereign",title:"Sovereign evidence",author:"Golden Path Fixture",captured_at:new Date().toISOString(),content_text:web,mime_type:"text/plain",user:{note:"Adversarial evidence fixture",tags:["golden-path"],capture_intent:"evidence"},provenance:{acquisition:"browser_extension",browser:"CERVEL Golden Path",trust:"untrusted_web_content",instruction_policy:"never_execute"},node_id:node,workspace_id:workspace,storage_location_id:storage},browser=await request("/v1/local/captures",{method:"POST",body:JSON.stringify(browserBody)}),duplicate=await request("/v1/local/captures",{method:"POST",body:JSON.stringify(browserBody)});if(!duplicate.duplicate)throw new Error("GOLDEN_BROWSER_DEDUP_FAILED");report.pass("browser_capture","Browser evidence captured with provenance",{cko_id:browser.cko_id,job_id:browser.job_id}).pass("duplicate_detection","Duplicate browser capture resolved deterministically",{capture_id:duplicate.id});
 const provenance=await request(`/v1/objects/${browser.cko_id}/provenance`);if(!provenance.some((row:any)=>row.source?.instruction_policy==="never_execute"))throw new Error("GOLDEN_PROMPT_INJECTION_POLICY_MISSING");report.pass("prompt_injection_quarantined","Captured page instructions remained untrusted evidence",{policy:"never_execute"});
 const enrolled=await request("/v1/local/mobile/devices",{method:"POST",body:JSON.stringify({node_id:node,workspace_id:workspace,label:"Golden mobile",platform:"ios"})}),mobileText=await readFile(resolve("fixtures/golden-path/mobile-observation.txt"),"utf8"),mobile=await request("/v1/mobile/captures",{method:"POST",body:JSON.stringify({protocol:"cervel-mobile-capture/v0.1",capture_id:`golden_mobile_${Date.now()}`,device_id:enrolled.device_id,capture_type:"text",queued_at:new Date().toISOString(),vault_ref:node,title:"Golden mobile observation",text:mobileText,tags:["golden-path"],intent:"evidence",consent:{location:false,timestamp:false},provenance:{acquisition:"cervel_mobile",platform:"ios",derivatives:[],trust:"untrusted_captured_content",instruction_policy:"never_execute"}})},enrolled.capability),receipt=await request(`/v1/mobile/receipts/${mobile.receipt_id}`,{},enrolled.capability);if(receipt.status!=="ready")throw new Error("GOLDEN_MOBILE_RECEIPT_NOT_READY");report.pass("mobile_capture","Offline-queue-compatible mobile evidence produced a ready receipt",{receipt_id:mobile.receipt_id,cko_id:mobile.cko_id});
 const query="sovereign offline knowledge evidence provenance",search=await request("/v1/search",{method:"POST",body:JSON.stringify({node_id:node,workspace_id:workspace,query})});if(!search.results?.length)throw new Error("GOLDEN_RETRIEVAL_EMPTY");report.pass("retrieval","Local hybrid retrieval returned ingested evidence",{results:search.results.length});const answer=await request("/v1/reason",{method:"POST",body:JSON.stringify({node_id:node,workspace_id:workspace,query})});if(!answer.id||!answer.citations?.length)throw new Error("GOLDEN_CITATIONS_MISSING");report.pass("cited_answer","Local reasoning produced citations",{answer_id:answer.id,citations:answer.citations.length});const trace=await request(`/v1/answers/${answer.id}/trace`),verified=verifyTrace(trace);report.pass("trace_complete","Answer-to-source trace is complete",verified);
 const digest=stateDigest({objects:[object.id,browser.cko_id,mobile.cko_id],artifact:artifact.artifact.id,answer:answer.id,trace:verified.digest});report.pass("state_digest","Canonical state digest recorded",{digest,answer_id:answer.id});const sync=await syncDrill();report.pass("sync_convergence","Two offline devices converged after a deterministic conflict",sync);await request(`/v1/local/mobile/devices/${enrolled.device_id}`,{method:"DELETE"});let denied=false;try{await request("/v1/mobile/retrieve",{method:"POST",body:JSON.stringify({query})},enrolled.capability);}catch(error:any){denied=error.status===401;}if(!denied)throw new Error("GOLDEN_REVOKED_MOBILE_ACCEPTED");report.pass("revocation","Revoked mobile capability failed closed",{device_id:enrolled.device_id});await report.save(reportPath);console.log(JSON.stringify({ok:true,report:reportPath,answer_id:answer.id,digest}));}
async function resume(){requireIdentity();const report=await GoldenReport.load(reportPath),answerId=String(report.value.checks.state_digest?.evidence?.answer_id??"");const search=await request("/v1/search",{method:"POST",body:JSON.stringify({node_id:node,workspace_id:workspace,query:"sovereign offline knowledge evidence provenance"})}),trace=await request(`/v1/answers/${answerId}/trace`);if(!search.results?.length)throw new Error("GOLDEN_RESTART_RETRIEVAL_EMPTY");verifyTrace(trace);report.pass("restart_persistence","Search and Trace survived Local Node restart",{answer_id:answerId,results:search.results.length});if(process.env.CERVEL_GOLDEN_RESTORED==="true")report.pass("restore_verified","Restored Vault preserved retrieval and Trace",{answer_id:answerId});await report.save(reportPath);console.log(JSON.stringify({ok:true,report:reportPath,restarted:true,restored:process.env.CERVEL_GOLDEN_RESTORED==="true"}));}
async function finalize(){const report=await GoldenReport.load(reportPath),backupJson=JSON.parse(await readFile(resolve(arg("--backup-json")??""),"utf8")),verifyJson=JSON.parse(await readFile(resolve(arg("--verify-json")??""),"utf8")),exportDir=resolve(arg("--export-dir")??"");if(!backupJson.ok||!backupJson.backup)throw new Error("GOLDEN_BACKUP_EVIDENCE_INVALID");const bytes=await readFile(backupJson.backup),digest=createHash("sha256").update(bytes).digest("hex");if(digest!==backupJson.sha256)throw new Error("GOLDEN_BACKUP_DIGEST_MISMATCH");if(!verifyJson.ok||verifyJson.artifacts_verified<1)throw new Error("GOLDEN_VAULT_VERIFY_FAILED");await Promise.all(["vault.json","database.sql","artifacts.jsonl"].map(file=>stat(resolve(exportDir,file))));report.pass("backup_verified","Encrypted backup digest and artifact integrity verified",{sha256:digest,artifacts:verifyJson.artifacts_verified}).pass("portable_export","Documented non-proprietary export is complete",{format:"cervel-portable-export/v0.1",files:["vault.json","database.sql","artifacts.jsonl"]}).finalize(REQUIRED_GOLDEN_CHECKS);await report.save(reportPath);console.log(JSON.stringify({ok:true,report:reportPath,result:report.value.result}));}
Promise.resolve(command==="run"?run():command==="resume"?resume():command==="finalize"?finalize():Promise.reject(new Error("Usage: alpha-golden-path <run|resume|finalize>"))).catch(async error=>{try{const report=await GoldenReport.load(reportPath);report.fail("runner",error instanceof Error?error.message:String(error));await report.save(reportPath);}catch{}console.error(error);process.exit(1);});
