import{createHash}from"node:crypto";import{mkdir,writeFile}from"node:fs/promises";import{dirname,resolve}from"node:path";import{assertEverywhereContinuity,startEverywhereReport,type EverywhereEvidence,type EverywhereStage}from"../packages/everywhere-golden-path/src";
const base=process.env.CERVEL_EVERYWHERE_URL??"http://127.0.0.1:8787",token=process.env.CERVEL_LOCAL_API_TOKEN??"",principal=process.env.CERVEL_GOLDEN_PRINCIPAL_ID??"",node=process.env.CERVEL_GOLDEN_NODE_ID??"",workspace=process.env.CERVEL_GOLDEN_WORKSPACE_ID??"",storage=process.env.CERVEL_GOLDEN_STORAGE_ID??"",reportPath=resolve(process.env.CERVEL_EVERYWHERE_REPORT??"reports/everywhere-golden-path/report.json");
if(!token||!principal||!node||!workspace||!storage)throw new Error("EVERYWHERE_LOCAL_IDENTITY_REQUIRED");
async function request(path:string,init:RequestInit={},capability?:string){const response=await fetch(new URL(path,base),{...init,headers:{...(capability?{authorization:`Bearer ${capability}`}:{"x-cervel-local-token":token,"x-cervel-principal-id":principal}),...(init.body?{"content-type":"application/json"}:{}),...init.headers},signal:AbortSignal.timeout(60_000)}),text=await response.text();let body:any=text;try{body=text?JSON.parse(text):null;}catch{}if(!response.ok)throw Object.assign(new Error(body?.error??`EVERYWHERE_HTTP_${response.status}`),{status:response.status,body});return body;}
const digest=(value:unknown)=>createHash("sha256").update(JSON.stringify(value)).digest("hex");
async function main(){const marker=`everywhere-${Date.now()}-${Math.random().toString(36).slice(2,8)}`,report=startEverywhereReport(marker),stage=(name:EverywhereStage,evidence:EverywhereEvidence)=>{report.stages[name]=evidence;};
 const browserBody={protocol:"cervel-capture/v0.1",request_id:`chrome-${marker}`,capture_type:"page",source_url:`https://example.test/cervel/${marker}`,canonical_url:`https://example.test/cervel/${marker}`,title:`CERVEL Everywhere ${marker}`,author:"CERVEL Golden Path",captured_at:new Date().toISOString(),content_text:`${marker} proves one persistent knowledge object can move from Chrome to Desktop, Cortex, Trace and phone without duplication.`,mime_type:"text/plain",user:{note:"CERVEL Everywhere continuity fixture",tags:["cervel-everywhere","golden-path"],capture_intent:"remember"},provenance:{acquisition:"browser_extension",browser:"Chrome",trust:"untrusted_web_content",instruction_policy:"never_execute"},node_id:node,workspace_id:workspace,storage_location_id:storage};
 const browser=await request("/v1/local/captures",{method:"POST",body:JSON.stringify(browserBody)});if(!browser.cko_id)throw new Error("EVERYWHERE_CHROME_CAPTURE_MISSING_CKO");stage("chrome_capture",{stage:"chrome_capture",cko_id:browser.cko_id,detail:"Chrome capture created canonical CKO"});
 const desktop=await request(`/v1/local/objects?node_id=${encodeURIComponent(node)}&q=${encodeURIComponent(marker)}`);const desktopObject=desktop.objects?.find((v:any)=>v.id===browser.cko_id);if(!desktopObject)throw new Error("EVERYWHERE_DESKTOP_OBJECT_NOT_VISIBLE");stage("desktop_visible",{stage:"desktop_visible",cko_id:desktopObject.id,detail:"Desktop Vault API resolved the same CKO"});
 const query=`What does ${marker} prove about CERVEL Everywhere continuity?`,answer=await request("/v1/reason",{method:"POST",body:JSON.stringify({node_id:node,workspace_id:workspace,query})});if(!answer.id||!answer.citations?.length)throw new Error("EVERYWHERE_CORTEX_ANSWER_INVALID");stage("cortex_answer",{stage:"cortex_answer",cko_id:browser.cko_id,detail:"Cortex answered from captured knowledge",answer_id:answer.id});
 const trace=await request(`/v1/answers/${answer.id}/trace`),links=Array.isArray(trace?.chain)?trace.chain:[],sourceLink=links.find((v:any)=>v?.source?.cko_id===browser.cko_id&&v?.answer_id===answer.id&&v?.artifact?.sha256);if(!sourceLink)throw new Error("EVERYWHERE_TRACE_DOES_NOT_REACH_CAPTURE");stage("trace_verified",{stage:"trace_verified",cko_id:browser.cko_id,detail:"Trace links answer back to captured CKO",answer_id:answer.id,trace_digest:digest(sourceLink)});
 const enrolled=await request("/v1/local/mobile/devices",{method:"POST",body:JSON.stringify({node_id:node,workspace_id:workspace,label:"Everywhere Golden Phone",platform:"ios"})});try{const mobile=await request("/v1/mobile/retrieve",{method:"POST",body:JSON.stringify({query:marker})},enrolled.capability),hit=mobile.results?.find((v:any)=>v.ckoId===browser.cko_id);if(!hit)throw new Error("EVERYWHERE_PHONE_OBJECT_NOT_VISIBLE");stage("phone_visible",{stage:"phone_visible",cko_id:hit.ckoId,detail:"Phone retrieval resolved the same CKO"});}finally{await request(`/v1/local/mobile/devices/${enrolled.device_id}`,{method:"DELETE"});}
 const continuity=assertEverywhereContinuity(report);report.canonical_cko_id=continuity.cko_id;report.result="passed";report.completed_at=new Date().toISOString();report.qualification.automated_api_path="passed";await mkdir(dirname(reportPath),{recursive:true});await writeFile(reportPath,JSON.stringify(report,null,2)+"\n");console.log(JSON.stringify({ok:true,report:reportPath,...continuity,qualification:report.qualification}));}
main().catch(async error=>{console.error(error);process.exit(1);});
