import { db,withTransaction } from "../apps/api/src/db";
import { uuidv7 } from "../apps/api/src/uuidv7";
import { createKnowledgeObject } from "../apps/api/src/objects";
import { upsertDependency } from "../apps/api/src/impact-engine";
import { createWatch } from "../apps/api/src/watch-engine";
import { appendCkepEvent } from "../apps/api/src/ckep-runtime";
import { dispatchCkepJournalEvent } from "../apps/api/src/ckep-reactive";
import { createAgentSubscription } from "../apps/api/src/agent-runtime";
import { pollAgentCkepSignals } from "../apps/api/src/agent-ckep-runtime";
import { mapKnowledgeEventToCkep } from "../packages/ckep/src";

const [nodeId,workspaceId,adminId]=process.argv.slice(2);if(!nodeId||!workspaceId||!adminId)throw new Error("node workspace admin required");
async function main(){const result=await withTransaction(async client=>{const node=(await client.query(`SELECT slug FROM nodes WHERE id=$1`,[nodeId])).rows[0];if(!node)throw new Error("node missing");const cko=await createKnowledgeObject(client,{nodeId,workspaceId,type:"project",title:"Reactive Alpha",summary:"CKEP reactive test",languages:["en"],jurisdictions:[],createdBy:adminId,nodeAuthority:node.slug});const projectId=uuidv7();await upsertDependency(client,{nodeId,workspaceId,sourceType:"project",sourceId:projectId,relation:"depends_on",targetType:"cko",targetId:cko.id,confidence:.95,strength:.95,createdBy:adminId});const watch=await createWatch(client,{nodeId,workspaceId,principalId:adminId,name:"Reactive launch watch",intent:"surface project changes",eventTypes:["OBJECT_UPDATED"],impactKinds:["affected"],focus:{resource_ids:[projectId]},minEventConfidence:.5,minImpactConfidence:.2,minScore:.2,cooldownSeconds:0});
const principalId=uuidv7(),agentId=uuidv7();await client.query(`INSERT INTO principals(id,node_id,principal_type,display_name) VALUES($1,$2,'agent','Reactive Agent')`,[principalId,nodeId]);await client.query(`INSERT INTO agent_identities(id,node_id,principal_id,name,kind,capabilities) VALUES($1,$2,$3,'Reactive Agent','internal',$4)`,[agentId,nodeId,principalId,["signals"]]);await client.query(`INSERT INTO agent_workspace_grants(agent_id,node_id,workspace_id,permissions,created_by) VALUES($1,$2,$3,$4,$5)`,[agentId,nodeId,workspaceId,["events:read"],adminId]);const subscription=await createAgentSubscription(client,{principalId,nodeId,workspaceId,eventTypes:["OBJECT_UPDATED"],impactKinds:["affected"],minConfidence:.5});
const eventId=uuidv7();const envelope=mapKnowledgeEventToCkep({authority:node.slug,nodeId,workspaceId,sequence:1,row:{id:eventId,event_type:"OBJECT_UPDATED",subject_type:"cko",subject_id:cko.id,summary:"Reactive project changed",confidence:.94,observed_at:new Date().toISOString()}});const appended=await appendCkepEvent(client,{nodeId,workspaceId,principalId:adminId,envelope});const dispatched=await dispatchCkepJournalEvent(client,{journalEventId:appended.row.id,nodeId,workspaceId});const signals=await pollAgentCkepSignals(client,{principalId,nodeId,workspaceId,subscriptionId:subscription.id,limit:10});const alert=(await client.query(`SELECT wa.id FROM watch_alerts wa WHERE wa.watch_id=$1 AND wa.event_id=$2`,[watch.id,eventId])).rows[0];const impact=(await client.query(`SELECT impacted_type,impacted_id,impact_kind FROM knowledge_event_impacts WHERE event_id=$1 AND impacted_type='project' AND impacted_id=$2`,[eventId,projectId])).rows[0];
const foreign=uuidv7();await client.query(`INSERT INTO workspaces(id,node_id,slug,name,created_by) VALUES($1,$2,$3,'Reactive Foreign',$4)`,[foreign,nodeId,`reactive-${Date.now()}`,adminId]);let isolated=false;try{await dispatchCkepJournalEvent(client,{journalEventId:appended.row.id,nodeId,workspaceId:foreign});}catch(e:any){isolated=e.message==="CKEP_JOURNAL_EVENT_NOT_FOUND";}
return {journal_created:appended.created,dispatch_status:dispatched.status,impact_kind:impact?.impact_kind,watch_alert:Boolean(alert),agent_signal_count:signals.length,agent_sequence:Number(signals[0]?.sequence??0),workspace_isolated:isolated,knowledge_event_id:dispatched.knowledge_event_id};});console.log(JSON.stringify(result));await db.end();}
main().catch(async e=>{console.error(e);await db.end();process.exit(1);});
