#!/usr/bin/env node
import { randomBytes } from "node:crypto";
import { spawn, spawnSync } from "node:child_process";
import { mkdir, readFile, rm, stat, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";
import { createVault, decryptBuffer, encryptBuffer, readManifest, sha256, unlockVault, vaultPath } from "./vault";
import { LocalCloudSyncController } from "./cloud-sync";

const args=process.argv.slice(2), command=args.shift(), option=(name:string)=>{const i=args.indexOf(name);return i>=0?args[i+1]:undefined;};
const root=vaultPath(option("--vault"));
const passphrase=()=>{const value=process.env.CERVEL_VAULT_PASSPHRASE;if(!value)throw new Error("CERVEL_VAULT_PASSPHRASE is required (interactive prompting is intentionally disabled to prevent shell leakage)");return value;};
const run=(cmd:string,argv:string[],env:NodeJS.ProcessEnv=process.env)=>{const result=spawnSync(cmd,argv,{stdio:"inherit",env});if(result.status!==0)throw new Error(`${cmd} failed with exit code ${result.status}`);};
const exists=async(path:string)=>stat(path).then(()=>true).catch(()=>false);
const wait=(ms:number)=>new Promise(resolve=>setTimeout(resolve,ms));
function runtimeEntry(source:string,compiled:string):string[]{const built=resolve(compiled);return require("node:fs").existsSync(built)?[built]:[resolve("node_modules/tsx/dist/cli.mjs"),source];}

async function init(){const manifest=await createVault(root,option("--name")??"My CERVEL Vault",option("--authority")??`local-${randomBytes(4).toString("hex")}`,passphrase());console.log(JSON.stringify({ok:true,vault:root,id:manifest.id,authority:manifest.node_authority}));}
async function unlocked(){return unlockVault(root,passphrase());}
function runtimeEnv(secrets:any,manifest:any):NodeJS.ProcessEnv{return {...process.env,CERVEL_RUNTIME_MODE:"local",CERVEL_VAULT_PATH:root,CERVEL_VAULT_KEY:secrets.vault_key,CERVEL_LOCAL_API_TOKEN:secrets.local_api_token,CERVEL_NODE_AUTHORITY:manifest.node_authority,CERVEL_NODE_NAME:manifest.name,CERVEL_BOOTSTRAP_ADMIN_SUBJECT:"local-owner",CERVEL_STORAGE_DRIVER:"vault",DATABASE_URL:`postgresql://cervel:${encodeURIComponent(secrets.database_password)}@127.0.0.1:${option("--db-port")??"55432"}/cervel`,HOST:"127.0.0.1",PORT:option("--port")??"8787",CERVEL_ALLOW_ALPHA_LOGIN:"false",CERVEL_TRUST_PRINCIPAL_HEADER:"true"};}
async function start(){
  const {manifest,secrets}=await unlocked(),env=runtimeEnv(secrets,manifest),pidPath=join(root,"runtime","node.pid"),container=`cervel-vault-${manifest.id.slice(0,12)}`;
  if(await exists(pidPath)){const pid=Number(await readFile(pidPath,"utf8"));try{process.kill(pid,0);try{const response=await fetch(`http://127.0.0.1:${env.PORT}/ready`,{signal:AbortSignal.timeout(1500)});if(response.ok){console.log(JSON.stringify({ok:true,pid,url:`http://127.0.0.1:${env.PORT}`,vault:root,already_running:true}));return;}}catch{}try{process.kill(pid,"SIGTERM");}catch{}await wait(250);}catch{}await rm(pidPath,{force:true});}
  const known=spawnSync("docker",["container","inspect",container],{stdio:"ignore"}).status===0,running=known&&spawnSync("docker",["container","inspect","-f","{{.State.Running}}",container],{encoding:"utf8"}).stdout.trim()==="true";if(known&&!running)run("docker",["start",container],env);else if(!known)run("docker",["run","-d","--name",container,"--restart","unless-stopped","-e","POSTGRES_USER=cervel","-e",`POSTGRES_PASSWORD=${secrets.database_password}`,"-e","POSTGRES_DB=cervel","-p",`127.0.0.1:${option("--db-port")??"55432"}:5432`,"-v",`${join(root,"database")}:/var/lib/postgresql/data`,"pgvector/pgvector:pg16"],env);
  for(let i=0;i<30;i++){const probe=spawnSync("docker",["exec",container,"pg_isready","-U","cervel"],{stdio:"ignore"});if(probe.status===0)break;await wait(1000);if(i===29)throw new Error("Local PostgreSQL did not become ready");}
  run(process.execPath,runtimeEntry("scripts/db/migrate.ts","dist/scripts/db/migrate.js"),env);const boot=spawnSync(process.execPath,runtimeEntry("scripts/db/bootstrap.ts","dist/scripts/db/bootstrap.js"),{env,encoding:"utf8"});if(boot.status!==0)throw new Error(boot.stderr||"Bootstrap failed");await writeFile(join(root,"runtime","bootstrap.json"),boot.stdout.trim(),{mode:0o600});const log=await import("node:fs").then(fs=>fs.openSync(join(root,"runtime","node.log"),"a"));const child=spawn(process.execPath,runtimeEntry("apps/api/src/server.ts","dist/apps/api/src/server.js"),{env,detached:true,stdio:["ignore",log,log]});child.unref();await writeFile(pidPath,String(child.pid),{mode:0o600});
  for(let i=0;i<30;i++){try{const response=await fetch(`http://127.0.0.1:${env.PORT}/ready`);if(response.ok)break;}catch{}await wait(250);if(i===29)throw new Error("Local Node did not become ready; inspect runtime/node.log");}console.log(JSON.stringify({ok:true,pid:child.pid,url:`http://127.0.0.1:${env.PORT}`,vault:root}));
}
async function status(){const manifest=await readManifest(root),pidPath=join(root,"runtime","node.pid");let pid:number|null=null,running=false;if(await exists(pidPath)){pid=Number(await readFile(pidPath,"utf8"));try{process.kill(pid,0);running=true;}catch{}}console.log(JSON.stringify({ok:true,vault:root,id:manifest.id,authority:manifest.node_authority,running,pid}));}
async function lock(){const manifest=await readManifest(root),pidPath=join(root,"runtime","node.pid");if(await exists(pidPath)){const pid=Number(await readFile(pidPath,"utf8"));try{process.kill(pid,"SIGTERM");}catch{}await rm(pidPath,{force:true});}spawnSync("docker",["stop",`cervel-vault-${manifest.id.slice(0,12)}`],{stdio:"ignore"});console.log(JSON.stringify({ok:true,locked:true,vault:root}));}
async function verify(){const {manifest,artifactKey}=await unlocked();let checked=0;const index=join(root,"artifacts","index.jsonl");if(await exists(index)){for(const line of (await readFile(index,"utf8")).split("\n").filter(Boolean)){const item=JSON.parse(line),payload=await readFile(join(root,"artifacts",item.path)),plain=decryptBuffer(payload,artifactKey);if(sha256(plain)!==item.sha256)throw new Error(`Artifact integrity failure: ${item.path}`);checked++;}}console.log(JSON.stringify({ok:true,id:manifest.id,artifacts_verified:checked}));}
async function backup(){const {manifest,artifactKey}=await unlocked(),stamp=new Date().toISOString().replace(/[:.]/g,"-"),scratch=join(root,"runtime",`backup-${stamp}`);await mkdir(scratch,{recursive:true});const container=`cervel-vault-${manifest.id.slice(0,12)}`;run("docker",["exec",container,"pg_dump","-U","cervel","-Fc","-f","/tmp/cervel.dump"]);run("docker",["cp",`${container}:/tmp/cervel.dump`,join(scratch,"database.dump")]);run("tar",["-C",root,"-cf",join(scratch,"vault.tar"),"vault.json","device-public.pem","artifacts"]);const payload=Buffer.concat([await readFile(join(scratch,"database.dump")),Buffer.from("\n--CERVEL-TAR--\n"),await readFile(join(scratch,"vault.tar"))]);const output=join(root,"backups",`cervel-${stamp}.cvbackup`);await writeFile(output,encryptBuffer(payload,artifactKey),{mode:0o600});await rm(scratch,{recursive:true,force:true});console.log(JSON.stringify({ok:true,backup:output,sha256:sha256(await readFile(output))}));}
async function exportVault(){const output=resolve(option("--to")??join(root,"exports",new Date().toISOString().replace(/[:.]/g,"-"))),{manifest,artifactKey}=await unlocked(),container=`cervel-vault-${manifest.id.slice(0,12)}`;await mkdir(join(output,"artifacts"),{recursive:true,mode:0o700});await writeFile(join(output,"vault.json"),JSON.stringify({...manifest,exported_at:new Date().toISOString()},null,2)+"\n");const index=join(root,"artifacts","index.jsonl");if(await exists(index)){for(const line of (await readFile(index,"utf8")).split("\n").filter(Boolean)){const item=JSON.parse(line),plain=decryptBuffer(await readFile(join(root,"artifacts",item.path)),artifactKey),target=join(output,"artifacts",item.path.replace(/\.cvlt$/,"").replaceAll("/","__"));await writeFile(target,plain,{mode:0o600});}await writeFile(join(output,"artifacts.jsonl"),await readFile(index));}run("docker",["exec",container,"pg_dump","-U","cervel","--no-owner","--no-privileges","-f","/tmp/cervel-export.sql"]);run("docker",["cp",`${container}:/tmp/cervel-export.sql`,join(output,"database.sql")]);console.warn("Export is intentionally unencrypted; protect the destination.");console.log(JSON.stringify({ok:true,export:output,format:"cervel-portable-export/v0.1"}));}
async function restore(){const input=option("--from");if(!input)throw new Error("restore requires --from <backup.cvbackup>");const {manifest,artifactKey}=await unlocked(),pidPath=join(root,"runtime","node.pid");if(await exists(pidPath)){const pid=Number(await readFile(pidPath,"utf8"));try{process.kill(pid,"SIGTERM");}catch{}await rm(pidPath,{force:true});await wait(500);}const payload=decryptBuffer(await readFile(resolve(input)),artifactKey),marker=Buffer.from("\n--CERVEL-TAR--\n"),at=payload.indexOf(marker);if(at<0)throw new Error("Invalid CERVEL backup");const scratch=join(root,"runtime","restore");await rm(scratch,{recursive:true,force:true});await mkdir(scratch,{recursive:true});await writeFile(join(scratch,"database.dump"),payload.subarray(0,at));await writeFile(join(scratch,"vault.tar"),payload.subarray(at+marker.length));run("tar",["-C",root,"-xf",join(scratch,"vault.tar")]);const container=`cervel-vault-${manifest.id.slice(0,12)}`;if(spawnSync("docker",["container","inspect","-f","{{.State.Running}}",container],{encoding:"utf8"}).stdout.trim()!=="true")run("docker",["start",container]);run("docker",["cp",join(scratch,"database.dump"),`${container}:/tmp/cervel.dump`]);run("docker",["exec",container,"pg_restore","-U","cervel","-d","cervel","--clean","--if-exists","/tmp/cervel.dump"]);await rm(scratch,{recursive:true,force:true});console.log(JSON.stringify({ok:true,restored_from:resolve(input),node_stopped:true}));}

async function syncCommand(){const action=args.shift(),relay=option("--relay");if(action==="enable"){if(!relay)throw new Error("sync enable requires --relay <https-url>");const controller=await LocalCloudSyncController.enable(root,passphrase(),relay);console.log(JSON.stringify({ok:true,...controller.status()}));return;}if(action==="enrollment-request"){console.log(JSON.stringify(await LocalCloudSyncController.createEnrollmentRequest(root,passphrase())));return;}if(action==="accept"){const bundlePath=option("--bundle");if(!bundlePath||!relay)throw new Error("sync accept requires --bundle FILE --relay URL");console.log(JSON.stringify(await LocalCloudSyncController.acceptEnrollment(root,passphrase(),relay,JSON.parse(await readFile(resolve(bundlePath),"utf8")))));return;}const controller=await LocalCloudSyncController.load(root,passphrase());if(action==="status")console.log(JSON.stringify(controller.status()));else if(action==="run")console.log(JSON.stringify(await controller.sync()));else if(action==="pause")console.log(JSON.stringify(await controller.pause(true)));else if(action==="resume")console.log(JSON.stringify(await controller.pause(false)));else if(action==="reset")console.log(JSON.stringify(await controller.reset()));else if(action==="backup")console.log(JSON.stringify(await controller.backup()));else if(action==="delete"){const confirm=option("--confirm");if(!confirm)throw new Error("sync delete requires --confirm <vault-id>");console.log(JSON.stringify(await controller.deleteRemote(confirm)));}else if(action==="revoke"){const device=option("--device");if(!device)throw new Error("sync revoke requires --device <id>");console.log(JSON.stringify(await controller.revoke(device)));}else if(action==="enroll"){const requestPath=option("--request");if(!requestPath)throw new Error("sync enroll requires --request FILE");console.log(JSON.stringify(await controller.approveEnrollment(JSON.parse(await readFile(resolve(requestPath),"utf8")))));}else if(action==="journal"){const entity=option("--entity"),type=option("--type"),json=option("--json");if(!entity||!type||json==null)throw new Error("sync journal requires --entity ID --type TYPE --json JSON");console.log(JSON.stringify(await controller.journal(entity,type,JSON.parse(json))));}else throw new Error("Usage: cervel sync <enable|status|run|pause|resume|reset|backup|delete|revoke|enrollment-request|enroll|accept|journal>");}

async function main(){if(command==="init")return init();if(command==="start")return start();if(command==="status")return status();if(command==="lock")return lock();if(command==="backup")return backup();if(command==="restore")return restore();if(command==="export")return exportVault();if(command==="vault"&&args.shift()==="verify")return verify();if(command==="sync")return syncCommand();throw new Error("Usage: cervel <init|start|status|lock|backup|restore|export|vault verify|sync> [--vault PATH]");}
main().catch(error=>{console.error(error instanceof Error?error.message:String(error));process.exit(1);});
