#!/usr/bin/env node
import { randomBytes } from "node:crypto";
import { spawn, spawnSync } from "node:child_process";
import { mkdir, readFile, rm, stat, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";
import { createVault, decryptBuffer, encryptBuffer, readManifest, sha256, unlockVault, vaultPath } from "./vault";

const args=process.argv.slice(2), command=args.shift(), option=(name:string)=>{const i=args.indexOf(name);return i>=0?args[i+1]:undefined;};
const root=vaultPath(option("--vault"));
const passphrase=()=>{const value=process.env.CERVEL_VAULT_PASSPHRASE;if(!value)throw new Error("CERVEL_VAULT_PASSPHRASE is required (interactive prompting is intentionally disabled to prevent shell leakage)");return value;};
const run=(cmd:string,argv:string[],env:NodeJS.ProcessEnv=process.env)=>{const result=spawnSync(cmd,argv,{stdio:"inherit",env});if(result.status!==0)throw new Error(`${cmd} failed with exit code ${result.status}`);};
const exists=async(path:string)=>stat(path).then(()=>true).catch(()=>false);

async function init(){const manifest=await createVault(root,option("--name")??"My CERVEL Vault",option("--authority")??`local-${randomBytes(4).toString("hex")}`,passphrase());console.log(JSON.stringify({ok:true,vault:root,id:manifest.id,authority:manifest.node_authority}));}
async function unlocked(){return unlockVault(root,passphrase());}
function runtimeEnv(secrets:any,manifest:any):NodeJS.ProcessEnv{return {...process.env,CERVEL_RUNTIME_MODE:"local",CERVEL_VAULT_PATH:root,CERVEL_VAULT_KEY:secrets.vault_key,CERVEL_LOCAL_API_TOKEN:secrets.local_api_token,CERVEL_NODE_AUTHORITY:manifest.node_authority,CERVEL_NODE_NAME:manifest.name,CERVEL_BOOTSTRAP_ADMIN_SUBJECT:"local-owner",CERVEL_STORAGE_DRIVER:"vault",DATABASE_URL:`postgresql://cervel:${encodeURIComponent(secrets.database_password)}@127.0.0.1:${option("--db-port")??"55432"}/cervel`,HOST:"127.0.0.1",PORT:option("--port")??"8787",CERVEL_ALLOW_ALPHA_LOGIN:"false",CERVEL_TRUST_PRINCIPAL_HEADER:"true"};}
async function start(){const {manifest,secrets}=await unlocked(),env=runtimeEnv(secrets,manifest),container=`cervel-vault-${manifest.id.slice(0,12)}`;const known=spawnSync("docker",["container","inspect",container],{stdio:"ignore"}).status===0;if(known)run("docker",["start",container],env);else run("docker",["run","-d","--name",container,"--restart","unless-stopped","-e","POSTGRES_USER=cervel","-e",`POSTGRES_PASSWORD=${secrets.database_password}`,"-e","POSTGRES_DB=cervel","-p",`127.0.0.1:${option("--db-port")??"55432"}:5432`,"-v",`${join(root,"database")}:/var/lib/postgresql/data`,"pgvector/pgvector:pg16"],env);for(let i=0;i<30;i++){const probe=spawnSync("docker",["exec",container,"pg_isready","-U","cervel"],{stdio:"ignore"});if(probe.status===0)break;await new Promise(r=>setTimeout(r,1000));if(i===29)throw new Error("Local PostgreSQL did not become ready");}run(process.execPath,[resolve("node_modules/tsx/dist/cli.mjs"),"scripts/db/migrate.ts"],env);const boot=spawnSync(process.execPath,[resolve("node_modules/tsx/dist/cli.mjs"),"scripts/db/bootstrap.ts"],{env,encoding:"utf8"});if(boot.status!==0)throw new Error(boot.stderr||"Bootstrap failed");await writeFile(join(root,"runtime","bootstrap.json"),boot.stdout.trim(),{mode:0o600});const log=await import("node:fs").then(fs=>fs.openSync(join(root,"runtime","node.log"),"a"));const child=spawn(process.execPath,[resolve("node_modules/tsx/dist/cli.mjs"),"apps/api/src/server.ts"],{env,detached:true,stdio:["ignore",log,log]});child.unref();await writeFile(join(root,"runtime","node.pid"),String(child.pid),{mode:0o600});console.log(JSON.stringify({ok:true,pid:child.pid,url:`http://127.0.0.1:${env.PORT}`,vault:root}));}
async function status(){const manifest=await readManifest(root),pidPath=join(root,"runtime","node.pid");let pid:number|null=null,running=false;if(await exists(pidPath)){pid=Number(await readFile(pidPath,"utf8"));try{process.kill(pid,0);running=true;}catch{}}console.log(JSON.stringify({ok:true,vault:root,id:manifest.id,authority:manifest.node_authority,running,pid}));}
async function lock(){const manifest=await readManifest(root),pidPath=join(root,"runtime","node.pid");if(await exists(pidPath)){const pid=Number(await readFile(pidPath,"utf8"));try{process.kill(pid,"SIGTERM");}catch{}await rm(pidPath,{force:true});}spawnSync("docker",["stop",`cervel-vault-${manifest.id.slice(0,12)}`],{stdio:"ignore"});console.log(JSON.stringify({ok:true,locked:true,vault:root}));}
async function verify(){const {manifest,artifactKey}=await unlocked();let checked=0;const index=join(root,"artifacts","index.jsonl");if(await exists(index)){for(const line of (await readFile(index,"utf8")).split("\n").filter(Boolean)){const item=JSON.parse(line),payload=await readFile(join(root,"artifacts",item.path)),plain=decryptBuffer(payload,artifactKey);if(sha256(plain)!==item.sha256)throw new Error(`Artifact integrity failure: ${item.path}`);checked++;}}console.log(JSON.stringify({ok:true,id:manifest.id,artifacts_verified:checked}));}
async function backup(){const {manifest,artifactKey}=await unlocked(),stamp=new Date().toISOString().replace(/[:.]/g,"-"),scratch=join(root,"runtime",`backup-${stamp}`);await mkdir(scratch,{recursive:true});const container=`cervel-vault-${manifest.id.slice(0,12)}`;run("docker",["exec",container,"pg_dump","-U","cervel","-Fc","-f","/tmp/cervel.dump"]);run("docker",["cp",`${container}:/tmp/cervel.dump`,join(scratch,"database.dump")]);run("tar",["-C",root,"-cf",join(scratch,"vault.tar"),"vault.json","device-public.pem","artifacts"]);const payload=Buffer.concat([await readFile(join(scratch,"database.dump")),Buffer.from("\n--CERVEL-TAR--\n"),await readFile(join(scratch,"vault.tar"))]);const output=join(root,"backups",`cervel-${stamp}.cvbackup`);await writeFile(output,encryptBuffer(payload,artifactKey),{mode:0o600});await rm(scratch,{recursive:true,force:true});console.log(JSON.stringify({ok:true,backup:output,sha256:sha256(await readFile(output))}));}
async function exportVault(){const output=resolve(option("--to")??join(root,"exports",new Date().toISOString().replace(/[:.]/g,"-"))),{manifest,artifactKey}=await unlocked(),container=`cervel-vault-${manifest.id.slice(0,12)}`;await mkdir(join(output,"artifacts"),{recursive:true,mode:0o700});await writeFile(join(output,"vault.json"),JSON.stringify({...manifest,exported_at:new Date().toISOString()},null,2)+"\n");const index=join(root,"artifacts","index.jsonl");if(await exists(index)){for(const line of (await readFile(index,"utf8")).split("\n").filter(Boolean)){const item=JSON.parse(line),plain=decryptBuffer(await readFile(join(root,"artifacts",item.path)),artifactKey),target=join(output,"artifacts",item.path.replace(/\.cvlt$/,"").replaceAll("/","__"));await writeFile(target,plain,{mode:0o600});}await writeFile(join(output,"artifacts.jsonl"),await readFile(index));}run("docker",["exec",container,"pg_dump","-U","cervel","--no-owner","--no-privileges","-f","/tmp/cervel-export.sql"]);run("docker",["cp",`${container}:/tmp/cervel-export.sql`,join(output,"database.sql")]);console.warn("Export is intentionally unencrypted; protect the destination.");console.log(JSON.stringify({ok:true,export:output,format:"cervel-portable-export/v0.1"}));}
async function restore(){const input=option("--from");if(!input)throw new Error("restore requires --from <backup.cvbackup>");const {manifest,artifactKey}=await unlocked(),payload=decryptBuffer(await readFile(resolve(input)),artifactKey),marker=Buffer.from("\n--CERVEL-TAR--\n"),at=payload.indexOf(marker);if(at<0)throw new Error("Invalid CERVEL backup");const scratch=join(root,"runtime","restore");await rm(scratch,{recursive:true,force:true});await mkdir(scratch,{recursive:true});await writeFile(join(scratch,"database.dump"),payload.subarray(0,at));await writeFile(join(scratch,"vault.tar"),payload.subarray(at+marker.length));run("tar",["-C",root,"-xf",join(scratch,"vault.tar")]);const container=`cervel-vault-${manifest.id.slice(0,12)}`;run("docker",["cp",join(scratch,"database.dump"),`${container}:/tmp/cervel.dump`]);run("docker",["exec",container,"pg_restore","-U","cervel","-d","cervel","--clean","--if-exists","/tmp/cervel.dump"]);await rm(scratch,{recursive:true,force:true});console.log(JSON.stringify({ok:true,restored_from:resolve(input)}));}

async function main(){if(command==="init")return init();if(command==="start")return start();if(command==="status")return status();if(command==="lock")return lock();if(command==="backup")return backup();if(command==="restore")return restore();if(command==="export")return exportVault();if(command==="vault"&&args.shift()==="verify")return verify();throw new Error("Usage: cervel <init|start|status|lock|backup|restore|export|vault verify> [--vault PATH]");}
main().catch(error=>{console.error(error instanceof Error?error.message:String(error));process.exit(1);});
