import {readFile} from "node:fs/promises";
import {join} from "node:path";
import {CloudSyncEngine,type SyncDevice} from "../../../packages/cloud-sync/src/engine";
import {HttpSyncRelay} from "../../../packages/cloud-sync/src/http";
import {generateEmbodimentDeviceV2,createEnrollmentChallengeV2,openSyncRootForDeviceV2,sealSyncRootForDeviceV2,type DeviceKeyMaterialV2} from "../../../packages/cloud-sync/src/device-crypto";
import {enrollDeviceV2,newDeviceRegistryV2,revokeDeviceV2,rotateSessionsToEpoch,type DeviceRegistryV2} from "../../../packages/cloud-sync/src/device-registry";
import {validateEnrollmentChallengeV2,validateGrantForDevice,type EncryptedEnrollmentBundleV2,type EnrollmentChallengeV2,type EnrollmentGrantV2} from "../../../packages/cloud-sync/src/device-enrollment";
import {syncEnrollmentProfile} from "../../../packages/embodiment/src/sync-v2";
import type {CervelEmbodimentKind} from "../../../packages/embodiment/src/index";
import {LocalCloudSyncController} from "./cloud-sync";
import {atomicWrite,decryptBuffer,encryptBuffer,unlockVault} from "./vault";
type LegacyConfig={format:"cervel-cloud-sync/v0.1";relay_url:string;vault_id:string;root_key:string;device:SyncDevice;enabled_at:string};type PendingV2={challenge:EnrollmentChallengeV2;device:DeviceKeyMaterialV2;created_at:string};
const configPath=(root:string)=>join(root,"private","cloud-sync.cvlt"),statePath=(root:string)=>join(root,"private","cloud-sync-state.cvlt"),pendingPath=(root:string)=>join(root,"private","device-enrollment-v2-pending.cvlt"),registryPath=(root:string)=>join(root,"private","device-registry-v2.cvlt");
async function readEncrypted<T>(path:string,key:Buffer):Promise<T>{return JSON.parse(decryptBuffer(await readFile(path),key).toString("utf8")) as T;}async function writeEncrypted(path:string,value:unknown,key:Buffer){await atomicWrite(path,encryptBuffer(Buffer.from(JSON.stringify(value)),key));}function asLegacyDevice(device:DeviceKeyMaterialV2):SyncDevice{return {registration:{device_id:device.identity.device_id,signing_public_key:device.identity.signing_public_key,encryption_public_key:device.identity.encryption_public_key,enrolled_at:new Date().toISOString()},signing_private_key:device.signing_private_key,encryption_private_key:device.encryption_private_key};}async function loadRegistry(root:string,key:Buffer,vaultId:string){try{return await readEncrypted<DeviceRegistryV2>(registryPath(root),key);}catch{return newDeviceRegistryV2(vaultId);}}
export async function beginDeviceEnrollmentV2(root:string,passphrase:string,input:{kind:Extract<CervelEmbodimentKind,"desktop"|"browser_extension"|"mobile">;display_name:string;platform?:string;app_version?:string;node_id:string}){const unlocked=await unlockVault(root,passphrase),config=await readEncrypted<LegacyConfig>(configPath(root),unlocked.artifactKey),profile=syncEnrollmentProfile(input.kind,config.vault_id),device=generateEmbodimentDeviceV2({...profile,display_name:input.display_name,platform:input.platform,app_version:input.app_version}),challenge=createEnrollmentChallengeV2(config.vault_id,input.node_id,device.identity),pending:PendingV2={challenge,device,created_at:new Date().toISOString()};await writeEncrypted(pendingPath(root),pending,unlocked.artifactKey);return challenge;}
export async function approveDeviceEnrollmentV2(root:string,passphrase:string,challengeInput:EnrollmentChallengeV2){const challenge=validateEnrollmentChallengeV2(challengeInput),unlocked=await unlockVault(root,passphrase),config=await readEncrypted<LegacyConfig>(configPath(root),unlocked.artifactKey);if(challenge.vault_id!==config.vault_id)throw new Error("ENROLLMENT_VAULT_MISMATCH");const controller=await LocalCloudSyncController.load(root,passphrase),legacy={device_id:challenge.device.device_id,signing_public_key:challenge.device.signing_public_key,encryption_public_key:challenge.device.encryption_public_key,enrolled_at:new Date().toISOString()};await controller.approveEnrollment(legacy);let registry=await loadRegistry(root,unlocked.artifactKey,config.vault_id);const enrolled=enrollDeviceV2(registry,challenge.device,{request_id:challenge.request_id,authorizer_device_id:config.device.registration.device_id,authorizer_signature:"relay-authorized",permissions:challenge.device.requested_permissions});registry=enrolled.registry;await writeEncrypted(registryPath(root),registry,unlocked.artifactKey);const bundle=sealSyncRootForDeviceV2(Buffer.from(config.root_key,"base64url"),{vault_id:config.vault_id,device:challenge.device,sync_epoch:registry.sync_epoch,grant:enrolled.grant});return {grant:enrolled.grant,bundle};}
export async function acceptDeviceEnrollmentV2(root:string,passphrase:string,relayUrl:string,bundle:EncryptedEnrollmentBundleV2,grant:EnrollmentGrantV2){const unlocked=await unlockVault(root,passphrase),pending=await readEncrypted<PendingV2>(pendingPath(root),unlocked.artifactKey);validateEnrollmentChallengeV2(pending.challenge);validateGrantForDevice(grant,pending.device.identity);if(grant.request_id!==pending.challenge.request_id||grant.vault_id!==pending.challenge.vault_id||grant.device_id!==pending.device.identity.device_id||grant.sync_epoch!==bundle.sync_epoch)throw new Error("ENROLLMENT_GRANT_MISMATCH");const rootKey=openSyncRootForDeviceV2(bundle,pending.device,grant),legacyDevice=asLegacyDevice(pending.device),config:LegacyConfig={format:"cervel-cloud-sync/v0.1",relay_url:relayUrl,vault_id:bundle.vault_id,root_key:rootKey.toString("base64url"),device:legacyDevice,enabled_at:new Date().toISOString()},engine=new CloudSyncEngine(bundle.vault_id,rootKey,legacyDevice,new HttpSyncRelay(relayUrl));await writeEncrypted(configPath(root),config,unlocked.artifactKey);await writeEncrypted(statePath(root),engine.persistence(),unlocked.artifactKey);let registry=newDeviceRegistryV2(bundle.vault_id);registry=enrollDeviceV2(registry,pending.device.identity,{request_id:grant.request_id,authorizer_device_id:grant.authorizer_device_id,authorizer_signature:grant.authorizer_signature,permissions:grant.approved_permissions}).registry;registry={...registry,sync_epoch:grant.sync_epoch,devices:{...registry.devices,[pending.device.identity.device_id]:{...registry.devices[pending.device.identity.device_id],session:{...registry.devices[pending.device.identity.device_id].session,sync_epoch:grant.sync_epoch}}}};await writeEncrypted(registryPath(root),registry,unlocked.artifactKey);return {ok:true,vault_id:bundle.vault_id,device_id:pending.device.identity.device_id,embodiment_id:pending.device.identity.embodiment_id,sync_epoch:grant.sync_epoch};}
export async function revokeEnrolledDeviceV2(root:string,passphrase:string,deviceId:string){const unlocked=await unlockVault(root,passphrase),config=await readEncrypted<LegacyConfig>(configPath(root),unlocked.artifactKey),controller=await LocalCloudSyncController.load(root,passphrase),registry=await loadRegistry(root,unlocked.artifactKey,config.vault_id);if(deviceId===config.device.registration.device_id)throw new Error("CANNOT_REVOKE_CURRENT_DEVICE");await controller.revoke(deviceId);const next=rotateSessionsToEpoch(revokeDeviceV2(registry,deviceId));await writeEncrypted(registryPath(root),next,unlocked.artifactKey);return {ok:true,revoked:deviceId,sync_epoch:next.sync_epoch};}
export async function listEnrolledDevicesV2(root:string,passphrase:string){const unlocked=await unlockVault(root,passphrase),config=await readEncrypted<LegacyConfig>(configPath(root),unlocked.artifactKey),registry=await loadRegistry(root,unlocked.artifactKey,config.vault_id);return Object.values(registry.devices).map(({identity,session})=>({device_id:identity.device_id,embodiment_id:identity.embodiment_id,kind:identity.kind,display_name:identity.display_name,key_fingerprint:identity.key_fingerprint,sync_epoch:session.sync_epoch,enrolled_at:session.enrolled_at,revoked_at:session.revoked_at}));}
