import{advanceDemo,DEMO_STAGES,seedDemo}from"../../packages/demo-experience/src";import{demoPage}from"../../apps/api/src/demo-routes";import{demoApp,demoCss}from"../../apps/api/src/demo-assets";
describe("CERVEL Alpha Demo Experience",()=>{
 test("walks the complete Golden Path with synthetic isolated state",()=>{let s=seedDemo("investor");for(const type of["capture","ask","trace","compile","create","connect","recover"])s=advanceDemo(s,{type});expect(s).toMatchObject({stage:"recover",recovered:true,compiled:{claims:5},external_receipt:{write_access:false}});expect(s.deliverables).toEqual(expect.arrayContaining(["Investor brief.pdf","Architecture deck.pptx"]));expect(s.events.map(x=>x.type)).toEqual(expect.arrayContaining(["EVIDENCE_CAPTURED","CITED_ANSWER_CREATED","TRACE_OPENED","KNOWLEDGE_COMPILED","DELIVERABLES_RENDERED","SCOPED_ACCESS_GRANTED","VAULT_RECOVERED"]));});
 test("starts with synthetic sources and can demonstrate offline mode",()=>{const a=seedDemo(),b=advanceDemo(a,{type:"offline"});expect(a.vault.mode).toBe("hosted-demo");expect(a.sources.every(x=>x.provenance.toLowerCase().includes("synthetic"))).toBe(true);expect(b.vault.online).toBe(false);});
 test("presents all seven investor narrative stages",()=>expect(DEMO_STAGES.map(x=>x[0])).toEqual(["capture","ask","trace","compile","create","connect","recover"]));
 test("renders a responsive interactive workspace with isolated assets",()=>{expect(demoPage).toContain("CERVEL — Alpha Workspace");expect(demoPage).toContain('/demo/app.js');expect(demoCss).toContain("@media(max-width:720px)");expect(demoApp).toContain("Synthetic demo");expect(demoApp).toContain("localStorage.removeItem");});
 test("ships syntactically valid standalone browser code",()=>expect(()=>new Function(demoApp)).not.toThrow());
 test("provides functional knowledge workspace interactions",()=>{for(const feature of['data-view="graph"',"Ask CERVEL","Knowledge Graph","Deliverables","Start guided tour","new-note","global-search","note-body"])expect(demoApp).toContain(feature);});
 test("ships a dense cursor-controlled 3D knowledge graph",()=>{for(const feature of["knowledge-graph","28 nodes","Drag anywhere to orbit","onpointermove","onwheel","requestAnimationFrame(draw)","Pause motion","GRAPH_NODE_FOCUSED"])expect(demoApp).toContain(feature);expect(demoApp.match(/\['[^']+','(?:knowledge|claim|source|person|artifact)'/g)?.length).toBeGreaterThanOrEqual(28);expect(demoCss).toContain("cursor:grab");});
 test("seeds a realistic linked Vault with navigable verticals",()=>{for(const feature of["CERVEL business plan","Investor pitch deck narrative","World Wide Web","NIST AI Risk Management Framework","Open original source","History & Context","Web Library","folderView","data-folder","cervel-workspace-v3"])expect(demoApp).toContain(feature);expect(demoApp.match(/\{id:'[^']+',title:/g)?.length).toBeGreaterThanOrEqual(16);});
 test("opens graph nodes into content and presents the finished legal footer",()=>{expect(demoApp).toContain("openGraphTarget(d)");expect(demoApp).toContain("'CERVEL':'folder:Strategy'");expect(demoApp).toContain("'Contradiction':'pricing-model'");expect(demoApp).toContain("© 2026 CSIX AI LABS LLC · CERVEL Alpha");});
 test("offers knowledge-source integrations from the primary rail",()=>{for(const feature of["['integrations','⌘','Integrations']","Google Drive","Dropbox","Slack","Salesforce","HubSpot","GitHub","CERVEL MCP","data-integrate","INTEGRATION_REQUESTED"])expect(demoApp).toContain(feature);});
 test("collapses explorer folders and preserves footer and graph clearance",()=>{for(const feature of["data-collapse","state.collapsed","collapse.closed","role=\"contentinfo\"","All rights reserved"])expect(demoApp+demoCss).toContain(feature);expect(demoCss).toContain("calc(100vh - 300px)");expect(demoCss).toContain("margin-bottom:22px");});
 test("keeps every page inside the persistent-footer layout contract",()=>{for(const feature of[".app,.rail,.explorer,.workspace,.context,.view{min-height:0}",".workspace{overflow:hidden}",".status{position:relative","role=\"contentinfo\""])expect(demoCss+demoApp).toContain(feature);});
 test("persists automatic UI language and day-night appearance preferences",()=>{for(const feature of["language-select","data-theme-toggle","applyPreferences","NodeFilter.SHOW_TEXT","root.dir=lang==='ar'?'rtl':'ltr'","data-theme=\"dark\"","Español","Français","Português","Deutsch","العربية","日本語","中文"])expect(demoApp+demoCss).toContain(feature);});
 test("routes live questions through the server and archives approved conversations",()=>{for(const feature of["/v1/demo/ask","data-live-ask","data-archive-answer","askCervel","archiveConversation","OPENAI_ANSWER_CREATED","CONVERSATION_ARCHIVED","Provider storage requested: false"])expect(demoApp).toContain(feature);});
 test("escapes browser-restored and provider-returned state before inserting it into workspace HTML",()=>{expect(demoApp).toContain("var esc=function");expect(demoApp).toContain("esc(e[1])");expect(demoApp).toContain("esc(n.title)");expect(demoApp).toContain("esc(t.content)");expect(demoApp).toContain("esc(t.response_id)");});
 test("rejects unrecognized demo actions",()=>expect(()=>advanceDemo(seedDemo(),{type:"write_real_vault"})).toThrow("DEMO_ACTION_UNKNOWN"));
});
