import{advanceDemo,DEMO_STAGES,seedDemo}from"../../packages/demo-experience/src";import{demoPage}from"../../apps/api/src/demo-routes";import{demoApp,demoCss}from"../../apps/api/src/demo-assets";
describe("CERVEL Alpha Demo Experience",()=>{
 test("walks the complete Golden Path with synthetic isolated state",()=>{let s=seedDemo("investor");for(const type of["capture","ask","trace","compile","create","connect","recover"])s=advanceDemo(s,{type});expect(s).toMatchObject({stage:"recover",recovered:true,compiled:{claims:5},external_receipt:{write_access:false}});expect(s.deliverables).toEqual(expect.arrayContaining(["Investor brief.pdf","Architecture deck.pptx"]));expect(s.events.map(x=>x.type)).toEqual(expect.arrayContaining(["EVIDENCE_CAPTURED","CITED_ANSWER_CREATED","TRACE_OPENED","KNOWLEDGE_COMPILED","DELIVERABLES_RENDERED","SCOPED_ACCESS_GRANTED","VAULT_RECOVERED"]));});
 test("starts with synthetic sources and can demonstrate offline mode",()=>{const a=seedDemo(),b=advanceDemo(a,{type:"offline"});expect(a.vault.mode).toBe("hosted-demo");expect(a.sources.every(x=>x.provenance.toLowerCase().includes("synthetic"))).toBe(true);expect(b.vault.online).toBe(false);});
 test("presents all seven investor narrative stages",()=>expect(DEMO_STAGES.map(x=>x[0])).toEqual(["capture","ask","trace","compile","create","connect","recover"]));
 test("renders a responsive interactive workspace with isolated assets",()=>{expect(demoPage).toContain("CERVEL — Alpha Workspace");expect(demoPage).toContain('/demo/app.js');expect(demoCss).toContain("@media(max-width:720px)");expect(demoApp).toContain("Synthetic demo");expect(demoApp).toContain("localStorage.removeItem");});
 test("ships syntactically valid standalone browser code",()=>expect(()=>new Function(demoApp)).not.toThrow());
 test("provides functional knowledge workspace interactions",()=>{for(const feature of['data-view="graph"',"Ask CERVEL","Knowledge Graph","Deliverables","Start guided tour","new-note","global-search","note-body"])expect(demoApp).toContain(feature);});
 test("escapes browser-restored state before inserting it into workspace HTML",()=>{expect(demoApp).toContain("var esc=function");expect(demoApp).toContain("esc(e[1])");expect(demoApp).toContain("esc(n.title)");expect(demoApp).toContain("esc(state.answer)");});
 test("rejects unrecognized demo actions",()=>expect(()=>advanceDemo(seedDemo(),{type:"write_real_vault"})).toThrow("DEMO_ACTION_UNKNOWN"));
});
