import type {CervelEmbodimentKind,EmbodimentCapability,EmbodimentPermission} from "./index";
export type SyncEnrollmentProfile={kind:CervelEmbodimentKind;capabilities:EmbodimentCapability[];permissions:(vaultId:string)=>EmbodimentPermission[]};
const scoped=(vault_id:string,capability:EmbodimentCapability,effect:"allow"|"approval_required"="allow"):EmbodimentPermission=>({capability,effect,scope:{vault_id}});
export const SYNC_V2_ENROLLMENT_PROFILES:Record<"desktop"|"browser_extension"|"mobile",SyncEnrollmentProfile>={
 desktop:{kind:"desktop",capabilities:["vault.read","vault.write","vault.search","capture.note","capture.file","cortex.ask","trace.read","sync.read","sync.write","device.pair"],permissions:v=>[scoped(v,"vault.read"),scoped(v,"vault.write"),scoped(v,"vault.search"),scoped(v,"capture.note"),scoped(v,"capture.file"),scoped(v,"cortex.ask"),scoped(v,"trace.read"),scoped(v,"sync.read"),scoped(v,"sync.write"),scoped(v,"device.pair")]},
 browser_extension:{kind:"browser_extension",capabilities:["capture.page","capture.selection","capture.link","capture.pdf","capture.note","vault.read","vault.write","vault.search","sync.read","sync.write","device.pair"],permissions:v=>[scoped(v,"capture.page"),scoped(v,"capture.selection"),scoped(v,"capture.link"),scoped(v,"capture.pdf"),scoped(v,"capture.note"),scoped(v,"vault.read"),scoped(v,"vault.write"),scoped(v,"vault.search"),scoped(v,"sync.read"),scoped(v,"sync.write"),scoped(v,"device.pair")]},
 mobile:{kind:"mobile",capabilities:["capture.note","capture.voice","capture.scan","capture.file","capture.image","capture.memory","vault.read","vault.write","vault.search","sync.read","sync.write","device.pair"],permissions:v=>[scoped(v,"capture.note"),scoped(v,"capture.voice"),scoped(v,"capture.scan"),scoped(v,"capture.file"),scoped(v,"capture.image"),scoped(v,"capture.memory"),scoped(v,"vault.read"),scoped(v,"vault.write"),scoped(v,"vault.search"),scoped(v,"sync.read"),scoped(v,"sync.write"),scoped(v,"device.pair")]}
};
export function syncEnrollmentProfile(kind:"desktop"|"browser_extension"|"mobile",vaultId:string){const profile=SYNC_V2_ENROLLMENT_PROFILES[kind];return {kind:profile.kind,capabilities:[...profile.capabilities],requested_permissions:profile.permissions(vaultId)};}
