import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { homedir } from "node:os";
import { validateEvidence } from "../../../packages/capture-extension/src";

type HostConfig={format:"cervel-capture-host/v0.1";vault:string;local_node_url:string;local_api_token:string;node_id:string;workspace_id:string;principal_id:string;storage_location_id:string};
type HostMessage={command:"capture"|"status";vault?:string;evidence?:unknown};
const write=(value:unknown)=>{const body=Buffer.from(JSON.stringify(value)),header=Buffer.alloc(4);header.writeUInt32LE(body.length);process.stdout.write(Buffer.concat([header,body]));};
async function config(vault:string){if(!/^[a-zA-Z0-9._-]{1,80}$/.test(vault))throw new Error("CAPTURE_VAULT_NAME_INVALID");const parsed=JSON.parse(await readFile(join(homedir(),".cervel","native-hosts",`${vault}.json`),"utf8")) as HostConfig;if(parsed.format!=="cervel-capture-host/v0.1")throw new Error("CAPTURE_HOST_CONFIG_INVALID");const url=new URL(parsed.local_node_url);if(url.protocol!=="http:"||!["127.0.0.1","localhost","::1"].includes(url.hostname))throw new Error("CAPTURE_HOST_LOOPBACK_REQUIRED");return parsed;}
async function call(message:HostMessage){const selected=message.vault??"default",cfg=await config(selected);if(message.command==="status"){const response=await fetch(new URL("/ready",cfg.local_node_url),{signal:AbortSignal.timeout(1500)});return {ok:response.ok,vault:selected};}if(message.command!=="capture"||!message.evidence)throw new Error("CAPTURE_HOST_COMMAND_INVALID");const evidence=validateEvidence(message.evidence as never),response=await fetch(new URL("/v1/local/captures",cfg.local_node_url),{method:"POST",headers:{"content-type":"application/json","x-cervel-local-token":cfg.local_api_token,"x-cervel-principal-id":cfg.principal_id},body:JSON.stringify({...evidence,node_id:cfg.node_id,workspace_id:cfg.workspace_id,storage_location_id:cfg.storage_location_id}),signal:AbortSignal.timeout(60_000)}),text=await response.text();let payload:any;try{payload=JSON.parse(text);}catch{payload={error:text};}if(!response.ok)throw new Error(payload.error??`CAPTURE_NODE_HTTP_${response.status}`);return payload;}
let pending=Buffer.alloc(0);process.stdin.on("data",chunk=>{pending=Buffer.concat([pending,chunk]);while(pending.length>=4){const size=pending.readUInt32LE();if(size>22*1024*1024){write({ok:false,error:"CAPTURE_HOST_MESSAGE_TOO_LARGE"});process.exit(1);}if(pending.length<4+size)return;const body=pending.subarray(4,4+size);pending=pending.subarray(4+size);void Promise.resolve().then(()=>call(JSON.parse(body.toString("utf8")))).then(result=>write({ok:true,result}),error=>write({ok:false,error:error instanceof Error?error.message:String(error)}));}});
