import{readFileSync}from"node:fs";import{resolve}from"node:path";import{LIFE_BRANCHES,LIFE_CORPUS_VERSION,LIFE_TAXONOMY,classifyLife,lifeBranchPolicy,lifePolicyDigest}from"../../packages/life-corpus/src";
describe("CERVEL Life Corpus Runtime",()=>{
 test("defines all seventeen Life branches",()=>{expect(LIFE_CORPUS_VERSION).toBe("1.0");expect(LIFE_BRANCHES.map(x=>x.title)).toEqual(["Personal","Relationships & Family","Health","Work & Career","Education","Projects","Finance","Home","Memory","Personal Knowledge","Digital Life","Travel","Hobbies & Interests","Goals","Civic & Community","Legal / Administrative","Legacy"]);expect(LIFE_TAXONOMY).toHaveLength(17);expect(lifePolicyDigest()).toMatch(/^[0-9a-f]{64}$/);});
 test("applies private sensitivity defaults and sealed high-risk subtabs",()=>{expect(lifeBranchPolicy("health")).toEqual({sensitivity:"confidential",visibility:"private"});expect(lifeBranchPolicy("health","Medical Records")).toEqual({sensitivity:"sealed",visibility:"sealed"});expect(lifeBranchPolicy("finance","Accounts")).toEqual({sensitivity:"sealed",visibility:"sealed"});expect(lifeBranchPolicy("digital-life","Credentials")).toEqual({sensitivity:"sealed",visibility:"sealed"});expect(lifeBranchPolicy("legacy","Estate")).toEqual({sensitivity:"sealed",visibility:"sealed"});});
 test("classifies personal knowledge into multiple Life branches",()=>{const result=classifyLife({type:"journal",title:"Family health and travel goals",summary:"Plan a doctor visit, family trip, career milestone, and monthly budget."});expect(result.map(x=>x.mega_tab)).toEqual(expect.arrayContaining(["relationships-family","health","work-career","finance","travel","goals"]));expect(result.every(x=>x.visibility==="private")).toBe(true);});
 test("migration hardens generic views against sealed bypass",()=>{const sql=readFileSync(resolve("db/migrations/033_life_corpus_runtime.sql"),"utf8"),engine=readFileSync(resolve("apps/api/src/corpus-engine.ts"),"utf8");expect(sql).toContain("branch_sensitivity");expect(sql).toContain("life_sealed_access_sessions");expect(sql).toContain("proof_reference_hash");expect(engine).toContain("v.branch_visibility<>'sealed'");expect(engine).toContain("s.expires_at>now()");});
 test("generic corpus operations preserve reference-corpus policy authority",()=>{const engine=readFileSync(resolve("apps/api/src/corpus-engine.ts"),"utf8");expect(engine).toContain("life_corpus_branch_policies");expect(engine).toContain("enterprise_branch_policies");expect(engine).toContain("policy?.sensitivity??\"internal\"");expect(engine).toContain("branch_visibility=EXCLUDED.branch_visibility");});
 test("ships a strict membership contract",()=>{const schema=JSON.parse(readFileSync(resolve("packages/contracts/v1.0/life-corpus.schema.json"),"utf8"));expect(schema.additionalProperties).toBe(false);expect(schema.properties.mega_tab.enum).toHaveLength(17);expect(schema.properties.visibility.enum).toEqual(["private","sealed"]);});
});
